table Debt
	lineageTag: 2fd5cac2-0e13-4bfc-bd45-2c7ef079cc3f

	column month
		dataType: dateTime
		summarizeBy: none
		sourceColumn: month
		lineageTag: 129727f5-b79b-465e-b38f-b2bce2d6597d
		annotation SummarizationSetBy = User

	column facility_id
		dataType: string
		summarizeBy: none
		sourceColumn: facility_id
		lineageTag: 512bbdfe-a66b-4d55-8630-b376f2185849
		annotation SummarizationSetBy = User

	column opening_balance
		dataType: double
		summarizeBy: sum
		sourceColumn: opening_balance
		lineageTag: fe486705-4fd2-4271-a7cb-c1432781a3e0
		annotation SummarizationSetBy = User

	column drawdown
		dataType: double
		summarizeBy: sum
		sourceColumn: drawdown
		lineageTag: 60161890-2229-4c1e-998b-e23d94640850
		annotation SummarizationSetBy = User

	column repayment
		dataType: double
		summarizeBy: sum
		sourceColumn: repayment
		lineageTag: ceab3a37-ddbf-44a2-a349-92042887133f
		annotation SummarizationSetBy = User

	column closing_balance
		dataType: double
		summarizeBy: sum
		sourceColumn: closing_balance
		lineageTag: d1ca9a89-42e7-4226-9f04-482fe5f375cd
		annotation SummarizationSetBy = User

	column interest_rate
		dataType: double
		summarizeBy: none
		sourceColumn: interest_rate
		lineageTag: aa918939-a26d-4734-a277-9463a6778512
		annotation SummarizationSetBy = User

	column interest_expense
		dataType: double
		summarizeBy: sum
		sourceColumn: interest_expense
		lineageTag: 1c90852c-e3f0-4f0c-a0d5-568cf548c97c
		annotation SummarizationSetBy = User

	column covenant_headroom
		dataType: double
		summarizeBy: sum
		sourceColumn: covenant_headroom
		lineageTag: 9dba3e28-126b-41d2-a7ca-d9d167a177ef
		annotation SummarizationSetBy = User

	partition Debt = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\debt.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"month", type date}, {"facility_id", type text}, {"opening_balance", type number}, {"drawdown", type number}, {"repayment", type number}, {"closing_balance", type number}, {"interest_rate", type number}, {"interest_expense", type number}, {"covenant_headroom", type number}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
