table Promotions
	lineageTag: 9b07f97e-fe4f-432c-b7d0-abf1be0fefd9

	column promo_id
		dataType: string
		isKey
		summarizeBy: none
		sourceColumn: promo_id
		lineageTag: 0b249895-0b8d-4a94-ae9b-087f626fda02
		annotation SummarizationSetBy = User

	column start_date
		dataType: dateTime
		summarizeBy: none
		sourceColumn: start_date
		lineageTag: 887c2859-c197-4f7a-b5b5-8b7fcaf22639
		annotation SummarizationSetBy = User

	column end_date
		dataType: dateTime
		summarizeBy: none
		sourceColumn: end_date
		lineageTag: 0b0485b4-6144-47f1-b379-314305465eec
		annotation SummarizationSetBy = User

	column channel_id
		dataType: string
		summarizeBy: none
		sourceColumn: channel_id
		lineageTag: 00795b37-b6b9-40d4-a38d-f004cac5f2f3
		annotation SummarizationSetBy = User

	column sku_id
		dataType: string
		summarizeBy: none
		sourceColumn: sku_id
		lineageTag: ac9a0d6b-d452-4119-bca6-1ef99bc62a41
		annotation SummarizationSetBy = User

	column mechanic
		dataType: string
		summarizeBy: none
		sourceColumn: mechanic
		lineageTag: f4feabc0-4e79-47e9-b379-6d73a9c8fc6d
		annotation SummarizationSetBy = User

	column planned_discount_pct
		dataType: double
		summarizeBy: none
		sourceColumn: planned_discount_pct
		lineageTag: e806163d-068f-430a-ad69-31752375254f
		annotation SummarizationSetBy = User

	column planned_units_lift_pct
		dataType: double
		summarizeBy: none
		sourceColumn: planned_units_lift_pct
		lineageTag: 8011299f-924d-45fd-80ee-1b5b12f91ad2
		annotation SummarizationSetBy = User

	column actual_discount_pct
		dataType: double
		summarizeBy: none
		sourceColumn: actual_discount_pct
		lineageTag: 19c92ecc-fa37-49b1-9392-fc9aafa298ad
		annotation SummarizationSetBy = User

	column incremental_units
		dataType: int64
		summarizeBy: sum
		sourceColumn: incremental_units
		lineageTag: 9365221b-5458-4cee-9532-9c04add8e72b
		annotation SummarizationSetBy = User

	column baseline_units
		dataType: int64
		summarizeBy: sum
		sourceColumn: baseline_units
		lineageTag: 91f0b464-4b4d-4b69-8ef5-fe52c1c871d3
		annotation SummarizationSetBy = User

	column promo_spend
		dataType: double
		summarizeBy: sum
		sourceColumn: promo_spend
		lineageTag: 0893eb79-d460-4a9a-83df-092e249cde01
		annotation SummarizationSetBy = User

	column roi
		dataType: double
		summarizeBy: none
		sourceColumn: roi
		lineageTag: fe7423f5-906c-45da-a028-c01509b73b71
		annotation SummarizationSetBy = User

	column status
		dataType: string
		summarizeBy: none
		sourceColumn: status
		lineageTag: 0d25da19-de90-44d0-be99-2f76179b91f3
		annotation SummarizationSetBy = User

	partition Promotions = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\promotions.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"promo_id", type text}, {"start_date", type date}, {"end_date", type date}, {"channel_id", type text}, {"sku_id", type text}, {"mechanic", type text}, {"planned_discount_pct", type number}, {"planned_units_lift_pct", type number}, {"actual_discount_pct", type number}, {"incremental_units", Int64.Type}, {"baseline_units", Int64.Type}, {"promo_spend", type number}, {"roi", type number}, {"status", type text}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
