'use client';

import { useMemo, useState } from 'react';
import {
  Activity,
  ArrowDownRight,
  ArrowUpRight,
  BarChart3,
  CheckCircle2,
  CircleDollarSign,
  Clock3,
  Database,
  ExternalLink,
  FileCheck2,
  Gauge,
  GitBranch,
  Layers3,
  ShieldCheck,
  Target,
  TrendingUp,
  Users,
  WalletCards,
  XCircle,
} from 'lucide-react';
import snapshot from '../../data/dashboard_snapshot.json';

type ScenarioName = 'Base' | 'Upside' | 'Downside';
type Scenario = (typeof snapshot.scenarios)[number];

const githubRepo = 'https://github.com/susayold/commercial-finance-profitability-analytics';
const modelLink = 'https://docs.google.com/spreadsheets/d/1-DAMs7zqQr8a6Otimm3WgkAIsX3kazpm/edit';
const evidenceLink = `${githubRepo}/tree/main/data/finance_model/final_v1`;

const monthLabels = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

function format(value: number, digits = 1) {
  return value.toLocaleString('en-US', { minimumFractionDigits: digits, maximumFractionDigits: digits });
}

function KpiCard({ icon: Icon, label, value, unit, detail, tone = 'green' }: { icon: typeof Activity; label: string; value: string; unit?: string; detail: string; tone?: 'green' | 'red' | 'blue' }) {
  return <div className={`dash-kpi dash-kpi-${tone}`}><span className="dash-kpi-icon"><Icon size={21} /></span><div><div className="dash-kpi-label">{label}</div><div className="dash-kpi-value">{value}<small>{unit}</small></div><div className="dash-kpi-detail">{detail}</div></div></div>;
}

function MiniLine({ values, color = '#137441', width = 132, height = 34 }: { values: number[]; color?: string; width?: number; height?: number }) {
  const min = Math.min(...values);
  const max = Math.max(...values);
  const span = max - min || 1;
  const points = values.map((value, index) => `${(index / (values.length - 1)) * width},${height - ((value - min) / span) * (height - 5) - 2}`).join(' ');
  return <svg className="dash-mini-line" viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Trend"><polyline points={points} fill="none" stroke={color} strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" /></svg>;
}

function TrendChart({ data, metric, color = '#11683d', label }: { data: Array<{ label: string; [key: string]: number | string }>; metric: string; color?: string; label: string }) {
  const values = data.map((row) => Number(row[metric]));
  const max = Math.max(...values) * 1.18;
  const points = values.map((value, index) => `${34 + (index / (values.length - 1)) * 692},${224 - (value / max) * 184}`).join(' ');
  return <div className="dash-trend-chart"><div className="dash-chart-legend"><span><i style={{ background: color }} />{label}</span><span>FY2025 monthly</span></div><svg viewBox="0 0 760 270" preserveAspectRatio="none" role="img" aria-label={label}><line x1="34" x2="726" y1="224" y2="224" className="dash-grid-line" /><line x1="34" x2="726" y1="162" y2="162" className="dash-grid-line" /><line x1="34" x2="726" y1="100" y2="100" className="dash-grid-line" /><line x1="34" x2="726" y1="38" y2="38" className="dash-grid-line" />{values.map((value, index) => { const x = 34 + (index / (values.length - 1)) * 692; const y = 224 - (value / max) * 184; return <g key={data[index].label}><rect x={x - 14} y={y} width="28" height={224 - y} rx="4" fill="rgba(17,104,61,.82)" /><circle cx={x} cy={y} r="4" fill="#fff" stroke={color} strokeWidth="2" /></g>; })}<polyline points={points} fill="none" stroke={color} strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" />{data.map((row, index) => <text key={row.label} x={34 + (index / (values.length - 1)) * 692} y="252" textAnchor="middle" className="dash-axis-label">{monthLabels[index]}</text>)}</svg></div>;
}

function CashChart({ rows }: { rows: Array<{ scenario: string; month: string; headroom: number }> }) {
  const base = rows.filter((row) => row.scenario === 'Base');
  const downside = rows.filter((row) => row.scenario === 'Downside');
  const all = [...base.map((row) => row.headroom), ...downside.map((row) => row.headroom)];
  const min = Math.min(...all, 0);
  const max = Math.max(...all) * 1.08;
  const y = (value: number) => 206 - ((value - min) / (max - min)) * 174;
  const x = (index: number) => 32 + (index / (base.length - 1)) * 696;
  const line = (series: typeof base) => series.map((row, index) => `${x(index)},${y(row.headroom)}`).join(' ');
  return <div className="dash-cash-chart"><div className="dash-chart-legend"><span><i className="dash-legend-green" />Base headroom</span><span><i className="dash-legend-red" />Downside headroom</span><span><i className="dash-legend-dash" />Minimum cash policy</span></div><svg viewBox="0 0 760 260" preserveAspectRatio="none" role="img" aria-label="Base and downside liquidity headroom"><line x1="32" x2="728" y1={y(1200)} y2={y(1200)} className="dash-policy-line" />{[0, 1, 2, 3].map((tick) => <line key={tick} x1="32" x2="728" y1={42 + tick * 55} y2={42 + tick * 55} className="dash-grid-line" />)}<polyline points={line(base)} fill="none" stroke="#11683d" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" /><polyline points={line(downside)} fill="none" stroke="#c72e32" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" />{base.map((row, index) => <g key={`b-${row.month}`}><circle cx={x(index)} cy={y(row.headroom)} r="4" fill="#fff" stroke="#11683d" strokeWidth="2" /><circle cx={x(index)} cy={y(downside[index].headroom)} r="4" fill="#fff" stroke="#c72e32" strokeWidth="2" /><text x={x(index)} y="237" textAnchor="middle" className="dash-axis-label">{row.month.slice(5)}</text></g>)}</svg></div>;
}

function ScenarioBadge({ scenario }: { scenario: Scenario }) {
  const isDown = scenario.scenario === 'Downside';
  return <div className={`dash-scenario-card ${isDown ? 'is-downside' : ''}`}><div className="dash-scenario-title"><span className="dash-scenario-icon">{isDown ? <ArrowDownRight size={17} /> : <ArrowUpRight size={17} />}</span>{scenario.scenario}</div><div className="dash-scenario-grid"><span>Revenue</span><strong>{format(scenario.revenue)}</strong><span>EBITDA proxy</span><strong>{format(scenario.ebitdaProxy)}</strong><span>EBITDA margin</span><strong>{format(scenario.ebitdaMargin)}%</strong><span>CCC</span><strong>{format(scenario.ccc, 0)} days</strong></div></div>;
}

export default function Dashboard() {
  const [scenarioName, setScenarioName] = useState<ScenarioName>('Base');
  const scenario = useMemo(() => snapshot.scenarios.find((item) => item.scenario === scenarioName) ?? snapshot.scenarios[0], [scenarioName]);
  const maxChannelSales = Math.max(...snapshot.channels.map((row) => row.netSales));
  const topCustomer = snapshot.customers.find((row) => row.id === 'C06') ?? [...snapshot.customers].sort((a, b) => b.netSales - a.netSales)[0];
  const highestAfterWc = [...snapshot.customers].sort((a, b) => b.afterWcContribution - a.afterWcContribution).slice(0, 5);
  const baseLiquidity = snapshot.liquidity.filter((row) => row.scenario === 'Base');
  const downLiquidity = snapshot.liquidity.filter((row) => row.scenario === 'Downside');
  const yearEndBase = baseLiquidity.at(-1);
  const yearEndDown = downLiquidity.at(-1);

  return <main className="dash-shell" id="dashboard">
    <nav className="dash-nav"><a className="dash-brand" href="../" aria-label="Back to VN Finance home"><span className="dash-brand-mark"><BarChart3 size={18} /></span><span>VN<span className="dash-brand-muted">/</span>FINANCE<small>Commercial Finance & FP&amp;A</small></span></a><span className="dash-entity"><Database size={17} /> VietNova Consumer JSC</span><div className="dash-nav-links"><a href="#executive">Executive</a><a href="#performance">Performance</a><a href="#commercial">Commercial</a><a href="#profitability">Profitability</a><a href="#cash">Cash</a><a href="#forecast">Forecast</a><a href="#evidence">Evidence</a></div><a className="dash-nav-cta" href={modelLink} target="_blank" rel="noreferrer">Open model <ExternalLink size={14} /></a></nav>

    <header className="dash-hero page-width"><div><div className="dash-eyebrow"><span /> FINANCE DECISION COCKPIT / DASHBOARD</div><h1>Executive management<br /><em>review.</em></h1><p>One recruiter-ready dashboard covering P&amp;L, commercial economics, profitability, cash conversion, scenario planning and evidence controls.</p></div><div className="dash-hero-meta"><div><span>Period</span><strong>FY2025</strong></div><div><span>Case</span><strong>{scenarioName}</strong></div><div><span>Status</span><strong>Review ready</strong></div><div><span>Data</span><strong>Simulated / Derived</strong></div></div></header>

    <section className="dash-kpi-strip page-width"><KpiCard icon={BarChart3} label="Net revenue" value={format(scenario.revenue)} unit="bn VND" detail="FY2025 YTD" /><KpiCard icon={CircleDollarSign} label="Gross profit" value={format(scenario.grossProfit)} unit="bn VND" detail={`${format((scenario.grossProfit / scenario.revenue) * 100)}% gross margin`} /><KpiCard icon={TrendingUp} label="EBITDA proxy" value={format(scenario.ebitdaProxy)} unit="bn VND" detail={`${format(scenario.ebitdaMargin)}% proxy margin`} /><KpiCard icon={Target} label="Contribution" value={format(scenario.contribution)} unit="bn VND" detail="After trade and variable cost" /><KpiCard icon={Clock3} label="Cash conversion" value={format(scenario.ccc, 0)} unit="days" detail="DSO + DIO − DPO" tone={scenario.ccc > 60 ? 'red' : 'green'} /><KpiCard icon={Gauge} label="Scenario lens" value={scenarioName} detail="Use the selector below" tone="blue" /></section>

    <section id="executive" className="dash-panel dash-executive page-width"><div className="dash-section-heading"><div><span className="dash-section-kicker">01 / EXECUTIVE</span><h2>What management should<br /><em>act on this month.</em></h2></div><div className="dash-selector" role="group" aria-label="Scenario selector">{(['Base', 'Upside', 'Downside'] as ScenarioName[]).map((item) => <button key={item} className={item === scenarioName ? `active ${item.toLowerCase()}` : ''} onClick={() => setScenarioName(item)}>{item}</button>)}</div></div><div className="dash-executive-grid"><div className="dash-white-card"><h3>Performance at a glance</h3><TrendChart data={snapshot.monthly} metric="revenue" label="Net revenue (bn VND)" /><div className="dash-inline-note"><CheckCircle2 size={16} /> Revenue trend is strongest in Q4; contribution softens in November as trade spend and mix pressure rise.</div></div><div className="dash-white-card"><h3>Management view</h3><div className="dash-management-list"><div><span className="dash-status-dot green"><CheckCircle2 size={14} /></span><strong>Revenue</strong><b>On track</b><small>Q4 run-rate is above the FY2025 monthly average.</small></div><div><span className="dash-status-dot amber"><Activity size={14} /></span><strong>Gross margin</strong><b>Watch</b><small>COGS intensity requires price / mix discipline.</small></div><div><span className="dash-status-dot red"><ArrowDownRight size={14} /></span><strong>Cash conversion</strong><b>Action</b><small>CCC is {format(scenario.ccc, 0)} days in the selected case.</small></div><div><span className="dash-status-dot green"><Target size={14} /></span><strong>Promotion ROI</strong><b>Positive</b><small>Scale E01 and E04; reject negative-return events.</small></div></div></div></div><div className="dash-scenario-row">{snapshot.scenarios.map((item) => <ScenarioBadge key={item.scenario} scenario={item} />)}</div></section>

    <section id="performance" className="dash-panel dash-panel-dark"><div className="page-width"><div className="dash-section-heading dark"><div><span className="dash-section-kicker">02 / PERFORMANCE</span><h2>P&amp;L performance and<br /><em>driver quality.</em></h2></div><p>Monthly values are calculated from the governed 2,160-line sales ledger and OPEX planning facts. The dashboard keeps the proxy label explicit.</p></div><div className="dash-performance-grid"><div className="dash-dark-card"><div className="dash-card-top"><h3>FY2025 monthly performance</h3><span>Revenue bars · EBITDA proxy line</span></div><TrendChart data={snapshot.monthly.map((row) => ({ ...row, revenue: row.revenue }))} metric="revenue" label="Revenue (bn VND)" color="#8ee8ba" /><div className="dash-dark-metrics"><span>Gross profit <strong>{format(scenario.grossProfit)} bn</strong></span><span>COGS <strong>{format(scenario.revenue - scenario.grossProfit)} bn</strong></span><span>Contribution <strong>{format(scenario.contribution)} bn</strong></span></div></div><div className="dash-dark-card"><div className="dash-card-top"><h3>Management P&amp;L structure</h3><span>{scenarioName} case</span></div><div className="dash-pnl-table"><div><span>Net revenue</span><strong>{format(scenario.revenue)}</strong><b>100.0%</b></div><div><span>COGS</span><strong>{format(scenario.revenue - scenario.grossProfit)}</strong><b>{format(((scenario.revenue - scenario.grossProfit) / scenario.revenue) * 100)}%</b></div><div className="highlight"><span>Gross profit</span><strong>{format(scenario.grossProfit)}</strong><b>{format((scenario.grossProfit / scenario.revenue) * 100)}%</b></div><div><span>OPEX</span><strong>{format(scenario.opex)}</strong><b>{format((scenario.opex / scenario.revenue) * 100)}%</b></div><div className="highlight"><span>EBITDA proxy</span><strong>{format(scenario.ebitdaProxy)}</strong><b>{format(scenario.ebitdaMargin)}%</b></div><div><span>Contribution</span><strong>{format(scenario.contribution)}</strong><b>{format((scenario.contribution / scenario.revenue) * 100)}%</b></div></div></div></div><div className="dash-bridge"><span className="dash-bridge-start">Revenue <b>{format(scenario.revenue)}</b></span><span>− COGS <b>{format(scenario.revenue - scenario.grossProfit)}</b></span><span>− OPEX <b>{format(scenario.opex)}</b></span><span className="dash-bridge-end">EBITDA proxy <b>{format(scenario.ebitdaProxy)}</b></span></div></div></section>

    <section id="commercial" className="dash-panel page-width"><div className="dash-section-heading"><div><span className="dash-section-kicker">03 / COMMERCIAL</span><h2>Commercial performance<br /><em>with decision context.</em></h2></div><p>Channel revenue is only the starting point. The decision layer ranks contribution quality, promotion ROI and spend reallocation.</p></div><div className="dash-commercial-grid"><div className="dash-white-card"><h3>Channel economics</h3><div className="dash-channel-list">{snapshot.channels.map((row) => <div key={row.channel}><div className="dash-row-label"><span>{row.channel}</span><strong>{format(row.netSales)}</strong></div><div className="dash-bar-track"><i style={{ width: `${(row.netSales / maxChannelSales) * 100}%` }} /></div><small>{format(row.contributionMargin)}% contribution margin · {format(row.contribution)} bn contribution</small></div>)}</div></div><div className="dash-white-card"><h3>Promotion ROI queue</h3><div className="dash-data-table"><div className="dash-data-head"><span>Event</span><span>ROI</span><span>Decision</span></div>{snapshot.promotions.map((row) => <div key={row.id}><span><b>{row.id}</b>{row.name}</span><strong className={row.roi < 0 ? 'negative' : 'positive'}>{format(row.roi, 2)}x</strong><em className={row.roi < 0 ? 'reject' : 'approve'}>{row.decision}</em></div>)}</div><div className="dash-inline-note"><ShieldCheck size={16} /> Positive ROI is a screening result, not a realized impact claim.</div></div></div><div className="dash-commercial-bottom"><div className="dash-white-card"><h3>Budget reallocation</h3><div className="dash-budget-table"><div className="dash-data-head"><span>Channel</span><span>Δ budget (m)</span><span>Action</span></div>{snapshot.budget.map((row) => <div key={row.channel}><span>{row.channel}</span><strong className={row.delta < 0 ? 'negative' : 'positive'}>{row.delta > 0 ? '+' : ''}{format(row.delta, 0)}</strong><em className={row.delta < 0 ? 'reduce' : 'scale'}>{row.decision}</em></div>)}</div></div><div className="dash-white-card dash-takeaways"><h3>Commercial takeaways</h3><p><Target size={16} /> Shift spend toward higher marginal ROI channels.</p><p><ShieldCheck size={16} /> Protect D2C margin before scaling CAC.</p><p><WalletCards size={16} /> Review marketplace economics and discount leakage.</p></div></div></section>

    <section id="profitability" className="dash-panel dash-panel-tint"><div className="page-width"><div className="dash-section-heading"><div><span className="dash-section-kicker">04 / PROFITABILITY</span><h2>Customer profitability<br /><em>after working capital.</em></h2></div><p>24 customer-year records expose the accounts where revenue, margin and cash absorption tell different stories.</p></div><div className="dash-profit-grid"><div className="dash-white-card"><h3>Customer profitability matrix</h3><div className="dash-scatter" role="img" aria-label="Customer revenue and contribution margin matrix"><span className="dash-scatter-axis-y">Contribution margin %</span><span className="dash-scatter-axis-x">Net sales (bn VND)</span>{snapshot.customers.map((row) => <span key={row.id} className={`dash-point ${row.strategicFlag === 'Y' ? 'flagged' : ''}`} title={`${row.name}: ${format(row.netSales)} bn, ${format(row.contributionMargin)}%`} style={{ left: `${8 + Math.min(row.netSales / 24, 1) * 84}%`, bottom: `${10 + Math.min(row.contributionMargin / 45, 1) * 77}%`, width: `${9 + Math.min(row.afterWcContribution / 8, 1) * 18}px`, height: `${9 + Math.min(row.afterWcContribution / 8, 1) * 18}px` }} />)}<div className="dash-scatter-cross vertical" /><div className="dash-scatter-cross horizontal" /><span className="dash-quadrant top-left">Protect</span><span className="dash-quadrant top-right">Scale</span><span className="dash-quadrant bottom-left">Fix economics</span><span className="dash-quadrant bottom-right">Monitor</span></div></div><div className="dash-white-card"><h3>Flagged customer</h3><div className="dash-flagged"><span className="dash-flagged-icon"><Users size={22} /></span><div><strong>{topCustomer.name}</strong><span>{topCustomer.channel} · Customer review</span></div><em>Review economics</em></div><div className="dash-flagged-metrics"><div><span>Net sales</span><strong>{format(topCustomer.netSales)} bn</strong></div><div><span>CM</span><strong>{format(topCustomer.contributionMargin)}%</strong></div><div><span>DSO</span><strong>{format(topCustomer.dso, 0)} d</strong></div><div><span>After-WC contribution</span><strong>{format(topCustomer.afterWcContribution)} bn</strong></div></div><div className="dash-inline-note warning"><Activity size={16} /> Prioritise collections and service-cost review for high-DSO accounts.</div></div></div><div className="dash-white-card dash-ranking"><h3>Top 5 by after-WC contribution</h3>{highestAfterWc.map((row, index) => <div key={row.id}><span className="dash-rank">{index + 1}</span><strong>{row.name}</strong><small>{row.channel}</small><b>{format(row.afterWcContribution)} bn VND</b></div>)}</div></div></section>

    <section id="cash" className="dash-panel page-width"><div className="dash-section-heading"><div><span className="dash-section-kicker">05 / CASH</span><h2>Cash and working capital<br /><em>before it hurts.</em></h2></div><p>Liquidity headroom, cash conversion and the operating actions needed to protect minimum cash policy.</p></div><div className="dash-cash-grid"><div className="dash-white-card"><h3>Liquidity stress profile</h3><CashChart rows={snapshot.liquidity} /></div><div className="dash-white-card"><h3>Base vs downside liquidity</h3><div className="dash-liquidity-card base"><span><CheckCircle2 size={21} /></span><div><strong>Base case</strong><small>Year-end headroom</small><b>{format(yearEndBase?.headroom ?? 0, 0)} <em>m VND</em></b></div></div><div className="dash-liquidity-card downside"><span><XCircle size={21} /></span><div><strong>Downside case</strong><small>Year-end headroom</small><b>{format(yearEndDown?.headroom ?? 0, 0)} <em>m VND</em></b></div></div></div></div><div className="dash-cash-bottom"><div className="dash-white-card"><h3>CCC management</h3><div className="dash-ccc-equation"><div><span>Base CCC</span><b>{format(scenario.ccc, 0)}</b><small>days</small></div><strong>+</strong><div><span>DSO trigger</span><b>+5</b><small>days</small></div><strong>+</strong><div><span>DIO trigger</span><b>+7</b><small>days</small></div><strong>=</strong><div className="danger"><span>Downside CCC</span><b>{format(snapshot.scenarios.find((item) => item.scenario === 'Downside')?.ccc ?? 68, 0)}</b><small>days</small></div></div><div className="dash-inline-note warning"><Clock3 size={16} /> DSO stretch and slow-moving inventory are the main downside cash drivers.</div></div><div className="dash-white-card"><h3>Working capital actions</h3><div className="dash-action-list"><p><span className="dash-action-index green">↗</span><strong>REC-04</strong> Collect overdue accounts <small>AR lead · weekly</small></p><p><span className="dash-action-index amber">↗</span><strong>REC-05</strong> Reduce slow-SKU inventory <small>Supply chain · weekly</small></p><p><span className="dash-action-index blue">↗</span><strong>FIN-07</strong> Monitor DPO discipline <small>AP manager · weekly</small></p></div></div></div></section>

    <section id="forecast" className="dash-panel dash-panel-dark"><div className="page-width"><div className="dash-section-heading dark"><div><span className="dash-section-kicker">06 / FORECAST</span><h2>Forecast range and<br /><em>decision gates.</em></h2></div><p>Base is the plan. Upside must be earned. Downside requires predefined actions and an explicit external-input boundary.</p></div><div className="dash-forecast-grid"><div className="dash-dark-card"><h3>Scenario landing range</h3>{snapshot.scenarios.map((item) => <div className="dash-landing-row" key={item.scenario}><span>{item.scenario}</span><div><i style={{ width: `${(item.revenue / 90) * 100}%` }} /><b>{format(item.revenue)} bn VND</b></div><small>EBITDA proxy {format(item.ebitdaProxy)} bn · CCC {format(item.ccc, 0)}d</small></div>)}</div><div className="dash-dark-card"><h3>Forecast accuracy rehearsal</h3><div className="dash-accuracy"><div><strong>20/20</strong><span>Core FP&amp;A requirements</span></div><div><strong>55/55</strong><span>Core QA checks</span></div><div><strong>52/52</strong><span>Release gate checks</span></div><div><strong>OPEN</strong><span>Gate A: live accuracy</span></div></div><div className="dash-gate"><ShieldCheck size={18} /><div><strong>Live forecast accuracy claim remains open</strong><span>Current numbers are a controlled rehearsal, pending real pre-close and post-close actuals.</span></div></div></div></div></div></section>

    <section id="evidence" className="dash-panel page-width"><div className="dash-section-heading"><div><span className="dash-section-kicker">07 / EVIDENCE</span><h2>Controls, governance<br /><em>and traceability.</em></h2></div><p>Every visible number links back to a project artifact. Candidate-specific claims remain input-gated.</p></div><div className="dash-evidence-grid"><div className="dash-white-card"><h3>Project architecture</h3><div className="dash-architecture"><div><Database size={21} /><span>Governed<br />data</span></div><b>→</b><div><Layers3 size={21} /><span>Finance<br />model</span></div><b>→</b><div><BarChart3 size={21} /><span>Review<br />outputs</span></div><b>→</b><div><GitBranch size={21} /><span>Recruiter<br />site</span></div></div><div className="dash-source-list"><p><CheckCircle2 size={15} /> 2,160 sales ledger lines</p><p><CheckCircle2 size={15} /> 36 months of controlled facts</p><p><CheckCircle2 size={15} /> Scenario, bridge and cash controls</p></div></div><div className="dash-white-card"><h3>Release scorecard</h3><div className="dash-score-list"><div><span><FileCheck2 size={16} /> Core FP&amp;A build</span><strong>100%</strong></div><div><span><ShieldCheck size={16} /> Core QA</span><strong>55 / 55</strong></div><div><span><CheckCircle2 size={16} /> Release gate</span><strong>52 / 52</strong></div><div><span><Database size={16} /> Manifest files</span><strong>56</strong></div><div><span><Clock3 size={16} /> Gate A</span><strong className="open">OPEN</strong></div></div></div></div><div className="dash-evidence-footer"><div><span>Data boundary</span><strong>SIMULATED / DERIVED</strong><small>Public-safe controlled case data</small></div><a href={evidenceLink} target="_blank" rel="noreferrer">Open source evidence <ExternalLink size={14} /></a><a href={githubRepo} target="_blank" rel="noreferrer">GitHub repository <ExternalLink size={14} /></a></div></section>

    <footer className="dash-footer page-width"><span>VN/FINANCE · Commercial Finance &amp; FP&amp;A</span><span>Dashboard page · FY2025 · Evidence-labelled release</span><a href="../">Back to portfolio <ArrowUpRight size={14} /></a></footer>
  </main>;
}
