table Budget
	lineageTag: 5e2a501e-3c44-486e-8a97-5b1d5e02379f

	column month
		dataType: dateTime
		summarizeBy: none
		sourceColumn: month
		lineageTag: 192b7a58-3c2b-413a-bf72-109c07891012
		annotation SummarizationSetBy = User

	column sku_id
		dataType: string
		summarizeBy: none
		sourceColumn: sku_id
		lineageTag: 9656d1a2-b027-44c3-9989-7dbd8b6b193a
		annotation SummarizationSetBy = User

	column channel_id
		dataType: string
		summarizeBy: none
		sourceColumn: channel_id
		lineageTag: 884fee7e-59ad-4f10-b092-bdfcdabecdec
		annotation SummarizationSetBy = User

	column version
		dataType: string
		summarizeBy: none
		sourceColumn: version
		lineageTag: a7c9f2a1-0b78-429a-9fcb-4cb8f74a7a63
		annotation SummarizationSetBy = User

	column budget_units
		dataType: int64
		summarizeBy: sum
		sourceColumn: budget_units
		lineageTag: 475b5afc-9919-47df-8d26-5b941a49e1fb
		annotation SummarizationSetBy = User

	column budget_net_sales
		dataType: double
		summarizeBy: sum
		sourceColumn: budget_net_sales
		lineageTag: 8a0f42ff-9198-4cb7-b1dd-d6902e95a864
		annotation SummarizationSetBy = User

	column budget_cogs
		dataType: double
		summarizeBy: sum
		sourceColumn: budget_cogs
		lineageTag: 1dff111d-f693-40d7-8232-f9bb98890c29
		annotation SummarizationSetBy = User

	column budget_trade_spend
		dataType: double
		summarizeBy: sum
		sourceColumn: budget_trade_spend
		lineageTag: fd1fd7f3-9ab4-4bab-b54f-0040a84d5672
		annotation SummarizationSetBy = User

	column budget_opex
		dataType: double
		summarizeBy: sum
		sourceColumn: budget_opex
		lineageTag: 1555f69e-0182-4f86-b04b-fe5a51d7dfa6
		annotation SummarizationSetBy = User

	partition Budget = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\budget.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"month", type date}, {"sku_id", type text}, {"channel_id", type text}, {"version", type text}, {"budget_units", Int64.Type}, {"budget_net_sales", type number}, {"budget_cogs", type number}, {"budget_trade_spend", type number}, {"budget_opex", type number}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
