table Budget
	lineageTag: 44b348e3-bd2d-40e0-84c1-58bb7bbc1b9b

	column month
		dataType: dateTime
		summarizeBy: none
		sourceColumn: month
		lineageTag: 33b548f2-6947-424d-b987-9e8a859a87ec
		annotation SummarizationSetBy = User

	column sku_id
		dataType: string
		summarizeBy: none
		sourceColumn: sku_id
		lineageTag: bb26f49e-19a9-46cb-8fc7-c96b1940323f
		annotation SummarizationSetBy = User

	column channel_id
		dataType: string
		summarizeBy: none
		sourceColumn: channel_id
		lineageTag: d3276c60-69ee-4b42-970b-28e17d247379
		annotation SummarizationSetBy = User

	column version
		dataType: string
		summarizeBy: none
		sourceColumn: version
		lineageTag: b2775f4b-addf-44ec-960c-e3aa183e0b7d
		annotation SummarizationSetBy = User

	column budget_units
		dataType: int64
		summarizeBy: sum
		sourceColumn: budget_units
		lineageTag: 99d5f74b-4b78-4571-9dd1-1d59177b6db5
		annotation SummarizationSetBy = User

	column budget_net_sales
		dataType: double
		summarizeBy: sum
		sourceColumn: budget_net_sales
		lineageTag: 9fb1098c-22d2-4022-ae72-4de17e0f19ea
		annotation SummarizationSetBy = User

	column budget_cogs
		dataType: double
		summarizeBy: sum
		sourceColumn: budget_cogs
		lineageTag: e3bcc018-aae2-4a72-ab79-2cf1677e333e
		annotation SummarizationSetBy = User

	column budget_trade_spend
		dataType: double
		summarizeBy: sum
		sourceColumn: budget_trade_spend
		lineageTag: 9036ed50-9bb8-45a5-bf64-ae5978960a7f
		annotation SummarizationSetBy = User

	column budget_opex
		dataType: double
		summarizeBy: sum
		sourceColumn: budget_opex
		lineageTag: 1526ff8e-ee55-479c-822d-9f3a67859a48
		annotation SummarizationSetBy = User

	partition Budget = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\budget.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"month", type date}, {"sku_id", type text}, {"channel_id", type text}, {"version", type text}, {"budget_units", Int64.Type}, {"budget_net_sales", type number}, {"budget_cogs", type number}, {"budget_trade_spend", type number}, {"budget_opex", type number}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
