table Calendar
	lineageTag: c4c4a374-5cc7-43a8-b1ac-0854e8090beb
	dataCategory: Time

	column month
		dataType: dateTime
		isKey
		formatString: Short Date
		summarizeBy: none
		sourceColumn: month
		lineageTag: 0d2dd5b6-93c4-4b74-8aea-4f47f7c9a144
		annotation SummarizationSetBy = User

	column year
		dataType: int64
		summarizeBy: none
		sourceColumn: year
		lineageTag: cf534aa1-3a40-47f4-b029-0cf184d68c3f
		annotation SummarizationSetBy = User

	column quarter
		dataType: string
		summarizeBy: none
		sourceColumn: quarter
		lineageTag: e2a6ad0b-518e-45bd-b417-cc653113b634
		annotation SummarizationSetBy = User

	column month_number
		dataType: int64
		summarizeBy: none
		sourceColumn: month_number
		lineageTag: a04d8ff5-0c02-4527-80bd-1da2d5a69d8d
		annotation SummarizationSetBy = User

	column year_month
		dataType: string
		summarizeBy: none
		sourceColumn: year_month
		lineageTag: d5dcd42b-f9c6-4410-a2cb-604c7e68e7ea
		sortByColumn: month
		annotation SummarizationSetBy = User

	partition Calendar = m
		mode: import
		source =
			let
			    StartDate = #date(2023, 1, 1),
			    MonthCount = 36,
			    MonthList = List.Transform({0..MonthCount-1}, each Date.AddMonths(StartDate, _)),
			    Base = Table.FromList(MonthList, Splitter.SplitByNothing(), {"month"}),
			    Typed = Table.TransformColumnTypes(Base, {{"month", type date}}),
			    AddYear = Table.AddColumn(Typed, "year", each Date.Year([month]), Int64.Type),
			    AddQuarter = Table.AddColumn(AddYear, "quarter", each "Q" & Text.From(Date.QuarterOfYear([month])), type text),
			    AddMonthNumber = Table.AddColumn(AddQuarter, "month_number", each Date.Month([month]), Int64.Type),
			    AddYearMonth = Table.AddColumn(AddMonthNumber, "year_month", each Date.ToText([month], "yyyy-MM"), type text)
			in
			    AddYearMonth

	annotation PBI_ResultType = Table
