table Calendar
	lineageTag: cdf91497-627f-4e0b-af05-11bfc4c98ac0
	dataCategory: Time

	column month
		dataType: dateTime
		isKey
		formatString: Short Date
		summarizeBy: none
		sourceColumn: month
		lineageTag: 7aa85746-783e-4456-8fc3-c25889b28686
		annotation SummarizationSetBy = User

	column year
		dataType: int64
		summarizeBy: none
		sourceColumn: year
		lineageTag: f4982c7f-2957-4822-82c8-b71ba21cbc62
		annotation SummarizationSetBy = User

	column quarter
		dataType: string
		summarizeBy: none
		sourceColumn: quarter
		lineageTag: 0e47e023-e7e1-4d59-9ffb-820a4758a9f8
		annotation SummarizationSetBy = User

	column month_number
		dataType: int64
		summarizeBy: none
		sourceColumn: month_number
		lineageTag: 126b50b7-2135-4f11-97a1-ce66e093180a
		annotation SummarizationSetBy = User

	column year_month
		dataType: string
		summarizeBy: none
		sourceColumn: year_month
		lineageTag: 6ba6c738-6fd7-4c51-a07e-902342ff1a67
		sortByColumn: month
		annotation SummarizationSetBy = User

	partition Calendar = m
		mode: import
		source =
			let
			    StartDate = #date(2023, 1, 1),
			    MonthCount = 36,
			    MonthList = List.Transform({0..MonthCount-1}, each Date.AddMonths(StartDate, _)),
			    Base = Table.FromList(MonthList, Splitter.SplitByNothing(), {"month"}),
			    Typed = Table.TransformColumnTypes(Base, {{"month", type date}}),
			    AddYear = Table.AddColumn(Typed, "year", each Date.Year([month]), Int64.Type),
			    AddQuarter = Table.AddColumn(AddYear, "quarter", each "Q" & Text.From(Date.QuarterOfYear([month])), type text),
			    AddMonthNumber = Table.AddColumn(AddQuarter, "month_number", each Date.Month([month]), Int64.Type),
			    AddYearMonth = Table.AddColumn(AddMonthNumber, "year_month", each Date.ToText([month], "yyyy-MM"), type text)
			in
			    AddYearMonth

	annotation PBI_ResultType = Table
