table CAPEX_Projects
	lineageTag: 1573d595-f964-479b-b219-efbb4af23dc7

	column period
		dataType: string
		summarizeBy: none
		sourceColumn: period
		lineageTag: 32050a61-fd09-4ee4-ae0f-e680683d9e01
		annotation SummarizationSetBy = User

	column project_id
		dataType: string
		summarizeBy: none
		sourceColumn: project_id
		lineageTag: 84a9b916-c492-4455-b19b-3bcf8abaa918
		annotation SummarizationSetBy = User

	column cost_center
		dataType: string
		summarizeBy: none
		sourceColumn: cost_center
		lineageTag: 004eae04-457a-4cd6-95e3-51e5183f3200
		annotation SummarizationSetBy = User

	column capex_type
		dataType: string
		summarizeBy: none
		sourceColumn: capex_type
		lineageTag: 7215bdf4-e246-46ac-91da-027ccc35d39d
		annotation SummarizationSetBy = User

	column approval_status
		dataType: string
		summarizeBy: none
		sourceColumn: approval_status
		lineageTag: 16125474-fc95-4a33-a9e8-36abdec44faa
		annotation SummarizationSetBy = User

	column budget_capex_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: budget_capex_vnd
		lineageTag: eea58317-047c-4493-8f63-3abde948deaf
		annotation SummarizationSetBy = User

	column actual_capex_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: actual_capex_vnd
		lineageTag: 934070ac-eb10-4be4-b75b-aea763823ed1
		annotation SummarizationSetBy = User

	column forecast_capex_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: forecast_capex_vnd
		lineageTag: b08e34cb-aaa6-4925-b151-60f3c7361366
		annotation SummarizationSetBy = User

	column committed_capex_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: committed_capex_vnd
		lineageTag: bbf04f08-7e59-435d-9f45-31e9f81aa497
		annotation SummarizationSetBy = User

	column asset_cost_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: asset_cost_vnd
		lineageTag: 701b0a9d-9540-416b-9a51-b0ad80f5fa8b
		annotation SummarizationSetBy = User

	column in_service_period
		dataType: string
		summarizeBy: none
		sourceColumn: in_service_period
		lineageTag: d8f73f17-8693-4b93-a531-1e33a4efc7c1
		annotation SummarizationSetBy = User

	column useful_life_months
		dataType: int64
		summarizeBy: none
		sourceColumn: useful_life_months
		lineageTag: c024b155-ff02-4888-96f7-f13c29cdfc29
		annotation SummarizationSetBy = User

	column depreciation_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: depreciation_vnd
		lineageTag: c3e8ffc1-a888-45fd-9a2f-da5624c7a710
		annotation SummarizationSetBy = User

	column expected_annual_contribution_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: expected_annual_contribution_vnd
		lineageTag: 26f99517-94ec-40e6-8d74-313c55c61597
		annotation SummarizationSetBy = User

	column payback_months
		dataType: double
		summarizeBy: none
		sourceColumn: payback_months
		lineageTag: 2c0dde1b-740d-49bd-befd-29ad7b819334
		annotation SummarizationSetBy = User

	column cash_payment_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: cash_payment_vnd
		lineageTag: cd33d11c-e146-45fd-ae44-c903b13a7b70
		annotation SummarizationSetBy = User

	column budget_variance_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: budget_variance_vnd
		lineageTag: 7b25e4d8-a66c-4583-90b3-79a96a5cefa1
		annotation SummarizationSetBy = User

	column forecast_variance_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: forecast_variance_vnd
		lineageTag: 21671575-d6fe-4d4c-b124-16050879937c
		annotation SummarizationSetBy = User

	column evidence_class
		dataType: string
		summarizeBy: none
		sourceColumn: evidence_class
		lineageTag: f7d7918d-e452-4298-b315-9135aa62dadd
		annotation SummarizationSetBy = User

	column source_system
		dataType: string
		summarizeBy: none
		sourceColumn: source_system
		lineageTag: 158ff862-ffb8-4a9a-91e5-e5471c54f369
		annotation SummarizationSetBy = User

	partition CAPEX_Projects = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\capex_fixed_asset_planning_synthetic.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"period", type text}, {"project_id", type text}, {"cost_center", type text}, {"capex_type", type text}, {"approval_status", type text}, {"budget_capex_vnd", type number}, {"actual_capex_vnd", type number}, {"forecast_capex_vnd", type number}, {"committed_capex_vnd", type number}, {"asset_cost_vnd", type number}, {"in_service_period", type text}, {"useful_life_months", Int64.Type}, {"depreciation_vnd", type number}, {"expected_annual_contribution_vnd", type number}, {"payback_months", type number}, {"cash_payment_vnd", type number}, {"budget_variance_vnd", type number}, {"forecast_variance_vnd", type number}, {"evidence_class", type text}, {"source_system", type text}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
