table CAPEX_Projects
	lineageTag: d3c162e6-0bd8-4261-ac56-2845ca1d163d

	column period
		dataType: string
		summarizeBy: none
		sourceColumn: period
		lineageTag: 515dd1b5-dcca-4a41-94da-cdb19bf29aaf
		annotation SummarizationSetBy = User

	column project_id
		dataType: string
		summarizeBy: none
		sourceColumn: project_id
		lineageTag: 6a2e2319-3832-4757-992e-4936cb5ce4c6
		annotation SummarizationSetBy = User

	column cost_center
		dataType: string
		summarizeBy: none
		sourceColumn: cost_center
		lineageTag: bb701b17-f8d1-4ce5-8e85-a5f2cf56c309
		annotation SummarizationSetBy = User

	column capex_type
		dataType: string
		summarizeBy: none
		sourceColumn: capex_type
		lineageTag: f35854a6-e58b-4b8d-a7e9-4d481c07c3c2
		annotation SummarizationSetBy = User

	column approval_status
		dataType: string
		summarizeBy: none
		sourceColumn: approval_status
		lineageTag: 2e636bab-8326-48e2-959e-efd7ba11ebdd
		annotation SummarizationSetBy = User

	column budget_capex_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: budget_capex_vnd
		lineageTag: 8d042cb9-7e39-45fd-b125-f6ba8e722e99
		annotation SummarizationSetBy = User

	column actual_capex_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: actual_capex_vnd
		lineageTag: b7f429cc-d4f6-4990-8b34-6fa794c023dc
		annotation SummarizationSetBy = User

	column forecast_capex_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: forecast_capex_vnd
		lineageTag: 7b605e9f-000d-49ea-a6d8-cc9d5f47b85e
		annotation SummarizationSetBy = User

	column committed_capex_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: committed_capex_vnd
		lineageTag: 75385c30-f207-46af-a4fa-7187be48bfdc
		annotation SummarizationSetBy = User

	column asset_cost_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: asset_cost_vnd
		lineageTag: 66fd41ee-1ba8-41ad-ae6e-ff70724e2727
		annotation SummarizationSetBy = User

	column in_service_period
		dataType: string
		summarizeBy: none
		sourceColumn: in_service_period
		lineageTag: dbff3df1-f3b4-4ff4-9d89-30a454c2d33f
		annotation SummarizationSetBy = User

	column useful_life_months
		dataType: int64
		summarizeBy: none
		sourceColumn: useful_life_months
		lineageTag: cf4ae44c-9920-4e9f-b5d1-926e7c64b3e5
		annotation SummarizationSetBy = User

	column depreciation_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: depreciation_vnd
		lineageTag: 24b7dd31-6cfb-4077-a2d6-2d9c3147c5f5
		annotation SummarizationSetBy = User

	column expected_annual_contribution_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: expected_annual_contribution_vnd
		lineageTag: a5cf1896-42a6-4517-8f10-bb546b1ee232
		annotation SummarizationSetBy = User

	column payback_months
		dataType: double
		summarizeBy: none
		sourceColumn: payback_months
		lineageTag: f4b3255f-ba30-4bd8-8952-ce034123b064
		annotation SummarizationSetBy = User

	column cash_payment_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: cash_payment_vnd
		lineageTag: 945a31b3-3a82-41dc-8766-feb145d75b8c
		annotation SummarizationSetBy = User

	column budget_variance_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: budget_variance_vnd
		lineageTag: 33a3fcc6-2bb1-453d-a1fe-e83bf96df0db
		annotation SummarizationSetBy = User

	column forecast_variance_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: forecast_variance_vnd
		lineageTag: 71e76c0d-e70b-4b81-bc23-c903e232b11f
		annotation SummarizationSetBy = User

	column evidence_class
		dataType: string
		summarizeBy: none
		sourceColumn: evidence_class
		lineageTag: 8253f819-bfc3-4021-8040-e1b0dfbb7717
		annotation SummarizationSetBy = User

	column source_system
		dataType: string
		summarizeBy: none
		sourceColumn: source_system
		lineageTag: 94f2c504-04c1-46e0-a9c7-39c6f6fc9de2
		annotation SummarizationSetBy = User

	partition CAPEX_Projects = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\capex_fixed_asset_planning_synthetic.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"period", type text}, {"project_id", type text}, {"cost_center", type text}, {"capex_type", type text}, {"approval_status", type text}, {"budget_capex_vnd", type number}, {"actual_capex_vnd", type number}, {"forecast_capex_vnd", type number}, {"committed_capex_vnd", type number}, {"asset_cost_vnd", type number}, {"in_service_period", type text}, {"useful_life_months", Int64.Type}, {"depreciation_vnd", type number}, {"expected_annual_contribution_vnd", type number}, {"payback_months", type number}, {"cash_payment_vnd", type number}, {"budget_variance_vnd", type number}, {"forecast_variance_vnd", type number}, {"evidence_class", type text}, {"source_system", type text}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
