table Channel
	lineageTag: a1df9dbc-57b9-423d-b5dc-0809f3b515a0

	column channel_id
		dataType: string
		isKey
		summarizeBy: none
		sourceColumn: channel_id
		lineageTag: 2096c0e6-b5a3-4a03-b0ab-17afd879472d
		annotation SummarizationSetBy = User

	column channel_type
		dataType: string
		summarizeBy: none
		sourceColumn: channel_type
		lineageTag: 99d05e1b-310f-4e64-ae69-0df5a56776e0
		annotation SummarizationSetBy = User

	column platform_fee_pct
		dataType: double
		summarizeBy: none
		sourceColumn: platform_fee_pct
		lineageTag: 53f39681-aef8-49d6-907d-15991f358827
		annotation SummarizationSetBy = User

	column commission_pct
		dataType: double
		summarizeBy: none
		sourceColumn: commission_pct
		lineageTag: 7f8f1d6f-ec7f-4625-ba31-d3a988b22961
		annotation SummarizationSetBy = User

	column settlement_days
		dataType: int64
		summarizeBy: none
		sourceColumn: settlement_days
		lineageTag: 1b76980b-7f92-4c9a-a7c7-56fe813a93f5
		annotation SummarizationSetBy = User

	column default_discount_pct
		dataType: double
		summarizeBy: none
		sourceColumn: default_discount_pct
		lineageTag: 9584c1be-0d1f-46bf-8e5b-5612f2b36203
		annotation SummarizationSetBy = User

	partition Channel = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\channel_master.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"channel_id", type text}, {"channel_type", type text}, {"platform_fee_pct", type number}, {"commission_pct", type number}, {"settlement_days", Int64.Type}, {"default_discount_pct", type number}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
