table Channel
	lineageTag: 9f0821ba-3bfd-4268-b036-d8533ebdcbbb

	column channel_id
		dataType: string
		isKey
		summarizeBy: none
		sourceColumn: channel_id
		lineageTag: 5831ccd2-341d-407c-b06f-02244c0a1731
		annotation SummarizationSetBy = User

	column channel_type
		dataType: string
		summarizeBy: none
		sourceColumn: channel_type
		lineageTag: 66462def-5b64-47ea-9cda-0d61c867df43
		annotation SummarizationSetBy = User

	column platform_fee_pct
		dataType: double
		summarizeBy: none
		sourceColumn: platform_fee_pct
		lineageTag: a8dd99e1-8503-44e9-bfd6-be12b968e07f
		annotation SummarizationSetBy = User

	column commission_pct
		dataType: double
		summarizeBy: none
		sourceColumn: commission_pct
		lineageTag: 7b9790a4-3d6c-490e-abb9-865ea94a3d2e
		annotation SummarizationSetBy = User

	column settlement_days
		dataType: int64
		summarizeBy: none
		sourceColumn: settlement_days
		lineageTag: 902c516b-0462-401e-94b8-27d2480e9b1c
		annotation SummarizationSetBy = User

	column default_discount_pct
		dataType: double
		summarizeBy: none
		sourceColumn: default_discount_pct
		lineageTag: 978c0cc3-709c-489e-be3c-7c26d44c4ae9
		annotation SummarizationSetBy = User

	partition Channel = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\channel_master.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"channel_id", type text}, {"channel_type", type text}, {"platform_fee_pct", type number}, {"commission_pct", type number}, {"settlement_days", Int64.Type}, {"default_discount_pct", type number}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
