table Channel
	lineageTag: 2a3570e3-6f0d-4045-9dd6-7fd6511c6b2d

	column channel_id
		dataType: string
		isKey
		summarizeBy: none
		sourceColumn: channel_id
		lineageTag: 55ca96bc-21f6-44e8-afb4-52a35850a4a3
		annotation SummarizationSetBy = User

	column channel_type
		dataType: string
		summarizeBy: none
		sourceColumn: channel_type
		lineageTag: fc5f206c-67bd-4410-85ce-404efa5d0b87
		annotation SummarizationSetBy = User

	column platform_fee_pct
		dataType: double
		summarizeBy: none
		sourceColumn: platform_fee_pct
		lineageTag: f186e0a5-180e-40eb-975d-4c429a715920
		annotation SummarizationSetBy = User

	column commission_pct
		dataType: double
		summarizeBy: none
		sourceColumn: commission_pct
		lineageTag: c2ca2d35-a7fe-456d-ab26-2589b5d7556a
		annotation SummarizationSetBy = User

	column settlement_days
		dataType: int64
		summarizeBy: none
		sourceColumn: settlement_days
		lineageTag: 9af1e4b9-e985-469c-8637-0af09ba55d21
		annotation SummarizationSetBy = User

	column default_discount_pct
		dataType: double
		summarizeBy: none
		sourceColumn: default_discount_pct
		lineageTag: f99babfc-9e05-4985-8273-81ff8443f861
		annotation SummarizationSetBy = User

	partition Channel = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\channel_master.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"channel_id", type text}, {"channel_type", type text}, {"platform_fee_pct", type number}, {"commission_pct", type number}, {"settlement_days", Int64.Type}, {"default_discount_pct", type number}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
