table Commercial_Costs
	lineageTag: 40fb2720-140e-451f-85c8-dee359c74c1b

	column month
		dataType: dateTime
		summarizeBy: none
		sourceColumn: month
		lineageTag: 23266a70-91bd-4a91-b73e-2daad12484f1
		annotation SummarizationSetBy = User

	column sku_id
		dataType: string
		summarizeBy: none
		sourceColumn: sku_id
		lineageTag: 2e2b5119-6f99-4d27-971c-0db5ba8da28c
		annotation SummarizationSetBy = User

	column channel_id
		dataType: string
		summarizeBy: none
		sourceColumn: channel_id
		lineageTag: 606b7010-327c-43ca-82c7-002a42d6d192
		annotation SummarizationSetBy = User

	column trade_spend
		dataType: double
		summarizeBy: sum
		sourceColumn: trade_spend
		lineageTag: f82acbab-dca2-4106-bd88-75f8d74ae622
		annotation SummarizationSetBy = User

	column listing_fee
		dataType: double
		summarizeBy: sum
		sourceColumn: listing_fee
		lineageTag: 3336874e-a4cd-4768-8265-35df5f41d0bc
		annotation SummarizationSetBy = User

	column rebate
		dataType: double
		summarizeBy: sum
		sourceColumn: rebate
		lineageTag: 1dee1ec2-c170-4bcd-bc6e-5a758f4ff880
		annotation SummarizationSetBy = User

	column freight
		dataType: double
		summarizeBy: sum
		sourceColumn: freight
		lineageTag: 65066157-0acf-4848-b557-0f697a3b7f26
		annotation SummarizationSetBy = User

	column payment_fee
		dataType: double
		summarizeBy: sum
		sourceColumn: payment_fee
		lineageTag: c9dbf50f-4046-4f85-ad08-8bbb5c859e41
		annotation SummarizationSetBy = User

	column commission
		dataType: double
		summarizeBy: sum
		sourceColumn: commission
		lineageTag: 33896817-68a3-44e5-895f-c8294c2dab64
		annotation SummarizationSetBy = User

	column writeoff
		dataType: double
		summarizeBy: sum
		sourceColumn: writeoff
		lineageTag: 4aa6fec7-6591-443b-bb45-8434f2b638ca
		annotation SummarizationSetBy = User

	column cost_version
		dataType: string
		summarizeBy: none
		sourceColumn: cost_version
		lineageTag: 1420f08e-fda0-4e5e-8b98-3d51c6732c66
		annotation SummarizationSetBy = User

	partition Commercial_Costs = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\commercial_costs.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"month", type date}, {"sku_id", type text}, {"channel_id", type text}, {"trade_spend", type number}, {"listing_fee", type number}, {"rebate", type number}, {"freight", type number}, {"payment_fee", type number}, {"commission", type number}, {"writeoff", type number}, {"cost_version", type text}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
