table Commercial_Costs
	lineageTag: bfa85344-00e2-487e-8ecd-64ed34b5ddfd

	column month
		dataType: dateTime
		summarizeBy: none
		sourceColumn: month
		lineageTag: aed7bb6f-c8f9-4756-9c51-703716b177b7
		annotation SummarizationSetBy = User

	column sku_id
		dataType: string
		summarizeBy: none
		sourceColumn: sku_id
		lineageTag: 8dcdb89b-570d-41e4-8dc1-09c6a216e9bd
		annotation SummarizationSetBy = User

	column channel_id
		dataType: string
		summarizeBy: none
		sourceColumn: channel_id
		lineageTag: 3483db17-5b0d-469f-b42b-43376e8d0065
		annotation SummarizationSetBy = User

	column trade_spend
		dataType: double
		summarizeBy: sum
		sourceColumn: trade_spend
		lineageTag: 62d898ec-630b-4f43-9ff4-6bd589838b4e
		annotation SummarizationSetBy = User

	column listing_fee
		dataType: double
		summarizeBy: sum
		sourceColumn: listing_fee
		lineageTag: 1c14ad99-d030-4ca8-b867-1a2dfdeb863d
		annotation SummarizationSetBy = User

	column rebate
		dataType: double
		summarizeBy: sum
		sourceColumn: rebate
		lineageTag: 54d3b7f1-1e82-41d0-8244-f686cfcfe899
		annotation SummarizationSetBy = User

	column freight
		dataType: double
		summarizeBy: sum
		sourceColumn: freight
		lineageTag: 9390b3ff-1686-4f78-81e9-3242619bc944
		annotation SummarizationSetBy = User

	column payment_fee
		dataType: double
		summarizeBy: sum
		sourceColumn: payment_fee
		lineageTag: 093a7d8c-b955-4a55-8d8c-8f9101bff85c
		annotation SummarizationSetBy = User

	column commission
		dataType: double
		summarizeBy: sum
		sourceColumn: commission
		lineageTag: 36849878-f397-4b28-87f1-041584b1f146
		annotation SummarizationSetBy = User

	column writeoff
		dataType: double
		summarizeBy: sum
		sourceColumn: writeoff
		lineageTag: 0c65e333-9139-439e-8d2b-c31456362d9d
		annotation SummarizationSetBy = User

	column cost_version
		dataType: string
		summarizeBy: none
		sourceColumn: cost_version
		lineageTag: 01c8aa11-741d-4cb6-9706-67343e895c44
		annotation SummarizationSetBy = User

	partition Commercial_Costs = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\commercial_costs.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"month", type date}, {"sku_id", type text}, {"channel_id", type text}, {"trade_spend", type number}, {"listing_fee", type number}, {"rebate", type number}, {"freight", type number}, {"payment_fee", type number}, {"commission", type number}, {"writeoff", type number}, {"cost_version", type text}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
