table Customer
	lineageTag: 80b12eca-608b-418a-897a-e7866c472120

	column customer_id
		dataType: string
		isKey
		summarizeBy: none
		sourceColumn: customer_id
		lineageTag: 8f8ab493-4245-460b-8801-f1e0c43a07e3
		annotation SummarizationSetBy = User

	column customer_type
		dataType: string
		summarizeBy: none
		sourceColumn: customer_type
		lineageTag: 562e12c1-2c06-4ed7-974c-c9fc3792e296
		annotation SummarizationSetBy = User

	column segment
		dataType: string
		summarizeBy: none
		sourceColumn: segment
		lineageTag: e077caf2-6dc2-44b3-8841-8d5758416b65
		annotation SummarizationSetBy = User

	column region
		dataType: string
		summarizeBy: none
		sourceColumn: region
		lineageTag: ed3031ad-8a50-42a8-87e0-665c78d4cfcf
		annotation SummarizationSetBy = User

	column payment_terms_days
		dataType: int64
		summarizeBy: none
		sourceColumn: payment_terms_days
		lineageTag: 301c823c-192c-4309-9585-7f0014ff5d33
		annotation SummarizationSetBy = User

	column credit_limit
		dataType: double
		summarizeBy: sum
		sourceColumn: credit_limit
		lineageTag: f003c5b6-167e-4dde-b14f-057bacb657e2
		annotation SummarizationSetBy = User

	column acquisition_month
		dataType: dateTime
		summarizeBy: none
		sourceColumn: acquisition_month
		lineageTag: 531a2f5d-a1d2-472e-bfbf-b0e4b76c9fdc
		annotation SummarizationSetBy = User

	partition Customer = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\customer_master.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"customer_id", type text}, {"customer_type", type text}, {"segment", type text}, {"region", type text}, {"payment_terms_days", Int64.Type}, {"credit_limit", type number}, {"acquisition_month", type date}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
