table Customer
	lineageTag: 84d3d868-5b23-44c1-bb1d-ca8f7f13b505

	column customer_id
		dataType: string
		isKey
		summarizeBy: none
		sourceColumn: customer_id
		lineageTag: 514a46c5-39c2-4e95-80eb-98a80696fa5f
		annotation SummarizationSetBy = User

	column customer_type
		dataType: string
		summarizeBy: none
		sourceColumn: customer_type
		lineageTag: a27a11c7-6b05-421b-a1fa-898eb71f9f99
		annotation SummarizationSetBy = User

	column segment
		dataType: string
		summarizeBy: none
		sourceColumn: segment
		lineageTag: 738dc14d-3639-4eb5-964b-2ce8f0d255b0
		annotation SummarizationSetBy = User

	column region
		dataType: string
		summarizeBy: none
		sourceColumn: region
		lineageTag: e727dab2-9f82-4901-b61c-6f0b986bb94e
		annotation SummarizationSetBy = User

	column payment_terms_days
		dataType: int64
		summarizeBy: none
		sourceColumn: payment_terms_days
		lineageTag: 17e75ee0-7235-4e5c-9b13-77a8fa930ba8
		annotation SummarizationSetBy = User

	column credit_limit
		dataType: double
		summarizeBy: sum
		sourceColumn: credit_limit
		lineageTag: 8af32486-c7b8-4475-b3d6-cb8e825df00b
		annotation SummarizationSetBy = User

	column acquisition_month
		dataType: dateTime
		summarizeBy: none
		sourceColumn: acquisition_month
		lineageTag: d2b0a9ab-3d38-4854-9511-92313636339d
		annotation SummarizationSetBy = User

	partition Customer = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\customer_master.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"customer_id", type text}, {"customer_type", type text}, {"segment", type text}, {"region", type text}, {"payment_terms_days", Int64.Type}, {"credit_limit", type number}, {"acquisition_month", type date}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
