table Customer
	lineageTag: f4192e4f-82d2-43b2-8ef7-56d03cc56ee4

	column customer_id
		dataType: string
		isKey
		summarizeBy: none
		sourceColumn: customer_id
		lineageTag: 2462191e-f558-43b3-be71-4ba140698e6f
		annotation SummarizationSetBy = User

	column customer_type
		dataType: string
		summarizeBy: none
		sourceColumn: customer_type
		lineageTag: e7b8cd0b-02ef-4c23-9f50-57fb3428f3bb
		annotation SummarizationSetBy = User

	column segment
		dataType: string
		summarizeBy: none
		sourceColumn: segment
		lineageTag: 6703f4ab-6975-4f10-9091-ba41e134ef5e
		annotation SummarizationSetBy = User

	column region
		dataType: string
		summarizeBy: none
		sourceColumn: region
		lineageTag: 96b5aeee-4a9a-4ce8-b278-f4a79adf0d64
		annotation SummarizationSetBy = User

	column payment_terms_days
		dataType: int64
		summarizeBy: none
		sourceColumn: payment_terms_days
		lineageTag: bbfca0a6-4a7c-45b1-a9fd-ab0ba6711833
		annotation SummarizationSetBy = User

	column credit_limit
		dataType: double
		summarizeBy: sum
		sourceColumn: credit_limit
		lineageTag: 3d6f204a-4606-485d-a2d9-90f68389661e
		annotation SummarizationSetBy = User

	column acquisition_month
		dataType: dateTime
		summarizeBy: none
		sourceColumn: acquisition_month
		lineageTag: 987feec2-b64d-4267-b385-3e1a07c6d276
		annotation SummarizationSetBy = User

	partition Customer = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\customer_master.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"customer_id", type text}, {"customer_type", type text}, {"segment", type text}, {"region", type text}, {"payment_terms_days", Int64.Type}, {"credit_limit", type number}, {"acquisition_month", type date}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
