table Debt
	lineageTag: a70639c5-0496-442d-a4e7-e42f886cf9f9

	column month
		dataType: dateTime
		summarizeBy: none
		sourceColumn: month
		lineageTag: 0a3297c8-225a-4ee1-89bd-ccfd7f38d543
		annotation SummarizationSetBy = User

	column facility_id
		dataType: string
		summarizeBy: none
		sourceColumn: facility_id
		lineageTag: d29cf9b7-d577-45a3-b70d-475d98c512b5
		annotation SummarizationSetBy = User

	column opening_balance
		dataType: double
		summarizeBy: sum
		sourceColumn: opening_balance
		lineageTag: b0249ac1-3949-44e5-9c22-8527f3df3714
		annotation SummarizationSetBy = User

	column drawdown
		dataType: double
		summarizeBy: sum
		sourceColumn: drawdown
		lineageTag: 70ac6459-8f55-4158-bd14-0efb6d1e9ced
		annotation SummarizationSetBy = User

	column repayment
		dataType: double
		summarizeBy: sum
		sourceColumn: repayment
		lineageTag: 18548aa7-c26c-4fc4-bf56-4996b48cc35d
		annotation SummarizationSetBy = User

	column closing_balance
		dataType: double
		summarizeBy: sum
		sourceColumn: closing_balance
		lineageTag: f81cd9b1-2670-4307-90b2-4f2e22d963ea
		annotation SummarizationSetBy = User

	column interest_rate
		dataType: double
		summarizeBy: none
		sourceColumn: interest_rate
		lineageTag: 9d6899b4-0723-4735-9c88-6c19a06e12c6
		annotation SummarizationSetBy = User

	column interest_expense
		dataType: double
		summarizeBy: sum
		sourceColumn: interest_expense
		lineageTag: 183f4bb4-53c6-45f3-9ffc-b8e7d557dcff
		annotation SummarizationSetBy = User

	column covenant_headroom
		dataType: double
		summarizeBy: sum
		sourceColumn: covenant_headroom
		lineageTag: aad15ac7-4a73-4b1e-a9c4-ea7ffcd49af8
		annotation SummarizationSetBy = User

	partition Debt = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\debt.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"month", type date}, {"facility_id", type text}, {"opening_balance", type number}, {"drawdown", type number}, {"repayment", type number}, {"closing_balance", type number}, {"interest_rate", type number}, {"interest_expense", type number}, {"covenant_headroom", type number}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
