table Debt
	lineageTag: 2cf3d964-dae1-4942-9701-b17f6821c0ba

	column month
		dataType: dateTime
		summarizeBy: none
		sourceColumn: month
		lineageTag: e43056c6-ec46-4f2a-b4af-9e5801b2ecda
		annotation SummarizationSetBy = User

	column facility_id
		dataType: string
		summarizeBy: none
		sourceColumn: facility_id
		lineageTag: f3a29810-22f2-4f6c-b172-f5ce7fd12759
		annotation SummarizationSetBy = User

	column opening_balance
		dataType: double
		summarizeBy: sum
		sourceColumn: opening_balance
		lineageTag: 752cb661-c491-427d-9d42-90e699200209
		annotation SummarizationSetBy = User

	column drawdown
		dataType: double
		summarizeBy: sum
		sourceColumn: drawdown
		lineageTag: 9adc511c-f883-48ce-8350-da5cffbc9a39
		annotation SummarizationSetBy = User

	column repayment
		dataType: double
		summarizeBy: sum
		sourceColumn: repayment
		lineageTag: 89459ea7-afe5-4790-b734-520d7b06022c
		annotation SummarizationSetBy = User

	column closing_balance
		dataType: double
		summarizeBy: sum
		sourceColumn: closing_balance
		lineageTag: a1a8cec5-1b5d-435d-b80a-b8d85c51b4d9
		annotation SummarizationSetBy = User

	column interest_rate
		dataType: double
		summarizeBy: none
		sourceColumn: interest_rate
		lineageTag: 40841c49-349d-4605-aedb-24fe92613e7e
		annotation SummarizationSetBy = User

	column interest_expense
		dataType: double
		summarizeBy: sum
		sourceColumn: interest_expense
		lineageTag: ecd31ae0-f745-4857-b14f-67c6914995e2
		annotation SummarizationSetBy = User

	column covenant_headroom
		dataType: double
		summarizeBy: sum
		sourceColumn: covenant_headroom
		lineageTag: 90e055ba-2bbe-451c-9114-058daef4c052
		annotation SummarizationSetBy = User

	partition Debt = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\debt.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"month", type date}, {"facility_id", type text}, {"opening_balance", type number}, {"drawdown", type number}, {"repayment", type number}, {"closing_balance", type number}, {"interest_rate", type number}, {"interest_expense", type number}, {"covenant_headroom", type number}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
