table Forecast
	lineageTag: 1245d2d3-00c0-405e-920f-5b52e4e26e13

	column snapshot_month
		dataType: dateTime
		summarizeBy: none
		sourceColumn: snapshot_month
		lineageTag: 3f41ef1c-63c7-432a-bb55-d79edbcaa27e
		annotation SummarizationSetBy = User

	column target_month
		dataType: dateTime
		summarizeBy: none
		sourceColumn: target_month
		lineageTag: 64c5fcec-bb98-4645-bb7b-244ca232fbe9
		annotation SummarizationSetBy = User

	column sku_id
		dataType: string
		summarizeBy: none
		sourceColumn: sku_id
		lineageTag: be2632c6-8758-4f3b-bb71-b8d0f95c98dc
		annotation SummarizationSetBy = User

	column channel_id
		dataType: string
		summarizeBy: none
		sourceColumn: channel_id
		lineageTag: 489b9ae8-a302-472e-b4ec-497cd752dea8
		annotation SummarizationSetBy = User

	column forecast_units
		dataType: int64
		summarizeBy: sum
		sourceColumn: forecast_units
		lineageTag: 57f3606c-d15c-41f6-aebd-faad83edc2a8
		annotation SummarizationSetBy = User

	column forecast_net_sales
		dataType: double
		summarizeBy: sum
		sourceColumn: forecast_net_sales
		lineageTag: e9f8ecd4-7c71-474e-b8f4-15a08541373c
		annotation SummarizationSetBy = User

	column forecast_cogs
		dataType: double
		summarizeBy: sum
		sourceColumn: forecast_cogs
		lineageTag: d7b451d8-2869-4519-afb2-a07fbc9f42bd
		annotation SummarizationSetBy = User

	column forecast_trade_spend
		dataType: double
		summarizeBy: sum
		sourceColumn: forecast_trade_spend
		lineageTag: 3aca1bc5-453e-4bc6-9202-a8e708d791c5
		annotation SummarizationSetBy = User

	column forecast_opex
		dataType: double
		summarizeBy: sum
		sourceColumn: forecast_opex
		lineageTag: 2bb5c6c4-9d84-41e3-9b1b-467e07676b53
		annotation SummarizationSetBy = User

	column forecast_version
		dataType: string
		summarizeBy: none
		sourceColumn: forecast_version
		lineageTag: 579b8993-b983-4452-8e0a-efb4d180c6c4
		annotation SummarizationSetBy = User

	partition Forecast = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\forecast.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"snapshot_month", type date}, {"target_month", type date}, {"sku_id", type text}, {"channel_id", type text}, {"forecast_units", Int64.Type}, {"forecast_net_sales", type number}, {"forecast_cogs", type number}, {"forecast_trade_spend", type number}, {"forecast_opex", type number}, {"forecast_version", type text}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
