table Forecast
	lineageTag: 181def38-61e7-437b-babb-5a39202d776a

	column snapshot_month
		dataType: dateTime
		summarizeBy: none
		sourceColumn: snapshot_month
		lineageTag: b40175d1-5ffc-42c0-aff6-d9a809ade53b
		annotation SummarizationSetBy = User

	column target_month
		dataType: dateTime
		summarizeBy: none
		sourceColumn: target_month
		lineageTag: a6da6a03-71e0-44b8-a4e3-efd1b2f72f14
		annotation SummarizationSetBy = User

	column sku_id
		dataType: string
		summarizeBy: none
		sourceColumn: sku_id
		lineageTag: 2d880ccf-b3bf-4a87-bae0-09cf021baa40
		annotation SummarizationSetBy = User

	column channel_id
		dataType: string
		summarizeBy: none
		sourceColumn: channel_id
		lineageTag: a1371d33-7993-4afa-881d-eeeb6204517f
		annotation SummarizationSetBy = User

	column forecast_units
		dataType: int64
		summarizeBy: sum
		sourceColumn: forecast_units
		lineageTag: 28fe83ad-13b3-4dc3-b6d6-7a08db4be24d
		annotation SummarizationSetBy = User

	column forecast_net_sales
		dataType: double
		summarizeBy: sum
		sourceColumn: forecast_net_sales
		lineageTag: 8ae9bce8-d8f3-4189-84f2-e30565a7f7f5
		annotation SummarizationSetBy = User

	column forecast_cogs
		dataType: double
		summarizeBy: sum
		sourceColumn: forecast_cogs
		lineageTag: 3a5dfc4f-69eb-41d6-a7b0-fc18109484b8
		annotation SummarizationSetBy = User

	column forecast_trade_spend
		dataType: double
		summarizeBy: sum
		sourceColumn: forecast_trade_spend
		lineageTag: 390c9157-d78f-437b-90d1-4f81f2f4b85c
		annotation SummarizationSetBy = User

	column forecast_opex
		dataType: double
		summarizeBy: sum
		sourceColumn: forecast_opex
		lineageTag: 7a4a1136-1106-4c1e-8da7-14664b4aac85
		annotation SummarizationSetBy = User

	column forecast_version
		dataType: string
		summarizeBy: none
		sourceColumn: forecast_version
		lineageTag: f462f42d-191d-4917-b5b7-1fe77c6b7f76
		annotation SummarizationSetBy = User

	partition Forecast = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\forecast.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"snapshot_month", type date}, {"target_month", type date}, {"sku_id", type text}, {"channel_id", type text}, {"forecast_units", Int64.Type}, {"forecast_net_sales", type number}, {"forecast_cogs", type number}, {"forecast_trade_spend", type number}, {"forecast_opex", type number}, {"forecast_version", type text}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
