table Inventory
	lineageTag: 3811f0eb-be82-456b-a63a-3d1ee1e8c387

	column month
		dataType: dateTime
		summarizeBy: none
		sourceColumn: month
		lineageTag: feee16fc-27da-4cc8-87f3-84ccc5e032c8
		annotation SummarizationSetBy = User

	column warehouse_id
		dataType: string
		summarizeBy: none
		sourceColumn: warehouse_id
		lineageTag: 453eea9d-07bf-4f59-8e69-62290a94ecb9
		annotation SummarizationSetBy = User

	column sku_id
		dataType: string
		summarizeBy: none
		sourceColumn: sku_id
		lineageTag: 154eb722-4b2e-492a-be0e-ef749b441ba2
		annotation SummarizationSetBy = User

	column opening_units
		dataType: int64
		summarizeBy: sum
		sourceColumn: opening_units
		lineageTag: a4a64137-28e0-467e-9279-03761c88e385
		annotation SummarizationSetBy = User

	column receipts_units
		dataType: int64
		summarizeBy: sum
		sourceColumn: receipts_units
		lineageTag: cd0c52ee-3031-4c44-9ad5-107019d48957
		annotation SummarizationSetBy = User

	column sales_units
		dataType: int64
		summarizeBy: sum
		sourceColumn: sales_units
		lineageTag: c8503ce9-96d7-418d-bcc4-985e24f8f7f2
		annotation SummarizationSetBy = User

	column closing_units
		dataType: int64
		summarizeBy: sum
		sourceColumn: closing_units
		lineageTag: 69decd19-c022-47ff-b4d2-16ad78c0e6ff
		annotation SummarizationSetBy = User

	column unit_cost
		dataType: double
		summarizeBy: sum
		sourceColumn: unit_cost
		lineageTag: 51097105-688f-46f3-be09-67dd38e60a9c
		annotation SummarizationSetBy = User

	column inventory_value
		dataType: double
		summarizeBy: sum
		sourceColumn: inventory_value
		lineageTag: b0074cb9-64b0-4931-a7fd-68a1a314d598
		annotation SummarizationSetBy = User

	column days_on_hand
		dataType: double
		summarizeBy: none
		sourceColumn: days_on_hand
		lineageTag: 78fe8ce3-1d50-42fc-8e23-4d5e474786f7
		annotation SummarizationSetBy = User

	column stockout_flag
		dataType: boolean
		summarizeBy: none
		sourceColumn: stockout_flag
		lineageTag: df50d78f-e2c6-4638-a9bc-2275c7d97690
		annotation SummarizationSetBy = User

	column expiry_writeoff
		dataType: double
		summarizeBy: sum
		sourceColumn: expiry_writeoff
		lineageTag: fb1b49cf-e89d-4a9f-86f0-eb89f66bbd53
		annotation SummarizationSetBy = User

	partition Inventory = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\inventory.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"month", type date}, {"warehouse_id", type text}, {"sku_id", type text}, {"opening_units", Int64.Type}, {"receipts_units", Int64.Type}, {"sales_units", Int64.Type}, {"closing_units", Int64.Type}, {"unit_cost", type number}, {"inventory_value", type number}, {"days_on_hand", type number}, {"stockout_flag", type logical}, {"expiry_writeoff", type number}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
