table Inventory
	lineageTag: 2253507e-27a0-4650-a943-643079a5f070

	column month
		dataType: dateTime
		summarizeBy: none
		sourceColumn: month
		lineageTag: 6b70bc24-7dff-4059-ad5e-8be04b8e1b5d
		annotation SummarizationSetBy = User

	column warehouse_id
		dataType: string
		summarizeBy: none
		sourceColumn: warehouse_id
		lineageTag: f3818f43-66ff-4049-94a2-a812efd7cc84
		annotation SummarizationSetBy = User

	column sku_id
		dataType: string
		summarizeBy: none
		sourceColumn: sku_id
		lineageTag: 66010d22-dc71-47e6-b03a-1bed1272a9df
		annotation SummarizationSetBy = User

	column opening_units
		dataType: int64
		summarizeBy: sum
		sourceColumn: opening_units
		lineageTag: 495e8d82-9752-4c48-98ca-52ef66828de3
		annotation SummarizationSetBy = User

	column receipts_units
		dataType: int64
		summarizeBy: sum
		sourceColumn: receipts_units
		lineageTag: 16b3d20f-ebed-4d9c-a800-abd0465b5e79
		annotation SummarizationSetBy = User

	column sales_units
		dataType: int64
		summarizeBy: sum
		sourceColumn: sales_units
		lineageTag: 2076983b-2f58-4549-9f63-a7ac76df617b
		annotation SummarizationSetBy = User

	column closing_units
		dataType: int64
		summarizeBy: sum
		sourceColumn: closing_units
		lineageTag: 64882f33-acd8-420d-b666-84312c6a520f
		annotation SummarizationSetBy = User

	column unit_cost
		dataType: double
		summarizeBy: sum
		sourceColumn: unit_cost
		lineageTag: d2adb5dc-dfce-4808-a5db-eae47f3b6655
		annotation SummarizationSetBy = User

	column inventory_value
		dataType: double
		summarizeBy: sum
		sourceColumn: inventory_value
		lineageTag: d491360d-4635-4555-90f0-93196e270810
		annotation SummarizationSetBy = User

	column days_on_hand
		dataType: double
		summarizeBy: none
		sourceColumn: days_on_hand
		lineageTag: ee75dc27-d16d-40ee-9192-41af9cad8b2e
		annotation SummarizationSetBy = User

	column stockout_flag
		dataType: boolean
		summarizeBy: none
		sourceColumn: stockout_flag
		lineageTag: 704e3683-59a0-4fd8-8995-21bd04149921
		annotation SummarizationSetBy = User

	column expiry_writeoff
		dataType: double
		summarizeBy: sum
		sourceColumn: expiry_writeoff
		lineageTag: 76bce0f5-ffa0-498a-8182-1c5ec9ed3912
		annotation SummarizationSetBy = User

	partition Inventory = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\inventory.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"month", type date}, {"warehouse_id", type text}, {"sku_id", type text}, {"opening_units", Int64.Type}, {"receipts_units", Int64.Type}, {"sales_units", Int64.Type}, {"closing_units", Int64.Type}, {"unit_cost", type number}, {"inventory_value", type number}, {"days_on_hand", type number}, {"stockout_flag", type logical}, {"expiry_writeoff", type number}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
