table Marketing
	lineageTag: 9f9b554b-d576-4758-af76-45dd4a2916e7

	column month
		dataType: dateTime
		summarizeBy: none
		sourceColumn: month
		lineageTag: c17618fe-e363-472a-bfef-a60f7285859c
		annotation SummarizationSetBy = User

	column channel_id
		dataType: string
		summarizeBy: none
		sourceColumn: channel_id
		lineageTag: 83ea899e-4bca-453b-bfbd-c3e0dd1105b4
		annotation SummarizationSetBy = User

	column campaign_id
		dataType: string
		summarizeBy: none
		sourceColumn: campaign_id
		lineageTag: 307400ff-8214-407c-ad68-b989e1ea7f71
		annotation SummarizationSetBy = User

	column spend
		dataType: double
		summarizeBy: sum
		sourceColumn: spend
		lineageTag: 6f3cbeb9-90a4-49a7-a573-e4a2a7b50dbe
		annotation SummarizationSetBy = User

	column impressions
		dataType: int64
		summarizeBy: sum
		sourceColumn: impressions
		lineageTag: de02ebba-e93c-46ec-9437-a0be83b360c3
		annotation SummarizationSetBy = User

	column clicks
		dataType: int64
		summarizeBy: sum
		sourceColumn: clicks
		lineageTag: 45e7b0dc-b564-43be-abf3-baf1adf0ef38
		annotation SummarizationSetBy = User

	column orders
		dataType: int64
		summarizeBy: sum
		sourceColumn: orders
		lineageTag: d49e5964-36a3-44b7-a45b-96ff8ba26bfb
		annotation SummarizationSetBy = User

	column attributed_net_sales
		dataType: double
		summarizeBy: sum
		sourceColumn: attributed_net_sales
		lineageTag: c3042025-5ce6-4181-89c4-2935af12c0d2
		annotation SummarizationSetBy = User

	column cac
		dataType: double
		summarizeBy: none
		sourceColumn: cac
		lineageTag: e2021327-2582-47c9-8d46-4d896949a981
		annotation SummarizationSetBy = User

	column roas
		dataType: double
		summarizeBy: none
		sourceColumn: roas
		lineageTag: 4f74b038-91aa-424a-ad43-658e7a006508
		annotation SummarizationSetBy = User

	partition Marketing = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\marketing_spend.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"month", type date}, {"channel_id", type text}, {"campaign_id", type text}, {"spend", type number}, {"impressions", Int64.Type}, {"clicks", Int64.Type}, {"orders", Int64.Type}, {"attributed_net_sales", type number}, {"cac", type number}, {"roas", type number}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
