table Marketing
	lineageTag: 332e8d05-9aae-4170-8feb-3d1c64ae20f5

	column month
		dataType: dateTime
		summarizeBy: none
		sourceColumn: month
		lineageTag: 93004c99-c14d-4163-888b-eb6e10b408fe
		annotation SummarizationSetBy = User

	column channel_id
		dataType: string
		summarizeBy: none
		sourceColumn: channel_id
		lineageTag: 5af62354-a5eb-4000-b1f1-03ed03dd9101
		annotation SummarizationSetBy = User

	column campaign_id
		dataType: string
		summarizeBy: none
		sourceColumn: campaign_id
		lineageTag: 5a89a439-94d9-4bfa-b38c-7a58fc8d4bc3
		annotation SummarizationSetBy = User

	column spend
		dataType: double
		summarizeBy: sum
		sourceColumn: spend
		lineageTag: 5e08b3eb-3b1b-4989-b846-16ba1339017d
		annotation SummarizationSetBy = User

	column impressions
		dataType: int64
		summarizeBy: sum
		sourceColumn: impressions
		lineageTag: 6b16cc0e-a2e1-48d5-a0e1-d4f562d9031b
		annotation SummarizationSetBy = User

	column clicks
		dataType: int64
		summarizeBy: sum
		sourceColumn: clicks
		lineageTag: 4d2bc3ea-a149-4aaf-b34c-a5144bf230ef
		annotation SummarizationSetBy = User

	column orders
		dataType: int64
		summarizeBy: sum
		sourceColumn: orders
		lineageTag: b9ea7689-7acc-4196-8f3c-e2bc6d71f06f
		annotation SummarizationSetBy = User

	column attributed_net_sales
		dataType: double
		summarizeBy: sum
		sourceColumn: attributed_net_sales
		lineageTag: 2e860bda-a983-4ca1-88a3-0b103a35886d
		annotation SummarizationSetBy = User

	column cac
		dataType: double
		summarizeBy: none
		sourceColumn: cac
		lineageTag: f5382d69-1697-4070-8798-67af5bd0dc5d
		annotation SummarizationSetBy = User

	column roas
		dataType: double
		summarizeBy: none
		sourceColumn: roas
		lineageTag: 83154bff-ae94-47e4-854e-0afca77e4bf4
		annotation SummarizationSetBy = User

	partition Marketing = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\marketing_spend.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"month", type date}, {"channel_id", type text}, {"campaign_id", type text}, {"spend", type number}, {"impressions", Int64.Type}, {"clicks", Int64.Type}, {"orders", Int64.Type}, {"attributed_net_sales", type number}, {"cac", type number}, {"roas", type number}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
