table OPEX_Headcount
	lineageTag: 1f531701-2019-430d-a71e-d78d12ead2c2

	column period
		dataType: string
		summarizeBy: none
		sourceColumn: period
		lineageTag: 1e335572-8f76-4f01-8af7-53da805de982
		annotation SummarizationSetBy = User

	column cost_center
		dataType: string
		summarizeBy: none
		sourceColumn: cost_center
		lineageTag: 6a7dee06-1b83-472b-8bda-16c2c4f59b87
		annotation SummarizationSetBy = User

	column function
		dataType: string
		summarizeBy: none
		sourceColumn: function
		lineageTag: 1b708da4-d6b2-4c68-9d9b-6ee280970694
		annotation SummarizationSetBy = User

	column headcount_open
		dataType: int64
		summarizeBy: sum
		sourceColumn: headcount_open
		lineageTag: eb283d00-ec49-4cec-b04c-4947daf758ad
		annotation SummarizationSetBy = User

	column hires
		dataType: int64
		summarizeBy: sum
		sourceColumn: hires
		lineageTag: dc39c91b-c17f-4d59-b80a-55f3dae30b5f
		annotation SummarizationSetBy = User

	column exits
		dataType: int64
		summarizeBy: sum
		sourceColumn: exits
		lineageTag: 9769f1a3-8a8d-469d-bdb6-1cfb9e523df0
		annotation SummarizationSetBy = User

	column headcount_close
		dataType: int64
		summarizeBy: sum
		sourceColumn: headcount_close
		lineageTag: 15a61945-96fc-4432-9d8d-7374e4c70ccd
		annotation SummarizationSetBy = User

	column avg_headcount
		dataType: double
		summarizeBy: sum
		sourceColumn: avg_headcount
		lineageTag: af7cf443-83f8-42b7-b94a-85b7d108ff85
		annotation SummarizationSetBy = User

	column avg_salary_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: avg_salary_vnd
		lineageTag: 95deac06-8d92-4c39-a432-475178dc3309
		annotation SummarizationSetBy = User

	column payroll_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: payroll_vnd
		lineageTag: 4d829dc2-b43a-4f1c-8acc-b7544b267ca2
		annotation SummarizationSetBy = User

	column benefits_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: benefits_vnd
		lineageTag: 5b41ef02-3e2f-4665-99e1-4f52ccf9cbdd
		annotation SummarizationSetBy = User

	column bonus_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: bonus_vnd
		lineageTag: 9c2c0087-a1cb-441d-ba33-c2ab1dd697c3
		annotation SummarizationSetBy = User

	column non_payroll_opex_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: non_payroll_opex_vnd
		lineageTag: 82ac2b1d-929e-4bbd-877c-116391a1030f
		annotation SummarizationSetBy = User

	column opex_actual_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: opex_actual_vnd
		lineageTag: 48527d73-3a87-4055-8c64-b9f8bfb24e20
		annotation SummarizationSetBy = User

	column opex_budget_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: opex_budget_vnd
		lineageTag: 3907747a-f576-4366-adf9-35f2908181ef
		annotation SummarizationSetBy = User

	column opex_forecast_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: opex_forecast_vnd
		lineageTag: 876c2e42-4f57-4df3-81c7-7edc550fcd9f
		annotation SummarizationSetBy = User

	column budget_variance_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: budget_variance_vnd
		lineageTag: b9a3435e-041f-49ad-a2fa-0463a652a51e
		annotation SummarizationSetBy = User

	column forecast_variance_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: forecast_variance_vnd
		lineageTag: 5d3bdd2c-ef48-46ad-98a5-1409e79fd684
		annotation SummarizationSetBy = User

	column evidence_class
		dataType: string
		summarizeBy: none
		sourceColumn: evidence_class
		lineageTag: 40d952db-afb9-417b-9f29-9a2f8e392a9c
		annotation SummarizationSetBy = User

	column source_system
		dataType: string
		summarizeBy: none
		sourceColumn: source_system
		lineageTag: 203fab36-88a7-4b2d-b4c2-b15c05df4706
		annotation SummarizationSetBy = User

	partition OPEX_Headcount = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\opex_headcount_planning_synthetic.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"period", type text}, {"cost_center", type text}, {"function", type text}, {"headcount_open", Int64.Type}, {"hires", Int64.Type}, {"exits", Int64.Type}, {"headcount_close", Int64.Type}, {"avg_headcount", type number}, {"avg_salary_vnd", type number}, {"payroll_vnd", type number}, {"benefits_vnd", type number}, {"bonus_vnd", type number}, {"non_payroll_opex_vnd", type number}, {"opex_actual_vnd", type number}, {"opex_budget_vnd", type number}, {"opex_forecast_vnd", type number}, {"budget_variance_vnd", type number}, {"forecast_variance_vnd", type number}, {"evidence_class", type text}, {"source_system", type text}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
