table OPEX_Headcount
	lineageTag: 51b4523d-52a3-4274-a81b-1bc94edbf518

	column period
		dataType: string
		summarizeBy: none
		sourceColumn: period
		lineageTag: 78f23754-97ce-435e-9e55-049d03f0ff0c
		annotation SummarizationSetBy = User

	column cost_center
		dataType: string
		summarizeBy: none
		sourceColumn: cost_center
		lineageTag: 33c488c2-ffc5-42ed-88f6-ffd2cc2d817c
		annotation SummarizationSetBy = User

	column function
		dataType: string
		summarizeBy: none
		sourceColumn: function
		lineageTag: d14bb68e-5416-4d01-a944-2630224564d6
		annotation SummarizationSetBy = User

	column headcount_open
		dataType: int64
		summarizeBy: sum
		sourceColumn: headcount_open
		lineageTag: f9ffbf4f-f4fd-4623-9440-1bbd576dce97
		annotation SummarizationSetBy = User

	column hires
		dataType: int64
		summarizeBy: sum
		sourceColumn: hires
		lineageTag: 95d5ef45-1d95-4962-8f53-cd4388317d23
		annotation SummarizationSetBy = User

	column exits
		dataType: int64
		summarizeBy: sum
		sourceColumn: exits
		lineageTag: e6fb582f-76e6-480d-b7b9-c5508c1640b0
		annotation SummarizationSetBy = User

	column headcount_close
		dataType: int64
		summarizeBy: sum
		sourceColumn: headcount_close
		lineageTag: c1757406-652c-4590-a72f-8a2fbed49641
		annotation SummarizationSetBy = User

	column avg_headcount
		dataType: double
		summarizeBy: sum
		sourceColumn: avg_headcount
		lineageTag: f6f58b5c-7c54-467e-8a72-d9f111098b0c
		annotation SummarizationSetBy = User

	column avg_salary_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: avg_salary_vnd
		lineageTag: 2ca2d38e-0fd6-4ba1-aab7-d2255ab190d3
		annotation SummarizationSetBy = User

	column payroll_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: payroll_vnd
		lineageTag: 73f45fe2-afa4-4624-957f-feef12d30567
		annotation SummarizationSetBy = User

	column benefits_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: benefits_vnd
		lineageTag: 78688cce-5a3b-4412-9f65-d8153a35a6f4
		annotation SummarizationSetBy = User

	column bonus_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: bonus_vnd
		lineageTag: 1e6a9ee7-6d28-4a08-b960-cba80f9e10f0
		annotation SummarizationSetBy = User

	column non_payroll_opex_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: non_payroll_opex_vnd
		lineageTag: a1677f96-3031-49af-a822-54bc3ebfd26e
		annotation SummarizationSetBy = User

	column opex_actual_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: opex_actual_vnd
		lineageTag: b6f87e70-0d43-43fd-813f-b35fcecdfbc1
		annotation SummarizationSetBy = User

	column opex_budget_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: opex_budget_vnd
		lineageTag: f03d3c8b-3f59-4733-9e66-3df9d324c344
		annotation SummarizationSetBy = User

	column opex_forecast_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: opex_forecast_vnd
		lineageTag: 150b03ec-77f8-4f56-80ef-07f18e968ffd
		annotation SummarizationSetBy = User

	column budget_variance_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: budget_variance_vnd
		lineageTag: 9178a139-f7eb-43ce-86f2-461af7f6a293
		annotation SummarizationSetBy = User

	column forecast_variance_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: forecast_variance_vnd
		lineageTag: e8c0d420-94f5-4cba-bbf8-5c794e0623e2
		annotation SummarizationSetBy = User

	column evidence_class
		dataType: string
		summarizeBy: none
		sourceColumn: evidence_class
		lineageTag: 181a1358-891f-48fd-b3a2-720aeb26f994
		annotation SummarizationSetBy = User

	column source_system
		dataType: string
		summarizeBy: none
		sourceColumn: source_system
		lineageTag: 89ad03eb-6727-41fd-a80c-d87d700e9793
		annotation SummarizationSetBy = User

	partition OPEX_Headcount = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\opex_headcount_planning_synthetic.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"period", type text}, {"cost_center", type text}, {"function", type text}, {"headcount_open", Int64.Type}, {"hires", Int64.Type}, {"exits", Int64.Type}, {"headcount_close", Int64.Type}, {"avg_headcount", type number}, {"avg_salary_vnd", type number}, {"payroll_vnd", type number}, {"benefits_vnd", type number}, {"bonus_vnd", type number}, {"non_payroll_opex_vnd", type number}, {"opex_actual_vnd", type number}, {"opex_budget_vnd", type number}, {"opex_forecast_vnd", type number}, {"budget_variance_vnd", type number}, {"forecast_variance_vnd", type number}, {"evidence_class", type text}, {"source_system", type text}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
