table OPEX_Headcount
	lineageTag: 8ff1fb13-74c7-4ec6-aa8f-c3745882cd84

	column period
		dataType: string
		summarizeBy: none
		sourceColumn: period
		lineageTag: 09b66e80-e96a-437f-9469-da7b0438a522
		annotation SummarizationSetBy = User

	column cost_center
		dataType: string
		summarizeBy: none
		sourceColumn: cost_center
		lineageTag: 6a761d89-d9bf-45c3-bfb6-c8833610f664
		annotation SummarizationSetBy = User

	column function
		dataType: string
		summarizeBy: none
		sourceColumn: function
		lineageTag: c8a314da-721a-44b5-abc8-d398bf2fee31
		annotation SummarizationSetBy = User

	column headcount_open
		dataType: int64
		summarizeBy: sum
		sourceColumn: headcount_open
		lineageTag: ade8125f-5d97-4be5-8231-fd679d75f07f
		annotation SummarizationSetBy = User

	column hires
		dataType: int64
		summarizeBy: sum
		sourceColumn: hires
		lineageTag: 6af33348-2df8-4884-be5e-71abfd0b2141
		annotation SummarizationSetBy = User

	column exits
		dataType: int64
		summarizeBy: sum
		sourceColumn: exits
		lineageTag: c810e83e-4490-4ee9-a612-91a1465cd76c
		annotation SummarizationSetBy = User

	column headcount_close
		dataType: int64
		summarizeBy: sum
		sourceColumn: headcount_close
		lineageTag: af28aca2-2bbf-4e6f-b472-57a6064919a9
		annotation SummarizationSetBy = User

	column avg_headcount
		dataType: double
		summarizeBy: sum
		sourceColumn: avg_headcount
		lineageTag: 3ac1793d-576d-4ebb-811d-fd0c6c3e15c9
		annotation SummarizationSetBy = User

	column avg_salary_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: avg_salary_vnd
		lineageTag: 4c7bb565-add7-42d8-a64d-f6748c6e0e47
		annotation SummarizationSetBy = User

	column payroll_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: payroll_vnd
		lineageTag: f414b118-563c-4cf7-b019-b754f6449c4a
		annotation SummarizationSetBy = User

	column benefits_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: benefits_vnd
		lineageTag: 359308c6-d75b-41b5-a871-c64b226bfac9
		annotation SummarizationSetBy = User

	column bonus_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: bonus_vnd
		lineageTag: 074cfcad-bdf0-43ff-9608-9e99b827ad36
		annotation SummarizationSetBy = User

	column non_payroll_opex_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: non_payroll_opex_vnd
		lineageTag: 41d99517-c270-4ce6-8848-c65c08296bdb
		annotation SummarizationSetBy = User

	column opex_actual_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: opex_actual_vnd
		lineageTag: 9c59556c-750f-46d1-991a-38fb156e89c2
		annotation SummarizationSetBy = User

	column opex_budget_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: opex_budget_vnd
		lineageTag: 0e25ebef-bc14-4e8e-a691-01a5c6cfc373
		annotation SummarizationSetBy = User

	column opex_forecast_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: opex_forecast_vnd
		lineageTag: a7697552-fba4-466e-9d15-6d64996e841a
		annotation SummarizationSetBy = User

	column budget_variance_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: budget_variance_vnd
		lineageTag: f9d0014f-6e33-4f77-9d73-97fd25e896de
		annotation SummarizationSetBy = User

	column forecast_variance_vnd
		dataType: double
		summarizeBy: sum
		sourceColumn: forecast_variance_vnd
		lineageTag: 83b6b393-50a6-4018-986c-61da897911be
		annotation SummarizationSetBy = User

	column evidence_class
		dataType: string
		summarizeBy: none
		sourceColumn: evidence_class
		lineageTag: 0c7f46d5-fe41-4229-9306-d8ee11dc288b
		annotation SummarizationSetBy = User

	column source_system
		dataType: string
		summarizeBy: none
		sourceColumn: source_system
		lineageTag: 438af570-9400-4303-8b7d-daa841522d2e
		annotation SummarizationSetBy = User

	partition OPEX_Headcount = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\opex_headcount_planning_synthetic.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"period", type text}, {"cost_center", type text}, {"function", type text}, {"headcount_open", Int64.Type}, {"hires", Int64.Type}, {"exits", Int64.Type}, {"headcount_close", Int64.Type}, {"avg_headcount", type number}, {"avg_salary_vnd", type number}, {"payroll_vnd", type number}, {"benefits_vnd", type number}, {"bonus_vnd", type number}, {"non_payroll_opex_vnd", type number}, {"opex_actual_vnd", type number}, {"opex_budget_vnd", type number}, {"opex_forecast_vnd", type number}, {"budget_variance_vnd", type number}, {"forecast_variance_vnd", type number}, {"evidence_class", type text}, {"source_system", type text}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
