table Payables
	lineageTag: 4a014648-af5e-40c4-8056-5c9ea30c9756

	column month
		dataType: dateTime
		summarizeBy: none
		sourceColumn: month
		lineageTag: 0a772d46-f23e-4067-bc08-ca27797eed03
		annotation SummarizationSetBy = User

	column supplier_id
		dataType: string
		summarizeBy: none
		sourceColumn: supplier_id
		lineageTag: 78216fd1-9904-49b0-a9be-42cebb946037
		annotation SummarizationSetBy = User

	column opening_ap
		dataType: double
		summarizeBy: sum
		sourceColumn: opening_ap
		lineageTag: 87819327-90fc-4f03-8bf4-d7334d54df06
		annotation SummarizationSetBy = User

	column purchases
		dataType: double
		summarizeBy: sum
		sourceColumn: purchases
		lineageTag: 4694f2e1-c7c1-4e80-a07e-71ad4d5fa208
		annotation SummarizationSetBy = User

	column cash_paid
		dataType: double
		summarizeBy: sum
		sourceColumn: cash_paid
		lineageTag: 597fd4e8-7b1f-4ffb-9b9e-e4ecd261c000
		annotation SummarizationSetBy = User

	column closing_ap
		dataType: double
		summarizeBy: sum
		sourceColumn: closing_ap
		lineageTag: 8bc879ea-d96f-47b2-8b6b-094296a880ba
		annotation SummarizationSetBy = User

	column overdue_ap
		dataType: double
		summarizeBy: sum
		sourceColumn: overdue_ap
		lineageTag: a86050e0-77ad-4695-b41b-2420e0aabc74
		annotation SummarizationSetBy = User

	column dpo
		dataType: double
		summarizeBy: none
		sourceColumn: dpo
		lineageTag: e6c45832-f5bf-4d5f-a8a9-a12faa6364ba
		annotation SummarizationSetBy = User

	partition Payables = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\payables.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"month", type date}, {"supplier_id", type text}, {"opening_ap", type number}, {"purchases", type number}, {"cash_paid", type number}, {"closing_ap", type number}, {"overdue_ap", type number}, {"dpo", type number}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
