table Payables
	lineageTag: eedb91ba-9557-442a-b031-8eb28f8232b8

	column month
		dataType: dateTime
		summarizeBy: none
		sourceColumn: month
		lineageTag: c913c18a-7dec-40a5-a611-19b0a7d05fc0
		annotation SummarizationSetBy = User

	column supplier_id
		dataType: string
		summarizeBy: none
		sourceColumn: supplier_id
		lineageTag: 3c1518bc-b101-4406-a8ff-417e57579852
		annotation SummarizationSetBy = User

	column opening_ap
		dataType: double
		summarizeBy: sum
		sourceColumn: opening_ap
		lineageTag: 3e0570d9-abc6-43a8-8616-91802ce9f0d4
		annotation SummarizationSetBy = User

	column purchases
		dataType: double
		summarizeBy: sum
		sourceColumn: purchases
		lineageTag: b936f832-188f-462c-87ae-58e5d30b5d41
		annotation SummarizationSetBy = User

	column cash_paid
		dataType: double
		summarizeBy: sum
		sourceColumn: cash_paid
		lineageTag: ca4a5d50-e50b-49ef-98d5-a7ac61ed779f
		annotation SummarizationSetBy = User

	column closing_ap
		dataType: double
		summarizeBy: sum
		sourceColumn: closing_ap
		lineageTag: 60e1fb23-dce2-41f5-8b84-2089a1386cd4
		annotation SummarizationSetBy = User

	column overdue_ap
		dataType: double
		summarizeBy: sum
		sourceColumn: overdue_ap
		lineageTag: 69fa51a5-81d1-4641-af56-0a91c6be29f7
		annotation SummarizationSetBy = User

	column dpo
		dataType: double
		summarizeBy: none
		sourceColumn: dpo
		lineageTag: d0e4ac63-a11c-4392-a28d-d0ff6bec8efb
		annotation SummarizationSetBy = User

	partition Payables = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\payables.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"month", type date}, {"supplier_id", type text}, {"opening_ap", type number}, {"purchases", type number}, {"cash_paid", type number}, {"closing_ap", type number}, {"overdue_ap", type number}, {"dpo", type number}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
