table Payables
	lineageTag: f0c7e965-e313-4def-b304-13502e4c15a4

	column month
		dataType: dateTime
		summarizeBy: none
		sourceColumn: month
		lineageTag: 56943cb3-fc4d-4f88-a553-d95c7cd052f4
		annotation SummarizationSetBy = User

	column supplier_id
		dataType: string
		summarizeBy: none
		sourceColumn: supplier_id
		lineageTag: be84946c-1ead-45a4-ad6b-ff4216c0db69
		annotation SummarizationSetBy = User

	column opening_ap
		dataType: double
		summarizeBy: sum
		sourceColumn: opening_ap
		lineageTag: 1f7a13bc-6d93-4bf9-a3ed-e34e38fa0882
		annotation SummarizationSetBy = User

	column purchases
		dataType: double
		summarizeBy: sum
		sourceColumn: purchases
		lineageTag: 1fa6434b-1b19-4906-85a1-39c92b238a5b
		annotation SummarizationSetBy = User

	column cash_paid
		dataType: double
		summarizeBy: sum
		sourceColumn: cash_paid
		lineageTag: 8ba19926-a032-4365-be12-b1bcd6eea70f
		annotation SummarizationSetBy = User

	column closing_ap
		dataType: double
		summarizeBy: sum
		sourceColumn: closing_ap
		lineageTag: ec4a2e07-f632-47c9-a43f-b0af7e11e92b
		annotation SummarizationSetBy = User

	column overdue_ap
		dataType: double
		summarizeBy: sum
		sourceColumn: overdue_ap
		lineageTag: 73cf6ca6-29fa-48c9-b7b6-15cf9450de34
		annotation SummarizationSetBy = User

	column dpo
		dataType: double
		summarizeBy: none
		sourceColumn: dpo
		lineageTag: 1e015bcf-b13e-4ed8-8ffb-d7cc0ebbc11b
		annotation SummarizationSetBy = User

	partition Payables = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\payables.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"month", type date}, {"supplier_id", type text}, {"opening_ap", type number}, {"purchases", type number}, {"cash_paid", type number}, {"closing_ap", type number}, {"overdue_ap", type number}, {"dpo", type number}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
