table Peer_Review_Queue
	lineageTag: 4a7dd474-3cbe-411b-9677-4c8ff83faa3f

	column company
		dataType: string
		summarizeBy: none
		sourceColumn: company
		lineageTag: c6cff080-b574-4193-8d9b-bbbf6eb58e1e
		annotation SummarizationSetBy = User

	column ticker
		dataType: string
		summarizeBy: none
		sourceColumn: ticker
		lineageTag: aecb95e4-7586-4669-a212-11e083b7524e
		annotation SummarizationSetBy = User

	column fiscal_year
		dataType: int64
		summarizeBy: none
		sourceColumn: fiscal_year
		lineageTag: 8baf567c-128f-46af-94a6-706a57157fa2
		annotation SummarizationSetBy = User

	column source_document
		dataType: string
		summarizeBy: none
		sourceColumn: source_document
		lineageTag: 02afb359-402c-4f1d-b20a-0a37171d4ff7
		annotation SummarizationSetBy = User

	column source_layer
		dataType: string
		summarizeBy: none
		sourceColumn: source_layer
		lineageTag: 7d002c9a-6455-4440-a5da-2a097beae267
		annotation SummarizationSetBy = User

	column review_status
		dataType: string
		summarizeBy: none
		sourceColumn: review_status
		lineageTag: c5240934-6a4f-4ab1-9e9b-860054d1ed48
		annotation SummarizationSetBy = User

	column required_metrics
		dataType: string
		summarizeBy: none
		sourceColumn: required_metrics
		lineageTag: 7c240d94-3d86-420c-a70f-8d92862fac5d
		annotation SummarizationSetBy = User

	column source_url
		dataType: string
		summarizeBy: none
		sourceColumn: source_url
		lineageTag: 3d16f703-3c8f-46e4-ba15-333ef33a2588
		annotation SummarizationSetBy = User

	column page_anchor
		dataType: string
		summarizeBy: none
		sourceColumn: page_anchor
		lineageTag: 9d180ffa-193e-4cf9-afc6-ddbfe653b08e
		annotation SummarizationSetBy = User

	column reported_basis
		dataType: string
		summarizeBy: none
		sourceColumn: reported_basis
		lineageTag: c633587d-46ca-4553-b794-80357215d5d6
		annotation SummarizationSetBy = User

	column reviewer_note
		dataType: string
		summarizeBy: none
		sourceColumn: reviewer_note
		lineageTag: 7bc46f82-f244-4611-a625-1ace8ea43cd0
		annotation SummarizationSetBy = User

	partition Peer_Review_Queue = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\peer_extraction_queue.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"company", type text}, {"ticker", type text}, {"fiscal_year", Int64.Type}, {"source_document", type text}, {"source_layer", type text}, {"review_status", type text}, {"required_metrics", type text}, {"source_url", type text}, {"page_anchor", type text}, {"reported_basis", type text}, {"reviewer_note", type text}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
