table Peer_Benchmark
	lineageTag: c6802a4f-e8b6-4c4b-99d4-b6cecd92b067

	column company
		dataType: string
		summarizeBy: none
		sourceColumn: company
		lineageTag: 3ea243e8-85be-4969-afeb-735f9e871d66
		annotation SummarizationSetBy = User

	column ticker
		dataType: string
		summarizeBy: none
		sourceColumn: ticker
		lineageTag: 44d8f632-b02a-4322-8a99-9d7ae912f402
		annotation SummarizationSetBy = User

	column fiscal_year
		dataType: int64
		summarizeBy: none
		sourceColumn: fiscal_year
		lineageTag: 32236419-6211-493b-96d1-6216be11fd99
		annotation SummarizationSetBy = User

	column net_revenue_vnd_bn
		dataType: double
		summarizeBy: sum
		sourceColumn: net_revenue_vnd_bn
		lineageTag: 05484e29-12a4-4a4d-94ac-87998c5e31c1
		annotation SummarizationSetBy = User

	column gross_profit_vnd_bn
		dataType: double
		summarizeBy: sum
		sourceColumn: gross_profit_vnd_bn
		lineageTag: e88a88be-adc7-42f9-8ef1-d3a02dc5d794
		annotation SummarizationSetBy = User

	column operating_profit_vnd_bn
		dataType: double
		summarizeBy: sum
		sourceColumn: operating_profit_vnd_bn
		lineageTag: 49bb1c48-daa9-478b-94de-c17e3797067d
		annotation SummarizationSetBy = User

	column profit_before_tax_vnd_bn
		dataType: double
		summarizeBy: sum
		sourceColumn: profit_before_tax_vnd_bn
		lineageTag: 0d847a99-b8fb-4512-b9c3-cb8572bab640
		annotation SummarizationSetBy = User

	column profit_after_tax_vnd_bn
		dataType: double
		summarizeBy: sum
		sourceColumn: profit_after_tax_vnd_bn
		lineageTag: 6861a26d-2146-4bea-8b03-2f872ebbc813
		annotation SummarizationSetBy = User

	column total_assets_vnd_bn
		dataType: double
		summarizeBy: sum
		sourceColumn: total_assets_vnd_bn
		lineageTag: 12331bde-8157-4f04-9485-d1645a4029c6
		annotation SummarizationSetBy = User

	column owners_equity_vnd_bn
		dataType: double
		summarizeBy: sum
		sourceColumn: owners_equity_vnd_bn
		lineageTag: c0c0d912-d498-40f7-9b75-d08d9b8a9805
		annotation SummarizationSetBy = User

	column operating_cash_flow_vnd_bn
		dataType: double
		summarizeBy: sum
		sourceColumn: operating_cash_flow_vnd_bn
		lineageTag: a194be8c-1382-46dc-95f9-54fce18840b8
		annotation SummarizationSetBy = User

	column source_status
		dataType: string
		summarizeBy: none
		sourceColumn: source_status
		lineageTag: 5162f6e5-5165-4f8c-b62a-7955f5d1a17e
		annotation SummarizationSetBy = User

	column source_layer
		dataType: string
		summarizeBy: none
		sourceColumn: source_layer
		lineageTag: dd075105-6e4d-48fc-bb2a-7cc46c1165c7
		annotation SummarizationSetBy = User

	column revenue_basis
		dataType: string
		summarizeBy: none
		sourceColumn: revenue_basis
		lineageTag: 37349ac4-072e-44c9-a8a9-19dd0016daec
		annotation SummarizationSetBy = User

	column source_document
		dataType: string
		summarizeBy: none
		sourceColumn: source_document
		lineageTag: 345aac04-f055-4307-be7e-6816114532da
		annotation SummarizationSetBy = User

	column source_url
		dataType: string
		summarizeBy: none
		sourceColumn: source_url
		lineageTag: 6a1dae51-1acc-4493-9c43-960fe60dfc3a
		annotation SummarizationSetBy = User

	column page_anchor
		dataType: string
		summarizeBy: none
		sourceColumn: page_anchor
		lineageTag: 6862473c-c35d-4c2d-9129-2fee3719d69c
		annotation SummarizationSetBy = User

	column comparability_note
		dataType: string
		summarizeBy: none
		sourceColumn: comparability_note
		lineageTag: a5e8971b-982c-40d9-ad5c-e44118a9d1d9
		annotation SummarizationSetBy = User

	partition Peer_Benchmark = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\peer_benchmark_approved_2016_2025.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"company", type text}, {"ticker", type text}, {"fiscal_year", Int64.Type}, {"net_revenue_vnd_bn", type number}, {"gross_profit_vnd_bn", type number}, {"operating_profit_vnd_bn", type number}, {"profit_before_tax_vnd_bn", type number}, {"profit_after_tax_vnd_bn", type number}, {"total_assets_vnd_bn", type number}, {"owners_equity_vnd_bn", type number}, {"operating_cash_flow_vnd_bn", type number}, {"source_status", type text}, {"source_layer", type text}, {"revenue_basis", type text}, {"source_document", type text}, {"source_url", type text}, {"page_anchor", type text}, {"comparability_note", type text}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
