table Peer_Benchmark
	lineageTag: abedc8a9-b9e1-49bb-9eae-641a529f0ab9

	column company
		dataType: string
		summarizeBy: none
		sourceColumn: company
		lineageTag: 9b3a3d31-9a9c-4582-980b-f21c0f19b1bc
		annotation SummarizationSetBy = User

	column ticker
		dataType: string
		summarizeBy: none
		sourceColumn: ticker
		lineageTag: 5403072e-251e-4656-be90-f01e312ddb89
		annotation SummarizationSetBy = User

	column fiscal_year
		dataType: int64
		summarizeBy: none
		sourceColumn: fiscal_year
		lineageTag: 17f091b0-cb0e-4eeb-91dc-1bbd060bd245
		annotation SummarizationSetBy = User

	column net_revenue_vnd_bn
		dataType: double
		summarizeBy: sum
		sourceColumn: net_revenue_vnd_bn
		lineageTag: 19d6d18c-5dbc-4559-8e74-4fde2e06f64d
		annotation SummarizationSetBy = User

	column gross_profit_vnd_bn
		dataType: double
		summarizeBy: sum
		sourceColumn: gross_profit_vnd_bn
		lineageTag: 6c3c30a6-39a8-4b74-855f-5efa493ecee4
		annotation SummarizationSetBy = User

	column operating_profit_vnd_bn
		dataType: double
		summarizeBy: sum
		sourceColumn: operating_profit_vnd_bn
		lineageTag: bca1d844-a08b-4f2e-845b-231c9518966c
		annotation SummarizationSetBy = User

	column profit_before_tax_vnd_bn
		dataType: double
		summarizeBy: sum
		sourceColumn: profit_before_tax_vnd_bn
		lineageTag: f9ea5f73-d87e-4962-996e-66cbf05f47dc
		annotation SummarizationSetBy = User

	column profit_after_tax_vnd_bn
		dataType: double
		summarizeBy: sum
		sourceColumn: profit_after_tax_vnd_bn
		lineageTag: bbe5b745-e7a2-41fc-b253-77e6a892de56
		annotation SummarizationSetBy = User

	column total_assets_vnd_bn
		dataType: double
		summarizeBy: sum
		sourceColumn: total_assets_vnd_bn
		lineageTag: 8bca4b5e-fdcb-4fc5-8e85-8d409dcf380f
		annotation SummarizationSetBy = User

	column owners_equity_vnd_bn
		dataType: double
		summarizeBy: sum
		sourceColumn: owners_equity_vnd_bn
		lineageTag: 417d07d0-7596-4621-97a2-0f18c6ce0e23
		annotation SummarizationSetBy = User

	column operating_cash_flow_vnd_bn
		dataType: double
		summarizeBy: sum
		sourceColumn: operating_cash_flow_vnd_bn
		lineageTag: c06ed2be-b574-4e7f-a21f-32cc24a2b86c
		annotation SummarizationSetBy = User

	column source_status
		dataType: string
		summarizeBy: none
		sourceColumn: source_status
		lineageTag: e7c54b37-df76-40a7-a9b5-74b8932342bf
		annotation SummarizationSetBy = User

	column source_layer
		dataType: string
		summarizeBy: none
		sourceColumn: source_layer
		lineageTag: e173cd31-46d0-499a-9d8f-43dddf69c820
		annotation SummarizationSetBy = User

	column revenue_basis
		dataType: string
		summarizeBy: none
		sourceColumn: revenue_basis
		lineageTag: 56adc16f-02fd-4264-82bc-d18fcdbf70b1
		annotation SummarizationSetBy = User

	column source_document
		dataType: string
		summarizeBy: none
		sourceColumn: source_document
		lineageTag: 9d924a73-d937-4a62-a224-b592fe0862cf
		annotation SummarizationSetBy = User

	column source_url
		dataType: string
		summarizeBy: none
		sourceColumn: source_url
		lineageTag: 3aee5cc4-4779-45e4-bc88-481c1bf1c2ed
		annotation SummarizationSetBy = User

	column page_anchor
		dataType: string
		summarizeBy: none
		sourceColumn: page_anchor
		lineageTag: 831cf0d3-b3a1-45fe-b7cb-f54d3faa8f6c
		annotation SummarizationSetBy = User

	column comparability_note
		dataType: string
		summarizeBy: none
		sourceColumn: comparability_note
		lineageTag: 19335484-8d44-4c37-aeda-25c49c9dda64
		annotation SummarizationSetBy = User

	partition Peer_Benchmark = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\peer_benchmark_approved_2016_2025.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"company", type text}, {"ticker", type text}, {"fiscal_year", Int64.Type}, {"net_revenue_vnd_bn", type number}, {"gross_profit_vnd_bn", type number}, {"operating_profit_vnd_bn", type number}, {"profit_before_tax_vnd_bn", type number}, {"profit_after_tax_vnd_bn", type number}, {"total_assets_vnd_bn", type number}, {"owners_equity_vnd_bn", type number}, {"operating_cash_flow_vnd_bn", type number}, {"source_status", type text}, {"source_layer", type text}, {"revenue_basis", type text}, {"source_document", type text}, {"source_url", type text}, {"page_anchor", type text}, {"comparability_note", type text}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
