table Peer_Review_Queue
	lineageTag: a0c7b217-8b9d-4ce8-88f5-f240ad255d6a

	column company
		dataType: string
		summarizeBy: none
		sourceColumn: company
		lineageTag: 5dfa32bf-200e-4a57-a7be-771c8000ed84
		annotation SummarizationSetBy = User

	column ticker
		dataType: string
		summarizeBy: none
		sourceColumn: ticker
		lineageTag: fa31b505-346c-4096-97c8-079990b56cc6
		annotation SummarizationSetBy = User

	column fiscal_year
		dataType: int64
		summarizeBy: none
		sourceColumn: fiscal_year
		lineageTag: 2f415f79-d6a3-487a-a9bd-9c4c781e3130
		annotation SummarizationSetBy = User

	column source_document
		dataType: string
		summarizeBy: none
		sourceColumn: source_document
		lineageTag: e63ea2b5-e167-4745-9bd9-ffff54ddf082
		annotation SummarizationSetBy = User

	column source_layer
		dataType: string
		summarizeBy: none
		sourceColumn: source_layer
		lineageTag: d0c94169-4120-4e75-9766-2b6177d781b4
		annotation SummarizationSetBy = User

	column review_status
		dataType: string
		summarizeBy: none
		sourceColumn: review_status
		lineageTag: ed49bbbf-9887-4994-bfe5-a978d62e51a7
		annotation SummarizationSetBy = User

	column required_metrics
		dataType: string
		summarizeBy: none
		sourceColumn: required_metrics
		lineageTag: 17966506-c3fa-4477-a101-3c574c2a13a6
		annotation SummarizationSetBy = User

	column source_url
		dataType: string
		summarizeBy: none
		sourceColumn: source_url
		lineageTag: 78f993c0-e95b-425a-b2e9-8ac809ecee2f
		annotation SummarizationSetBy = User

	column page_anchor
		dataType: string
		summarizeBy: none
		sourceColumn: page_anchor
		lineageTag: ad9fcec8-25f8-45de-a1e9-255f69e5f4b7
		annotation SummarizationSetBy = User

	column reported_basis
		dataType: string
		summarizeBy: none
		sourceColumn: reported_basis
		lineageTag: 0f98df9c-cbcc-4fe2-afe0-0ef983b44222
		annotation SummarizationSetBy = User

	column reviewer_note
		dataType: string
		summarizeBy: none
		sourceColumn: reviewer_note
		lineageTag: c50497b3-f8f6-4b3e-8543-35ace0861e06
		annotation SummarizationSetBy = User

	partition Peer_Review_Queue = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\peer_extraction_queue.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"company", type text}, {"ticker", type text}, {"fiscal_year", Int64.Type}, {"source_document", type text}, {"source_layer", type text}, {"review_status", type text}, {"required_metrics", type text}, {"source_url", type text}, {"page_anchor", type text}, {"reported_basis", type text}, {"reviewer_note", type text}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
