table Product
	lineageTag: 9f118e5c-c11f-4e2e-b9a5-1272c71345de

	column sku_id
		dataType: string
		isKey
		summarizeBy: none
		sourceColumn: sku_id
		lineageTag: 9f76faa1-16a9-4594-85f7-1f5b2b2bf656
		annotation SummarizationSetBy = User

	column brand
		dataType: string
		summarizeBy: none
		sourceColumn: brand
		lineageTag: 94023355-146c-4a19-905b-19fd4e572448
		annotation SummarizationSetBy = User

	column category
		dataType: string
		summarizeBy: none
		sourceColumn: category
		lineageTag: 64f81b9f-6d08-4b14-9be0-d9851ff7ccbb
		annotation SummarizationSetBy = User

	column launch_month
		dataType: dateTime
		summarizeBy: none
		sourceColumn: launch_month
		lineageTag: da2c87ed-76ad-4cdc-a656-1bb70a8b9e9f
		annotation SummarizationSetBy = User

	column list_price
		dataType: double
		summarizeBy: sum
		sourceColumn: list_price
		lineageTag: 6ab35d7f-1557-4c22-ba45-df83e2955abe
		annotation SummarizationSetBy = User

	column pack_size
		dataType: int64
		summarizeBy: none
		sourceColumn: pack_size
		lineageTag: fb657775-65a2-4576-94b3-4b3e0d09896f
		annotation SummarizationSetBy = User

	column standard_cogs
		dataType: double
		summarizeBy: sum
		sourceColumn: standard_cogs
		lineageTag: 883ce084-3e5b-4515-aba4-f10966fd5d52
		annotation SummarizationSetBy = User

	column status
		dataType: string
		summarizeBy: none
		sourceColumn: status
		lineageTag: 79caed1b-d008-4b5a-a89b-d6982e836b4b
		annotation SummarizationSetBy = User

	column supplier_id
		dataType: string
		summarizeBy: none
		sourceColumn: supplier_id
		lineageTag: 860af870-b79c-414d-b95a-005c80ec5887
		annotation SummarizationSetBy = User

	partition Product = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\product_master.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"sku_id", type text}, {"brand", type text}, {"category", type text}, {"launch_month", type date}, {"list_price", type number}, {"pack_size", Int64.Type}, {"standard_cogs", type number}, {"status", type text}, {"supplier_id", type text}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
