table Product
	lineageTag: 2d6a3226-395f-4dc7-ba43-7828e215d8fe

	column sku_id
		dataType: string
		isKey
		summarizeBy: none
		sourceColumn: sku_id
		lineageTag: c1909191-3992-4295-aea4-bdae5c93b33a
		annotation SummarizationSetBy = User

	column brand
		dataType: string
		summarizeBy: none
		sourceColumn: brand
		lineageTag: 61a78524-50b9-4aa6-bd6e-45d4fee1841b
		annotation SummarizationSetBy = User

	column category
		dataType: string
		summarizeBy: none
		sourceColumn: category
		lineageTag: f55e50aa-67ae-46b8-8e9a-40ba48f91965
		annotation SummarizationSetBy = User

	column launch_month
		dataType: dateTime
		summarizeBy: none
		sourceColumn: launch_month
		lineageTag: 438ea68b-e703-490c-ae57-59455166cbdf
		annotation SummarizationSetBy = User

	column list_price
		dataType: double
		summarizeBy: sum
		sourceColumn: list_price
		lineageTag: 6f3e443e-b64d-4412-83b9-a77477b5edc3
		annotation SummarizationSetBy = User

	column pack_size
		dataType: int64
		summarizeBy: none
		sourceColumn: pack_size
		lineageTag: d58768d6-b862-491c-899a-b2359967070a
		annotation SummarizationSetBy = User

	column standard_cogs
		dataType: double
		summarizeBy: sum
		sourceColumn: standard_cogs
		lineageTag: 5cd241ff-cea7-4847-baef-558721e7bf3b
		annotation SummarizationSetBy = User

	column status
		dataType: string
		summarizeBy: none
		sourceColumn: status
		lineageTag: e264a158-904f-4527-a0c0-8a3ac040e2d3
		annotation SummarizationSetBy = User

	column supplier_id
		dataType: string
		summarizeBy: none
		sourceColumn: supplier_id
		lineageTag: 2374d1b0-3621-46dc-a39c-8617cd86638f
		annotation SummarizationSetBy = User

	partition Product = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\product_master.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"sku_id", type text}, {"brand", type text}, {"category", type text}, {"launch_month", type date}, {"list_price", type number}, {"pack_size", Int64.Type}, {"standard_cogs", type number}, {"status", type text}, {"supplier_id", type text}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
