table Promotions
	lineageTag: e7f43b7f-67a4-471a-b120-af7b11193762

	column promo_id
		dataType: string
		isKey
		summarizeBy: none
		sourceColumn: promo_id
		lineageTag: 19eea808-914c-4066-9728-e9c6eb54aa5c
		annotation SummarizationSetBy = User

	column start_date
		dataType: dateTime
		summarizeBy: none
		sourceColumn: start_date
		lineageTag: 871e38ec-a396-4980-be8e-a57c49304abe
		annotation SummarizationSetBy = User

	column end_date
		dataType: dateTime
		summarizeBy: none
		sourceColumn: end_date
		lineageTag: f73b2c49-eadd-45b7-99dd-b8e89f96eef1
		annotation SummarizationSetBy = User

	column channel_id
		dataType: string
		summarizeBy: none
		sourceColumn: channel_id
		lineageTag: e83bdb85-a211-4eee-9a3d-003c7ade7e25
		annotation SummarizationSetBy = User

	column sku_id
		dataType: string
		summarizeBy: none
		sourceColumn: sku_id
		lineageTag: 5ac37eb0-0a95-4ecc-be00-17cc9a98e944
		annotation SummarizationSetBy = User

	column mechanic
		dataType: string
		summarizeBy: none
		sourceColumn: mechanic
		lineageTag: 54039656-0217-4d8d-b593-5e66218cc8e8
		annotation SummarizationSetBy = User

	column planned_discount_pct
		dataType: double
		summarizeBy: none
		sourceColumn: planned_discount_pct
		lineageTag: df115150-f792-41be-a4e7-823528da3069
		annotation SummarizationSetBy = User

	column planned_units_lift_pct
		dataType: double
		summarizeBy: none
		sourceColumn: planned_units_lift_pct
		lineageTag: fcef1ac7-c54b-489c-b9bf-c7c98ec81768
		annotation SummarizationSetBy = User

	column actual_discount_pct
		dataType: double
		summarizeBy: none
		sourceColumn: actual_discount_pct
		lineageTag: 0308da1d-613d-493c-98a7-27e0f977bafb
		annotation SummarizationSetBy = User

	column incremental_units
		dataType: int64
		summarizeBy: sum
		sourceColumn: incremental_units
		lineageTag: 2eff7f87-1de9-4611-98be-9f62a1c80c95
		annotation SummarizationSetBy = User

	column baseline_units
		dataType: int64
		summarizeBy: sum
		sourceColumn: baseline_units
		lineageTag: 8d47dff5-32a5-40fd-865b-dddf66a2948d
		annotation SummarizationSetBy = User

	column promo_spend
		dataType: double
		summarizeBy: sum
		sourceColumn: promo_spend
		lineageTag: fb164bf2-741c-41a8-9efd-c319889bdf5e
		annotation SummarizationSetBy = User

	column roi
		dataType: double
		summarizeBy: none
		sourceColumn: roi
		lineageTag: eb4814dd-d954-458f-b5d7-8b6e3b3c9fe6
		annotation SummarizationSetBy = User

	column status
		dataType: string
		summarizeBy: none
		sourceColumn: status
		lineageTag: 8eb2062d-1fa2-41ae-bd2c-d755159036d4
		annotation SummarizationSetBy = User

	partition Promotions = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\promotions.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"promo_id", type text}, {"start_date", type date}, {"end_date", type date}, {"channel_id", type text}, {"sku_id", type text}, {"mechanic", type text}, {"planned_discount_pct", type number}, {"planned_units_lift_pct", type number}, {"actual_discount_pct", type number}, {"incremental_units", Int64.Type}, {"baseline_units", Int64.Type}, {"promo_spend", type number}, {"roi", type number}, {"status", type text}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
