table Promotions
	lineageTag: 79efe39d-f3b9-4582-b94c-71cfecb1274a

	column promo_id
		dataType: string
		isKey
		summarizeBy: none
		sourceColumn: promo_id
		lineageTag: 511618f3-d7ae-4353-9e59-d9c160c381a2
		annotation SummarizationSetBy = User

	column start_date
		dataType: dateTime
		summarizeBy: none
		sourceColumn: start_date
		lineageTag: 9d768baa-46e5-41bb-acca-5594ed5c2bdc
		annotation SummarizationSetBy = User

	column end_date
		dataType: dateTime
		summarizeBy: none
		sourceColumn: end_date
		lineageTag: cc695fc3-9c56-4c77-a4ea-16ed110ca329
		annotation SummarizationSetBy = User

	column channel_id
		dataType: string
		summarizeBy: none
		sourceColumn: channel_id
		lineageTag: 537cea28-10ae-4654-a1d4-55fadb7a7aaf
		annotation SummarizationSetBy = User

	column sku_id
		dataType: string
		summarizeBy: none
		sourceColumn: sku_id
		lineageTag: f2378ffd-e8ff-474b-8903-377bc4715582
		annotation SummarizationSetBy = User

	column mechanic
		dataType: string
		summarizeBy: none
		sourceColumn: mechanic
		lineageTag: 3523277e-92e1-4503-95d3-ef7ba7503bc3
		annotation SummarizationSetBy = User

	column planned_discount_pct
		dataType: double
		summarizeBy: none
		sourceColumn: planned_discount_pct
		lineageTag: 918415ff-ee47-4d0b-9646-2fa7329ef86c
		annotation SummarizationSetBy = User

	column planned_units_lift_pct
		dataType: double
		summarizeBy: none
		sourceColumn: planned_units_lift_pct
		lineageTag: eaeceb0e-25af-4e61-a117-a7a39e4553ea
		annotation SummarizationSetBy = User

	column actual_discount_pct
		dataType: double
		summarizeBy: none
		sourceColumn: actual_discount_pct
		lineageTag: d1a1a0dc-91f7-41c8-9756-3be3df243562
		annotation SummarizationSetBy = User

	column incremental_units
		dataType: int64
		summarizeBy: sum
		sourceColumn: incremental_units
		lineageTag: d41f6eb2-9fe6-4803-8847-b84157aa7047
		annotation SummarizationSetBy = User

	column baseline_units
		dataType: int64
		summarizeBy: sum
		sourceColumn: baseline_units
		lineageTag: 43b7c9d0-1522-4c49-9cef-c764691b8fbb
		annotation SummarizationSetBy = User

	column promo_spend
		dataType: double
		summarizeBy: sum
		sourceColumn: promo_spend
		lineageTag: b1cbafd9-483e-49c7-8bf6-23a1e7bf16df
		annotation SummarizationSetBy = User

	column roi
		dataType: double
		summarizeBy: none
		sourceColumn: roi
		lineageTag: 6c67604a-445a-432d-8d38-96ceccef4ad1
		annotation SummarizationSetBy = User

	column status
		dataType: string
		summarizeBy: none
		sourceColumn: status
		lineageTag: 0d9fbb29-7d83-4d9e-9ae7-2552fee9dabc
		annotation SummarizationSetBy = User

	partition Promotions = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\promotions.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"promo_id", type text}, {"start_date", type date}, {"end_date", type date}, {"channel_id", type text}, {"sku_id", type text}, {"mechanic", type text}, {"planned_discount_pct", type number}, {"planned_units_lift_pct", type number}, {"actual_discount_pct", type number}, {"incremental_units", Int64.Type}, {"baseline_units", Int64.Type}, {"promo_spend", type number}, {"roi", type number}, {"status", type text}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
