table Receivables
	lineageTag: 9dd13ad7-9526-465b-a434-74318a2c87dd

	column month
		dataType: dateTime
		summarizeBy: none
		sourceColumn: month
		lineageTag: e22bf61a-4959-4cb5-a4d2-f23fcb326e2b
		annotation SummarizationSetBy = User

	column customer_id
		dataType: string
		summarizeBy: none
		sourceColumn: customer_id
		lineageTag: ca9fba39-df9d-4982-b34b-b6fd5451a2ac
		annotation SummarizationSetBy = User

	column opening_ar
		dataType: double
		summarizeBy: sum
		sourceColumn: opening_ar
		lineageTag: 1b6edb6c-3a64-4343-a927-63ac36ccb487
		annotation SummarizationSetBy = User

	column invoiced
		dataType: double
		summarizeBy: sum
		sourceColumn: invoiced
		lineageTag: c46f6a7c-71d7-4f78-bcbc-63d44ea9b8f5
		annotation SummarizationSetBy = User

	column cash_collected
		dataType: double
		summarizeBy: sum
		sourceColumn: cash_collected
		lineageTag: 978a0458-c286-42e7-bac7-a01e1fc9ed36
		annotation SummarizationSetBy = User

	column credit_note
		dataType: double
		summarizeBy: sum
		sourceColumn: credit_note
		lineageTag: 971594f9-14c3-4f9c-a391-7321c2080bd9
		annotation SummarizationSetBy = User

	column closing_ar
		dataType: double
		summarizeBy: sum
		sourceColumn: closing_ar
		lineageTag: bdb8686d-6bec-45c4-8637-ee772f7a7318
		annotation SummarizationSetBy = User

	column overdue_0_30
		dataType: double
		summarizeBy: sum
		sourceColumn: overdue_0_30
		lineageTag: 6e54eb30-1242-4718-82b9-7090cbd5ab29
		annotation SummarizationSetBy = User

	column overdue_31_60
		dataType: double
		summarizeBy: sum
		sourceColumn: overdue_31_60
		lineageTag: 54bcdcc9-1033-47a2-8037-82d7fe577b7b
		annotation SummarizationSetBy = User

	column overdue_61_plus
		dataType: double
		summarizeBy: sum
		sourceColumn: overdue_61_plus
		lineageTag: ca02eb48-5037-4664-98ef-a9542e4bd1f6
		annotation SummarizationSetBy = User

	column dso
		dataType: double
		summarizeBy: none
		sourceColumn: dso
		lineageTag: d1f1f3da-3f0c-47d9-aec4-2237f9dbb014
		annotation SummarizationSetBy = User

	partition Receivables = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\receivables.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"month", type date}, {"customer_id", type text}, {"opening_ar", type number}, {"invoiced", type number}, {"cash_collected", type number}, {"credit_note", type number}, {"closing_ar", type number}, {"overdue_0_30", type number}, {"overdue_31_60", type number}, {"overdue_61_plus", type number}, {"dso", type number}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
