table Receivables
	lineageTag: a5a5f685-1046-43a6-8941-8351a3872da8

	column month
		dataType: dateTime
		summarizeBy: none
		sourceColumn: month
		lineageTag: ac69051d-5613-4887-b961-c67b342ed0a7
		annotation SummarizationSetBy = User

	column customer_id
		dataType: string
		summarizeBy: none
		sourceColumn: customer_id
		lineageTag: f914d569-7ca3-414c-b613-9984b6724bdf
		annotation SummarizationSetBy = User

	column opening_ar
		dataType: double
		summarizeBy: sum
		sourceColumn: opening_ar
		lineageTag: a78edb6a-2976-44d0-8a3f-861e6ff0f830
		annotation SummarizationSetBy = User

	column invoiced
		dataType: double
		summarizeBy: sum
		sourceColumn: invoiced
		lineageTag: edc7fc72-92da-445a-b166-41d269a69afe
		annotation SummarizationSetBy = User

	column cash_collected
		dataType: double
		summarizeBy: sum
		sourceColumn: cash_collected
		lineageTag: b75d41b7-8354-45d5-9a82-87668b339986
		annotation SummarizationSetBy = User

	column credit_note
		dataType: double
		summarizeBy: sum
		sourceColumn: credit_note
		lineageTag: 025fd885-20c3-40ae-84d3-9edb34d400f1
		annotation SummarizationSetBy = User

	column closing_ar
		dataType: double
		summarizeBy: sum
		sourceColumn: closing_ar
		lineageTag: 7cf6c5e6-6ebb-4d8f-8be6-610a66701fb4
		annotation SummarizationSetBy = User

	column overdue_0_30
		dataType: double
		summarizeBy: sum
		sourceColumn: overdue_0_30
		lineageTag: a7529301-7b25-4cc3-a3ed-6b5f4ee772d4
		annotation SummarizationSetBy = User

	column overdue_31_60
		dataType: double
		summarizeBy: sum
		sourceColumn: overdue_31_60
		lineageTag: 5bd39e50-8847-4da2-94c1-4159e56ecd64
		annotation SummarizationSetBy = User

	column overdue_61_plus
		dataType: double
		summarizeBy: sum
		sourceColumn: overdue_61_plus
		lineageTag: c7b6ca76-4b6a-4634-b99d-6995ccf8b1e2
		annotation SummarizationSetBy = User

	column dso
		dataType: double
		summarizeBy: none
		sourceColumn: dso
		lineageTag: 47bfc586-cea1-4ea9-9a5c-36bd0097ac15
		annotation SummarizationSetBy = User

	partition Receivables = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\receivables.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"month", type date}, {"customer_id", type text}, {"opening_ar", type number}, {"invoiced", type number}, {"cash_collected", type number}, {"credit_note", type number}, {"closing_ar", type number}, {"overdue_0_30", type number}, {"overdue_31_60", type number}, {"overdue_61_plus", type number}, {"dso", type number}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
