table Sales
	lineageTag: 231c0a47-c4f7-4fcf-bb7f-24ac0b330a26

	measure 'Net Revenue' = SUM ( Sales[net_sales] )
		formatString: #,0,,.0 M
		lineageTag: 69dd2bc2-9b9a-4d1b-a838-b36020c0d3bf

	measure 'Gross Sales' = SUM ( Sales[gross_sales] )
		formatString: #,0,,.0 M
		lineageTag: 8fe01818-2db8-4c0f-b038-1dfac1cd4412

	measure 'COGS Total' = SUM ( Sales[cogs] )
		formatString: #,0,,.0 M
		lineageTag: 3f30a45d-d75f-4145-a517-267a4463a763

	measure 'Gross Profit' = [Net Revenue] - [COGS Total]
		formatString: #,0,,.0 M
		lineageTag: 21fa5ce2-7322-4590-a3e2-2606e57db54f

	measure 'Gross Margin %' = DIVIDE ( [Gross Profit], [Net Revenue] )
		formatString: 0.0%
		lineageTag: 93974251-7936-490b-941a-72e1a5771ffc

	measure 'Contribution Margin' = SUM ( Sales[contribution_margin] )
		formatString: #,0,,.0 M
		lineageTag: 013412bf-7c51-4fd2-98a3-45a1179bd518

	measure 'Contribution Margin %' = DIVIDE ( [Contribution Margin], [Net Revenue] )
		formatString: 0.0%
		lineageTag: f87a09b1-55cc-4bb8-8d69-816a18a9c179

	measure 'Units Total' = SUM ( Sales[units] )
		formatString: #,0
		lineageTag: 4b362875-1679-4680-a59a-a94253c49e5c

	measure ASP = DIVIDE ( [Net Revenue], [Units Total] )
		formatString: #,0
		lineageTag: d5e45086-9a06-489f-9ea3-1731ee6c0669

	measure 'Budget Revenue' = SUM ( Budget[budget_net_sales] )
		formatString: #,0,,.0 M
		lineageTag: 7c63881d-f8be-4b2a-aeb4-4a52f7069bfd

	measure 'Forecast Revenue' = SUM ( Forecast[forecast_net_sales] )
		formatString: #,0,,.0 M
		lineageTag: 89aeb8fe-84b6-40ad-b856-5acc80191e0a

	measure 'Revenue vs Budget' = [Net Revenue] - [Budget Revenue]
		formatString: #,0,,.0 M;(#,0,,.0 M)
		lineageTag: 8a34da5e-ba2a-4fb4-a27b-648f6be013bc

	measure 'Revenue vs Budget %' = DIVIDE ( [Revenue vs Budget], [Budget Revenue] )
		formatString: 0.0%;(0.0%)
		lineageTag: 65abfb6a-15ea-44f1-87aa-9e4773cb336c

	measure 'Revenue vs Forecast' = [Net Revenue] - [Forecast Revenue]
		formatString: #,0,,.0 M;(#,0,,.0 M)
		lineageTag: 1673bcc0-2074-465b-b338-042890521e8c

	measure 'Revenue vs Forecast %' = DIVIDE ( [Revenue vs Forecast], [Forecast Revenue] )
		formatString: 0.0%;(0.0%)
		lineageTag: 06f47fae-4556-4969-9372-75fd8599d8b2

	measure 'Prior Net Revenue' = CALCULATE ( [Net Revenue], DATEADD ( Calendar[month], -1, MONTH ) )
		formatString: #,0,,.0 M
		lineageTag: 13c7a7fd-1940-4390-9da1-c9d74c451d79

	measure 'Revenue Growth %' = DIVIDE ( [Net Revenue] - [Prior Net Revenue], [Prior Net Revenue] )
		formatString: 0.0%;(0.0%)
		lineageTag: a6bcc022-1c82-4d4e-bac7-123b6d4d2dbf

	measure 'Prior Units' = CALCULATE ( [Units Total], DATEADD ( Calendar[month], -1, MONTH ) )
		formatString: #,0
		lineageTag: de3c02eb-fdb4-4495-808e-a9f76d0cdedb

	measure 'Prior ASP' = CALCULATE ( [ASP], DATEADD ( Calendar[month], -1, MONTH ) )
		formatString: #,0
		lineageTag: 21c1986c-1ab0-40e8-8e57-4bdda53b7d17

	measure 'Price Impact' = ( [ASP] - [Prior ASP] ) * [Units Total]
		formatString: #,0,,.0 M;(#,0,,.0 M)
		lineageTag: 36f53daf-15ce-4df6-b36e-0a83a9765c2b

	measure 'Volume Impact' = ( [Units Total] - [Prior Units] ) * [Prior ASP]
		formatString: #,0,,.0 M;(#,0,,.0 M)
		lineageTag: 50492ae2-892c-4f8a-97bb-1d15df1cf10a

	measure 'Mix Other Impact' = [Net Revenue] - [Prior Net Revenue] - [Price Impact] - [Volume Impact]
		formatString: #,0,,.0 M;(#,0,,.0 M)
		lineageTag: 254241de-e34e-40f3-bf72-b0daa8806dbe

	measure 'Trade Spend' = SUM ( Commercial_Costs[trade_spend] )
		formatString: #,0,,.0 M
		lineageTag: 4894f284-63f7-45bc-8fdf-ef2afe7692b9

	measure 'Marketing Spend' = SUM ( Marketing[spend] )
		formatString: #,0,,.0 M
		lineageTag: 0b98ef09-d71f-48d6-b5ac-fef1738968d9

	measure 'Ending AR' = CALCULATE ( SUM ( Receivables[closing_ar] ), LASTDATE ( Calendar[month] ) )
		formatString: #,0,,.0 M
		lineageTag: b8c07b98-6be7-4c00-a059-aca642c812a8

	measure 'Ending Inventory' = CALCULATE ( SUM ( Inventory[inventory_value] ), LASTDATE ( Calendar[month] ) )
		formatString: #,0,,.0 M
		lineageTag: f85272b6-1ff1-4d49-b57e-a5b048d18794

	measure 'Ending AP' = CALCULATE ( SUM ( Payables[closing_ap] ), LASTDATE ( Calendar[month] ) )
		formatString: #,0,,.0 M
		lineageTag: 75166cd0-23ff-4612-811c-b758a59403d8

	measure DSO = CALCULATE ( AVERAGE ( Receivables[dso] ), LASTDATE ( Calendar[month] ) )
		formatString: 0.0
		lineageTag: 1d66bce5-e718-484c-b8ea-48e41f784bbf

	measure DIO = CALCULATE ( AVERAGE ( Inventory[days_on_hand] ), LASTDATE ( Calendar[month] ) )
		formatString: 0.0
		lineageTag: 9e80dcf4-ec0c-4d9b-a97a-87b28b37fa1f

	measure DPO = CALCULATE ( AVERAGE ( Payables[dpo] ), LASTDATE ( Calendar[month] ) )
		formatString: 0.0
		lineageTag: c3cea9fa-1bd3-4c57-b2f2-2f12d5387326

	measure CCC = [DSO] + [DIO] - [DPO]
		formatString: 0.0
		lineageTag: a97de733-e246-4d0c-be4e-c5b9de2103a2

	measure 'Debt Balance' = CALCULATE ( SUM ( Debt[closing_balance] ), LASTDATE ( Calendar[month] ) )
		formatString: #,0,,.0 M
		lineageTag: f25532b8-978d-4316-b538-894d4063e3f3

	measure 'Covenant Headroom' = CALCULATE ( SUM ( Debt[covenant_headroom] ), LASTDATE ( Calendar[month] ) )
		formatString: #,0,,.0 M
		lineageTag: 395f59f8-8f6a-444c-9ca3-766927cd982d

	measure 'Sales Rows' = COUNTROWS ( Sales )
		formatString: #,0
		lineageTag: 51988cfc-23a4-497f-a855-3e02df2687b1

	measure 'Product Rows' = COUNTROWS ( Product )
		formatString: #,0
		lineageTag: a127b9cd-0bf2-4298-86f3-0ec7485fd5be

	measure 'Customer Rows' = COUNTROWS ( Customer )
		formatString: #,0
		lineageTag: e4437908-ec9c-4262-b228-a49c96933d3a

	measure 'Refresh Timestamp' = NOW ()
		formatString: yyyy-mm-dd hh:mm:ss
		lineageTag: c9b7a100-a9bf-4c6a-8e9d-12dcf1621e76

	measure 'Selected Scenario' = SELECTEDVALUE ( 'Scenario Selector'[scenario], "Actual" )
		formatString: @
		lineageTag: 6e3a4e70-9fa4-488b-8387-57f492e7a059

	measure 'Scenario Revenue' = VAR Scenario = [Selected Scenario]
VAR BaseCase = COALESCE ( CALCULATE ( SELECTEDVALUE ( 'Scenario Selector'[base_case] ), 'Scenario Selector'[scenario] = Scenario ), "Actual" )
VAR BaseRevenue = SWITCH ( BaseCase, "Budget", [Budget Revenue], "Forecast", [Forecast Revenue], [Net Revenue] )
VAR Multiplier = COALESCE ( CALCULATE ( MAX ( 'Scenario Selector'[revenue_multiplier] ), 'Scenario Selector'[scenario] = Scenario ), 1 )
RETURN BaseRevenue * Multiplier
		formatString: #,0,,.0 M
		lineageTag: 205ba0d0-adb1-4fbd-966a-80ca359977f9

	measure 'EBITDA Proxy' = VAR Scenario = [Selected Scenario]
VAR BaseCase = COALESCE ( CALCULATE ( SELECTEDVALUE ( 'Scenario Selector'[base_case] ), 'Scenario Selector'[scenario] = Scenario ), "Actual" )
VAR BaseCOGS = SWITCH ( BaseCase, "Budget", SUM ( Budget[budget_cogs] ), "Forecast", SUM ( Forecast[forecast_cogs] ), [COGS Total] )
VAR BaseOPEX = SWITCH ( BaseCase, "Budget", [OPEX Budget], "Forecast", [OPEX Forecast], [OPEX Actual] )
VAR COGSMultiplier = COALESCE ( CALCULATE ( MAX ( 'Scenario Selector'[cogs_multiplier] ), 'Scenario Selector'[scenario] = Scenario ), 1 )
VAR OPEXMultiplier = COALESCE ( CALCULATE ( MAX ( 'Scenario Selector'[opex_multiplier] ), 'Scenario Selector'[scenario] = Scenario ), 1 )
RETURN [Scenario Revenue] - BaseCOGS * COGSMultiplier - BaseOPEX * OPEXMultiplier
		formatString: #,0,,.0 M
		lineageTag: 4a17f0a1-e82c-4a21-a154-949d60ebac39

	measure 'OPEX Actual' = SUM ( OPEX_Headcount[opex_actual_vnd] )
		formatString: #,0,,.0 M
		lineageTag: 0d68c8e7-bb6c-499d-8590-ebe7b845218f

	measure 'OPEX Budget' = SUM ( OPEX_Headcount[opex_budget_vnd] )
		formatString: #,0,,.0 M
		lineageTag: 7b5ab70c-d18b-4941-a5b7-fe9533fa562f

	measure 'OPEX Forecast' = SUM ( OPEX_Headcount[opex_forecast_vnd] )
		formatString: #,0,,.0 M
		lineageTag: ca95cec4-8d5a-4278-9815-d0ae6a1df132

	measure 'OPEX vs Budget' = [OPEX Actual] - [OPEX Budget]
		formatString: #,0,,.0 M;(#,0,,.0 M)
		lineageTag: 241055f2-8592-4b43-a22b-16ed02aa1f75

	measure 'OPEX vs Forecast' = [OPEX Actual] - [OPEX Forecast]
		formatString: #,0,,.0 M;(#,0,,.0 M)
		lineageTag: 519126a5-5229-4aff-a995-5651c57f9ba4

	measure 'Average Headcount' = SUM ( OPEX_Headcount[avg_headcount] )
		formatString: #,0.0
		lineageTag: f9b7e36f-0eff-4992-90f0-5ce2adb324ec

	measure 'CAPEX Budget' = SUM ( CAPEX_Projects[budget_capex_vnd] )
		formatString: #,0,,.0 M
		lineageTag: bbdc60bb-5d66-4fbf-822f-80bbe39e2df6

	measure 'CAPEX Actual' = SUM ( CAPEX_Projects[actual_capex_vnd] )
		formatString: #,0,,.0 M
		lineageTag: 8ddf39ff-ff83-492e-9ac4-01fb5549e4e0

	measure 'CAPEX Forecast' = SUM ( CAPEX_Projects[forecast_capex_vnd] )
		formatString: #,0,,.0 M
		lineageTag: 6a1a4f65-fd5a-4d50-847e-94bd53d1c51f

	measure 'CAPEX Committed' = SUM ( CAPEX_Projects[committed_capex_vnd] )
		formatString: #,0,,.0 M
		lineageTag: 36ddc263-7e56-4b4d-b115-487e5af0d80c

	measure 'CAPEX Cash Payment' = SUM ( CAPEX_Projects[cash_payment_vnd] )
		formatString: #,0,,.0 M
		lineageTag: b7e013b7-b0e7-4646-a66f-0a3faa517b37

	measure 'CAPEX Depreciation' = SUM ( CAPEX_Projects[depreciation_vnd] )
		formatString: #,0,,.0 M
		lineageTag: 5f40808a-7295-440d-af22-19667e193d9c

	measure 'CAPEX Annual Benefit' = SUM ( CAPEX_Projects[expected_annual_contribution_vnd] )
		formatString: #,0,,.0 M
		lineageTag: f7fbf9b0-3dd1-4c64-8f86-cd076136d018

	measure 'CAPEX Payback Months' = AVERAGE ( CAPEX_Projects[payback_months] )
		formatString: 0.0
		lineageTag: be92eb6a-08e7-4ba9-8cbd-68144d8e2358

	measure 'CAPEX vs Budget' = [CAPEX Actual] - [CAPEX Budget]
		formatString: #,0,,.0 M;(#,0,,.0 M)
		lineageTag: fe08e564-a2d2-4eea-9fda-49ac7ad9e4db

	measure 'Approved Peer Rows' = COUNTROWS ( Peer_Benchmark )
		formatString: #,0
		lineageTag: 1161f6ae-4175-4ccd-9a6b-0af988c1e62c

	measure 'Peer Revenue' = SUM ( Peer_Benchmark[net_revenue_vnd_bn] )
		formatString: #,0.0
		lineageTag: 377c5ef0-ec41-465d-a861-9b99305696b6

	measure 'Peer PAT Margin' = DIVIDE ( SUM ( Peer_Benchmark[profit_after_tax_vnd_bn] ), SUM ( Peer_Benchmark[net_revenue_vnd_bn] ) )
		formatString: 0.0%
		lineageTag: 0cd9ff4b-af77-4667-9ea6-4ee48b7d680c

	measure 'Peer CFO Conversion' = DIVIDE ( SUM ( Peer_Benchmark[operating_cash_flow_vnd_bn] ), SUM ( Peer_Benchmark[profit_after_tax_vnd_bn] ) )
		formatString: 0.0x
		lineageTag: 31c06e51-67af-48db-a4f5-6d93b2dbdfab

	measure 'Peer Review Queue Rows' = COUNTROWS ( Peer_Review_Queue )
		formatString: #,0
		lineageTag: 0c1e7fcc-f457-451a-b755-0bf537aa0663

	column line_id
		dataType: string
		isKey
		summarizeBy: none
		sourceColumn: line_id
		lineageTag: 26c892fa-2182-4bbe-9734-0d02d05f3748
		annotation SummarizationSetBy = User

	column order_id
		dataType: string
		summarizeBy: none
		sourceColumn: order_id
		lineageTag: b5249b39-efd6-4c3f-90ac-247547c0344e
		annotation SummarizationSetBy = User

	column date
		dataType: dateTime
		summarizeBy: none
		sourceColumn: date
		lineageTag: 3aa1be27-e075-4ef1-8449-45f820237558
		annotation SummarizationSetBy = User

	column month
		dataType: dateTime
		summarizeBy: none
		sourceColumn: month
		lineageTag: ca2e0b1f-af88-40b9-9f5f-da6e0e83efb9
		annotation SummarizationSetBy = User

	column sku_id
		dataType: string
		summarizeBy: none
		sourceColumn: sku_id
		lineageTag: fd7d0ff6-6106-4bec-b6fc-ccc72e7da86f
		annotation SummarizationSetBy = User

	column customer_id
		dataType: string
		summarizeBy: none
		sourceColumn: customer_id
		lineageTag: fc3f85f7-5886-4f45-8ad8-c56673857df9
		annotation SummarizationSetBy = User

	column channel_id
		dataType: string
		summarizeBy: none
		sourceColumn: channel_id
		lineageTag: 7a478e6d-b97a-4763-9464-402df8c3fa41
		annotation SummarizationSetBy = User

	column region
		dataType: string
		summarizeBy: none
		sourceColumn: region
		lineageTag: 8d7a5d36-fb47-4065-95b9-498ef7ed7717
		annotation SummarizationSetBy = User

	column units
		dataType: int64
		summarizeBy: sum
		sourceColumn: units
		lineageTag: c87730fb-a82c-467b-bd48-fabc23465749
		annotation SummarizationSetBy = User

	column gross_sales
		dataType: double
		summarizeBy: sum
		sourceColumn: gross_sales
		lineageTag: 85fb11af-61d1-488d-b49f-c600504ab80e
		annotation SummarizationSetBy = User

	column discount
		dataType: double
		summarizeBy: sum
		sourceColumn: discount
		lineageTag: b8f25fb1-c7bb-42a8-86e6-ff00b37108c2
		annotation SummarizationSetBy = User

	column returns
		dataType: double
		summarizeBy: sum
		sourceColumn: returns
		lineageTag: c60fff49-8c52-49ac-8860-e74674076f42
		annotation SummarizationSetBy = User

	column net_sales
		dataType: double
		summarizeBy: sum
		sourceColumn: net_sales
		lineageTag: 0394ad0d-1eac-4301-8889-a4728aaf84d6
		annotation SummarizationSetBy = User

	column cogs
		dataType: double
		summarizeBy: sum
		sourceColumn: cogs
		lineageTag: 994066e2-dd86-4d71-8a72-07b42d14ecff
		annotation SummarizationSetBy = User

	column freight
		dataType: double
		summarizeBy: sum
		sourceColumn: freight
		lineageTag: e8851c7d-f433-4499-b0b1-55e0c45ed864
		annotation SummarizationSetBy = User

	column payment_fee
		dataType: double
		summarizeBy: sum
		sourceColumn: payment_fee
		lineageTag: 72caaad8-2acb-49ed-a779-c9f04a19971a
		annotation SummarizationSetBy = User

	column commission
		dataType: double
		summarizeBy: sum
		sourceColumn: commission
		lineageTag: 9800d5a7-5bdd-4735-b9e6-352056b0dc47
		annotation SummarizationSetBy = User

	column trade_spend
		dataType: double
		summarizeBy: sum
		sourceColumn: trade_spend
		lineageTag: 57022d05-c982-4b2f-833e-d51e87e672ae
		annotation SummarizationSetBy = User

	column contribution_margin
		dataType: double
		summarizeBy: sum
		sourceColumn: contribution_margin
		lineageTag: 4721589f-0460-44bc-8637-4c8b10f1e0af
		annotation SummarizationSetBy = User

	column promo_id
		dataType: string
		summarizeBy: none
		sourceColumn: promo_id
		lineageTag: 1ae8857e-b203-46de-85ee-6cfeb46acb2c
		annotation SummarizationSetBy = User

	column is_stockout
		dataType: boolean
		summarizeBy: none
		sourceColumn: is_stockout
		lineageTag: 5bbd75c5-a5bd-48b0-b796-76f8b8a5e878
		annotation SummarizationSetBy = User

	column is_intercompany
		dataType: boolean
		summarizeBy: none
		sourceColumn: is_intercompany
		lineageTag: 0e47c7eb-8ac4-44e8-831d-f250bc660326
		annotation SummarizationSetBy = User

	partition Sales = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\sales_fact.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"line_id", type text}, {"order_id", type text}, {"date", type date}, {"month", type date}, {"sku_id", type text}, {"customer_id", type text}, {"channel_id", type text}, {"region", type text}, {"units", Int64.Type}, {"gross_sales", type number}, {"discount", type number}, {"returns", type number}, {"net_sales", type number}, {"cogs", type number}, {"freight", type number}, {"payment_fee", type number}, {"commission", type number}, {"trade_spend", type number}, {"contribution_margin", type number}, {"promo_id", type text}, {"is_stockout", type logical}, {"is_intercompany", type logical}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
