table Sales
	lineageTag: 13f57ec1-c6fa-420c-a0b4-39e57927a6bf

	measure 'Net Revenue' = SUM ( Sales[net_sales] )
		formatString: #,0,,.0 M
		lineageTag: a34d4951-db87-4947-a3ba-4942e9489095

	measure 'Gross Sales' = SUM ( Sales[gross_sales] )
		formatString: #,0,,.0 M
		lineageTag: f5bb16d9-7667-4621-94f2-5244f283556a

	measure 'COGS Total' = SUM ( Sales[cogs] )
		formatString: #,0,,.0 M
		lineageTag: a2fc83bb-b1ff-4ea3-8347-2e767312d514

	measure 'Gross Profit' = [Net Revenue] - [COGS Total]
		formatString: #,0,,.0 M
		lineageTag: c719baa5-81b3-45d2-8fae-61cf0ef599c8

	measure 'Gross Margin %' = DIVIDE ( [Gross Profit], [Net Revenue] )
		formatString: 0.0%
		lineageTag: c6cd6333-5c9d-4df2-84d0-62242b9c6b2b

	measure 'Contribution Margin' = SUM ( Sales[contribution_margin] )
		formatString: #,0,,.0 M
		lineageTag: b45c029c-0500-4944-b9ea-ea46e3703ce0

	measure 'Contribution Margin %' = DIVIDE ( [Contribution Margin], [Net Revenue] )
		formatString: 0.0%
		lineageTag: e988e5e5-0dee-4a96-8bfc-e58650f7c81c

	measure 'Units Total' = SUM ( Sales[units] )
		formatString: #,0
		lineageTag: d63035c1-6f4c-4615-a99b-3f2656619e49

	measure ASP = DIVIDE ( [Net Revenue], [Units Total] )
		formatString: #,0
		lineageTag: dfaf8212-7867-4068-9d6a-18db53acea29

	measure 'Budget Revenue' = SUM ( Budget[budget_net_sales] )
		formatString: #,0,,.0 M
		lineageTag: 8f817ebd-568f-4fe0-8317-4ebe5c58c30b

	measure 'Forecast Revenue' = SUM ( Forecast[forecast_net_sales] )
		formatString: #,0,,.0 M
		lineageTag: 6de30402-f820-47d7-9ef9-d4305d871846

	measure 'Revenue vs Budget' = [Net Revenue] - [Budget Revenue]
		formatString: #,0,,.0 M;(#,0,,.0 M)
		lineageTag: 9cb22691-35ac-47c0-b183-38752120407a

	measure 'Revenue vs Budget %' = DIVIDE ( [Revenue vs Budget], [Budget Revenue] )
		formatString: 0.0%;(0.0%)
		lineageTag: 792656c4-8da0-4daf-8099-d04640073df9

	measure 'Revenue vs Forecast' = [Net Revenue] - [Forecast Revenue]
		formatString: #,0,,.0 M;(#,0,,.0 M)
		lineageTag: d0cba95f-fa93-4ebc-a11a-b02c350bc32c

	measure 'Revenue vs Forecast %' = DIVIDE ( [Revenue vs Forecast], [Forecast Revenue] )
		formatString: 0.0%;(0.0%)
		lineageTag: 5000c5cd-74a4-4221-a9d6-9ff7dffb9e6d

	measure 'Prior Net Revenue' = CALCULATE ( [Net Revenue], DATEADD ( Calendar[month], -1, MONTH ) )
		formatString: #,0,,.0 M
		lineageTag: fce560f5-810d-46cd-83b0-ab57341900ae

	measure 'Revenue Growth %' = DIVIDE ( [Net Revenue] - [Prior Net Revenue], [Prior Net Revenue] )
		formatString: 0.0%;(0.0%)
		lineageTag: d0e7d4c2-17fe-4032-84d8-dee70c15d48c

	measure 'Prior Units' = CALCULATE ( [Units Total], DATEADD ( Calendar[month], -1, MONTH ) )
		formatString: #,0
		lineageTag: ac2b5ab3-74e2-42d0-9c95-dd20f3885aaf

	measure 'Prior ASP' = CALCULATE ( [ASP], DATEADD ( Calendar[month], -1, MONTH ) )
		formatString: #,0
		lineageTag: a06daa85-5789-4bc8-99ac-fd628ebcb0f7

	measure 'Price Impact' = ( [ASP] - [Prior ASP] ) * [Units Total]
		formatString: #,0,,.0 M;(#,0,,.0 M)
		lineageTag: c5f4b197-ac45-488b-9b10-52f0435349c2

	measure 'Volume Impact' = ( [Units Total] - [Prior Units] ) * [Prior ASP]
		formatString: #,0,,.0 M;(#,0,,.0 M)
		lineageTag: 75e8b6bd-7f25-4a7a-8c31-c0bffbade26c

	measure 'Mix Other Impact' = [Net Revenue] - [Prior Net Revenue] - [Price Impact] - [Volume Impact]
		formatString: #,0,,.0 M;(#,0,,.0 M)
		lineageTag: 9ad214cc-fb72-40bc-986a-552d896d8bbd

	measure 'Trade Spend' = SUM ( Commercial_Costs[trade_spend] )
		formatString: #,0,,.0 M
		lineageTag: b9ee72f8-9c69-477e-b249-27beaaaad935

	measure 'Marketing Spend' = SUM ( Marketing[spend] )
		formatString: #,0,,.0 M
		lineageTag: 93a55a4b-4bc0-48a6-a42f-e9736e830bf8

	measure 'Ending AR' = CALCULATE ( SUM ( Receivables[closing_ar] ), LASTDATE ( Calendar[month] ) )
		formatString: #,0,,.0 M
		lineageTag: 840f8a31-8324-404c-986d-b0b2a914d503

	measure 'Ending Inventory' = CALCULATE ( SUM ( Inventory[inventory_value] ), LASTDATE ( Calendar[month] ) )
		formatString: #,0,,.0 M
		lineageTag: ddffdd72-e60a-4d46-b4b6-ee188deecb7b

	measure 'Ending AP' = CALCULATE ( SUM ( Payables[closing_ap] ), LASTDATE ( Calendar[month] ) )
		formatString: #,0,,.0 M
		lineageTag: 58255a0c-dede-4e9a-ac77-33efbb273f06

	measure DSO = CALCULATE ( AVERAGE ( Receivables[dso] ), LASTDATE ( Calendar[month] ) )
		formatString: 0.0
		lineageTag: 0e6c5fa9-29b2-4a24-9efb-db356e979f11

	measure DIO = CALCULATE ( AVERAGE ( Inventory[days_on_hand] ), LASTDATE ( Calendar[month] ) )
		formatString: 0.0
		lineageTag: 6b229e3c-dbea-420c-aff7-7f9f5a3f947a

	measure DPO = CALCULATE ( AVERAGE ( Payables[dpo] ), LASTDATE ( Calendar[month] ) )
		formatString: 0.0
		lineageTag: d193f8ef-01d6-44a3-865e-8a00dc4e2fb2

	measure CCC = VAR Scenario = [Selected Scenario]
VAR WorkingCapitalDelta = COALESCE ( CALCULATE ( MAX ( 'Scenario Selector'[working_capital_days_delta] ), 'Scenario Selector'[scenario] = Scenario ), 0 )
RETURN [DSO] + [DIO] - [DPO] + WorkingCapitalDelta
		formatString: 0.0
		lineageTag: 8cafac25-a13b-49ce-bab3-342eceb0e906

	measure 'Debt Balance' = CALCULATE ( SUM ( Debt[closing_balance] ), LASTDATE ( Calendar[month] ) )
		formatString: #,0,,.0 M
		lineageTag: 5b1790cd-2df5-4db8-a642-f5daf4b5b83e

	measure 'Covenant Headroom' = CALCULATE ( SUM ( Debt[covenant_headroom] ), LASTDATE ( Calendar[month] ) )
		formatString: #,0,,.0 M
		lineageTag: 1e5f9971-209e-4a83-8b59-0c5982ebb1c3

	measure 'Sales Rows' = COUNTROWS ( Sales )
		formatString: #,0
		lineageTag: a24473be-53f2-4bc0-9442-0d58c515a857

	measure 'Product Rows' = COUNTROWS ( Product )
		formatString: #,0
		lineageTag: ed7d1b8f-9652-454e-b5bc-51e271e46add

	measure 'Customer Rows' = COUNTROWS ( Customer )
		formatString: #,0
		lineageTag: dc26dbb1-19dd-459b-8f89-71895c46926f

	measure 'Refresh Timestamp' = NOW ()
		formatString: yyyy-mm-dd hh:mm:ss
		lineageTag: ec5c4651-269e-4855-88d6-f35d78dab989

	measure 'Selected Scenario' = SELECTEDVALUE ( 'Scenario Selector'[scenario], "Actual" )
		formatString: @
		lineageTag: 1fa7be0e-5509-4664-995e-18734fbe04f9

	measure 'Scenario Revenue' = VAR Scenario = [Selected Scenario]
VAR BaseCase = COALESCE ( CALCULATE ( SELECTEDVALUE ( 'Scenario Selector'[base_case] ), 'Scenario Selector'[scenario] = Scenario ), "Actual" )
VAR BaseRevenue = SWITCH ( BaseCase, "Budget", [Budget Revenue], "Forecast", [Forecast Revenue], [Net Revenue] )
VAR Multiplier = COALESCE ( CALCULATE ( MAX ( 'Scenario Selector'[revenue_multiplier] ), 'Scenario Selector'[scenario] = Scenario ), 1 )
RETURN BaseRevenue * Multiplier
		formatString: #,0,,.0 M
		lineageTag: 9efefaed-3bcc-4e78-b46d-50329c42d6b3

	measure 'EBITDA Proxy' = VAR Scenario = [Selected Scenario]
VAR BaseCase = COALESCE ( CALCULATE ( SELECTEDVALUE ( 'Scenario Selector'[base_case] ), 'Scenario Selector'[scenario] = Scenario ), "Actual" )
VAR BaseCOGS = SWITCH ( BaseCase, "Budget", SUM ( Budget[budget_cogs] ), "Forecast", SUM ( Forecast[forecast_cogs] ), [COGS Total] )
VAR BaseOPEX = SWITCH ( BaseCase, "Budget", [OPEX Budget], "Forecast", [OPEX Forecast], [OPEX Actual] )
VAR COGSMultiplier = COALESCE ( CALCULATE ( MAX ( 'Scenario Selector'[cogs_multiplier] ), 'Scenario Selector'[scenario] = Scenario ), 1 )
VAR OPEXMultiplier = COALESCE ( CALCULATE ( MAX ( 'Scenario Selector'[opex_multiplier] ), 'Scenario Selector'[scenario] = Scenario ), 1 )
RETURN [Scenario Revenue] - BaseCOGS * COGSMultiplier - BaseOPEX * OPEXMultiplier
		formatString: #,0,,.0 M
		lineageTag: 70d8cd86-5f4f-49c0-98aa-f0b24341de2f

	measure 'OPEX Actual' = SUM ( OPEX_Headcount[opex_actual_vnd] )
		formatString: #,0,,.0 M
		lineageTag: 9b2f0c67-bd08-4736-bf55-6df585460389

	measure 'OPEX Budget' = SUM ( OPEX_Headcount[opex_budget_vnd] )
		formatString: #,0,,.0 M
		lineageTag: 973948b2-64a9-4c56-b941-769286e5d1bd

	measure 'OPEX Forecast' = SUM ( OPEX_Headcount[opex_forecast_vnd] )
		formatString: #,0,,.0 M
		lineageTag: 3f74c483-9d48-48ee-bb87-e7746ddb3d18

	measure 'OPEX vs Budget' = [OPEX Actual] - [OPEX Budget]
		formatString: #,0,,.0 M;(#,0,,.0 M)
		lineageTag: 733021fa-de3b-4696-8699-185cef8b0be5

	measure 'OPEX vs Forecast' = [OPEX Actual] - [OPEX Forecast]
		formatString: #,0,,.0 M;(#,0,,.0 M)
		lineageTag: a9a10b78-fc34-444a-b845-c7d888d02e93

	measure 'Average Headcount' = SUM ( OPEX_Headcount[avg_headcount] )
		formatString: #,0.0
		lineageTag: 41a2055e-56c2-4f44-8bf2-30591ba2cc34

	measure 'CAPEX Budget' = SUM ( CAPEX_Projects[budget_capex_vnd] )
		formatString: #,0,,.0 M
		lineageTag: 5cfb3db8-d3b9-4ac9-a54a-7556aa778e52

	measure 'CAPEX Actual' = SUM ( CAPEX_Projects[actual_capex_vnd] )
		formatString: #,0,,.0 M
		lineageTag: 330f3e12-3459-4a49-bcaf-c97ad0dd53ad

	measure 'CAPEX Forecast' = SUM ( CAPEX_Projects[forecast_capex_vnd] )
		formatString: #,0,,.0 M
		lineageTag: adea84c7-82d3-4199-845c-c5b2381e8ddb

	measure 'CAPEX Committed' = SUM ( CAPEX_Projects[committed_capex_vnd] )
		formatString: #,0,,.0 M
		lineageTag: 944b4d61-5891-48e1-9875-9862078d6d01

	measure 'CAPEX Cash Payment' = SUM ( CAPEX_Projects[cash_payment_vnd] )
		formatString: #,0,,.0 M
		lineageTag: 2520f56f-8240-488e-822d-ac9a08a50e6f

	measure 'CAPEX Depreciation' = SUM ( CAPEX_Projects[depreciation_vnd] )
		formatString: #,0,,.0 M
		lineageTag: d63b7661-911f-4b22-8085-7764dc04a802

	measure 'CAPEX Annual Benefit' = SUM ( CAPEX_Projects[expected_annual_contribution_vnd] )
		formatString: #,0,,.0 M
		lineageTag: 6d953721-d370-4102-8ffa-62e0738ec04c

	measure 'CAPEX Payback Months' = AVERAGE ( CAPEX_Projects[payback_months] )
		formatString: 0.0
		lineageTag: 13371c87-6473-435f-8abc-f1ad1fdce0c2

	measure 'CAPEX vs Budget' = [CAPEX Actual] - [CAPEX Budget]
		formatString: #,0,,.0 M;(#,0,,.0 M)
		lineageTag: 2f3f6a1d-ceaf-4adc-9292-c1b3076933b1

	measure 'Approved Peer Rows' = COUNTROWS ( Peer_Benchmark )
		formatString: #,0
		lineageTag: 4d3a9fc5-dbed-4764-940c-a9b12e01ea37

	measure 'Peer Revenue' = SUM ( Peer_Benchmark[net_revenue_vnd_bn] )
		formatString: #,0.0
		lineageTag: 1e686031-ce1b-4e1a-b3ab-19a82b6e22df

	measure 'Peer PAT Margin' = DIVIDE ( SUM ( Peer_Benchmark[profit_after_tax_vnd_bn] ), SUM ( Peer_Benchmark[net_revenue_vnd_bn] ) )
		formatString: 0.0%
		lineageTag: e9857a9d-acef-4ed3-bf8b-42b1bb72934f

	measure 'Peer CFO Conversion' = DIVIDE ( SUM ( Peer_Benchmark[operating_cash_flow_vnd_bn] ), SUM ( Peer_Benchmark[profit_after_tax_vnd_bn] ) )
		formatString: 0.0x
		lineageTag: e82261c7-30fa-48e9-bbbe-c4e53d08e816

	measure 'Peer Review Queue Rows' = COUNTROWS ( Peer_Review_Queue )
		formatString: #,0
		lineageTag: c5e9aa54-d43a-4c90-af3c-557123ef0536

	column line_id
		dataType: string
		isKey
		summarizeBy: none
		sourceColumn: line_id
		lineageTag: bc4a1af9-9f25-4041-930e-a0afeba01c94
		annotation SummarizationSetBy = User

	column order_id
		dataType: string
		summarizeBy: none
		sourceColumn: order_id
		lineageTag: 28268be7-c4b2-4d26-9414-b74557e1b4e4
		annotation SummarizationSetBy = User

	column date
		dataType: dateTime
		summarizeBy: none
		sourceColumn: date
		lineageTag: 68cbb621-804d-4739-9825-ce944975c0ad
		annotation SummarizationSetBy = User

	column month
		dataType: dateTime
		summarizeBy: none
		sourceColumn: month
		lineageTag: bdbffade-2e00-41d2-b0c6-e10245205066
		annotation SummarizationSetBy = User

	column sku_id
		dataType: string
		summarizeBy: none
		sourceColumn: sku_id
		lineageTag: 31fc48c8-4ac3-40cc-b4e6-ccab81cc578e
		annotation SummarizationSetBy = User

	column customer_id
		dataType: string
		summarizeBy: none
		sourceColumn: customer_id
		lineageTag: 60041fa4-498e-4117-8494-ac6baa6997ba
		annotation SummarizationSetBy = User

	column channel_id
		dataType: string
		summarizeBy: none
		sourceColumn: channel_id
		lineageTag: 72865f61-fe21-4202-be1a-abed27619597
		annotation SummarizationSetBy = User

	column region
		dataType: string
		summarizeBy: none
		sourceColumn: region
		lineageTag: 5f3fd4d2-25cf-4076-87f7-d6c061991a8f
		annotation SummarizationSetBy = User

	column units
		dataType: int64
		summarizeBy: sum
		sourceColumn: units
		lineageTag: c1669f31-61de-44d2-bb13-575528d39cf5
		annotation SummarizationSetBy = User

	column gross_sales
		dataType: double
		summarizeBy: sum
		sourceColumn: gross_sales
		lineageTag: 496207b3-9bb8-4439-bc05-7c7e89014e33
		annotation SummarizationSetBy = User

	column discount
		dataType: double
		summarizeBy: sum
		sourceColumn: discount
		lineageTag: 88bd124c-4a68-496e-8fc1-f0a4440503c0
		annotation SummarizationSetBy = User

	column returns
		dataType: double
		summarizeBy: sum
		sourceColumn: returns
		lineageTag: 849d35ac-cc1c-4fb6-ab06-4dab3a9f7e89
		annotation SummarizationSetBy = User

	column net_sales
		dataType: double
		summarizeBy: sum
		sourceColumn: net_sales
		lineageTag: 2c1b7773-0628-4a3e-b031-7190f91a29ff
		annotation SummarizationSetBy = User

	column cogs
		dataType: double
		summarizeBy: sum
		sourceColumn: cogs
		lineageTag: 814bdfe9-f29d-4782-8712-3b31a976dc61
		annotation SummarizationSetBy = User

	column freight
		dataType: double
		summarizeBy: sum
		sourceColumn: freight
		lineageTag: 9190a961-ea93-407b-bd27-5ecaa5b06520
		annotation SummarizationSetBy = User

	column payment_fee
		dataType: double
		summarizeBy: sum
		sourceColumn: payment_fee
		lineageTag: 00279ca7-3a6d-4590-9046-6055640149c7
		annotation SummarizationSetBy = User

	column commission
		dataType: double
		summarizeBy: sum
		sourceColumn: commission
		lineageTag: fa07424d-037f-4e44-99ab-719db9106378
		annotation SummarizationSetBy = User

	column trade_spend
		dataType: double
		summarizeBy: sum
		sourceColumn: trade_spend
		lineageTag: 25cdc6cd-8572-4961-9708-774ee541fc22
		annotation SummarizationSetBy = User

	column contribution_margin
		dataType: double
		summarizeBy: sum
		sourceColumn: contribution_margin
		lineageTag: 34c07aa0-1c1e-49dc-b804-eb8dda19b764
		annotation SummarizationSetBy = User

	column promo_id
		dataType: string
		summarizeBy: none
		sourceColumn: promo_id
		lineageTag: 4ee220f1-b135-4a46-8a78-7782375c7724
		annotation SummarizationSetBy = User

	column is_stockout
		dataType: boolean
		summarizeBy: none
		sourceColumn: is_stockout
		lineageTag: b9cc79ba-f970-49e7-aa42-86937d3305df
		annotation SummarizationSetBy = User

	column is_intercompany
		dataType: boolean
		summarizeBy: none
		sourceColumn: is_intercompany
		lineageTag: 9e542607-646b-45f3-a096-577e9d25b3f6
		annotation SummarizationSetBy = User

	partition Sales = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\sales_fact.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"line_id", type text}, {"order_id", type text}, {"date", type date}, {"month", type date}, {"sku_id", type text}, {"customer_id", type text}, {"channel_id", type text}, {"region", type text}, {"units", Int64.Type}, {"gross_sales", type number}, {"discount", type number}, {"returns", type number}, {"net_sales", type number}, {"cogs", type number}, {"freight", type number}, {"payment_fee", type number}, {"commission", type number}, {"trade_spend", type number}, {"contribution_margin", type number}, {"promo_id", type text}, {"is_stockout", type logical}, {"is_intercompany", type logical}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
