table 'Scenario Selector'
	lineageTag: 96050259-c9f3-468e-8847-05cfa949c8e1

	column scenario
		dataType: string
		isKey
		summarizeBy: none
		sourceColumn: scenario
		lineageTag: be0e131f-4cb2-4213-bf98-ebb44c2a35e2
		annotation SummarizationSetBy = User

	column base_case
		dataType: string
		summarizeBy: none
		sourceColumn: base_case
		lineageTag: b1e73700-4b5c-4fbb-a58b-a40053f9e0f2
		annotation SummarizationSetBy = User

	column revenue_multiplier
		dataType: double
		summarizeBy: none
		sourceColumn: revenue_multiplier
		lineageTag: b0f00c73-9872-4d76-949f-258a181f1640
		annotation SummarizationSetBy = User

	column cogs_multiplier
		dataType: double
		summarizeBy: none
		sourceColumn: cogs_multiplier
		lineageTag: 8460d07f-19c3-4bc3-a1af-f8fcbcab0535
		annotation SummarizationSetBy = User

	column opex_multiplier
		dataType: double
		summarizeBy: none
		sourceColumn: opex_multiplier
		lineageTag: 5d719217-1c1a-4471-b275-cc0dbf410400
		annotation SummarizationSetBy = User

	column working_capital_days_delta
		dataType: double
		summarizeBy: none
		sourceColumn: working_capital_days_delta
		lineageTag: 6cd6042f-d13c-449b-a17c-b8f5f9e5f8d0
		annotation SummarizationSetBy = User

	column scenario_note
		dataType: string
		summarizeBy: none
		sourceColumn: scenario_note
		lineageTag: 0ab594ea-12d9-41f8-bc53-954d9af6268d
		annotation SummarizationSetBy = User

	partition 'Scenario Selector' = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\scenario_selector.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"scenario", type text}, {"base_case", type text}, {"revenue_multiplier", type number}, {"cogs_multiplier", type number}, {"opex_multiplier", type number}, {"working_capital_days_delta", type number}, {"scenario_note", type text}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
