table Source_Control
	lineageTag: 020b54b2-88af-4734-9149-44681e407e93

	column control_id
		dataType: string
		isKey
		summarizeBy: none
		sourceColumn: control_id
		lineageTag: 7a596fc2-e49e-4fbb-91bf-fbaf83d4415b
		annotation SummarizationSetBy = User

	column control_name
		dataType: string
		summarizeBy: none
		sourceColumn: control_name
		lineageTag: b3bc4915-fe16-4b52-aff5-93c82f926933
		annotation SummarizationSetBy = User

	column status
		dataType: string
		summarizeBy: none
		sourceColumn: status
		lineageTag: d1983133-77ad-43dc-a6e2-d47c18b10895
		annotation SummarizationSetBy = User

	column evidence_class
		dataType: string
		summarizeBy: none
		sourceColumn: evidence_class
		lineageTag: 3618626b-b814-409e-bb79-4a0a973f7e5c
		annotation SummarizationSetBy = User

	column source_file
		dataType: string
		summarizeBy: none
		sourceColumn: source_file
		lineageTag: bdc6d963-9d40-49be-b555-defb87182cba
		annotation SummarizationSetBy = User

	partition Source_Control = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\source_control.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"control_id", type text}, {"control_name", type text}, {"status", type text}, {"evidence_class", type text}, {"source_file", type text}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
