table Source_Control
	lineageTag: 2b744a85-5d17-45a3-8f15-cfaa691a8236

	column control_id
		dataType: string
		isKey
		summarizeBy: none
		sourceColumn: control_id
		lineageTag: 3fae44b0-8170-42cb-bb5f-60e66a368f8b
		annotation SummarizationSetBy = User

	column control_name
		dataType: string
		summarizeBy: none
		sourceColumn: control_name
		lineageTag: 4f87e815-0029-4917-bfd3-bfa6e0d66c20
		annotation SummarizationSetBy = User

	column status
		dataType: string
		summarizeBy: none
		sourceColumn: status
		lineageTag: 6b11bed1-e73c-4629-ba8b-0b70d155e84e
		annotation SummarizationSetBy = User

	column evidence_class
		dataType: string
		summarizeBy: none
		sourceColumn: evidence_class
		lineageTag: 9503dc8c-ee18-4957-9685-6f6e86890e37
		annotation SummarizationSetBy = User

	column source_file
		dataType: string
		summarizeBy: none
		sourceColumn: source_file
		lineageTag: ce8bff8f-5629-4f43-93e0-f6d7bc59bc53
		annotation SummarizationSetBy = User

	partition Source_Control = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\source_control.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"control_id", type text}, {"control_name", type text}, {"status", type text}, {"evidence_class", type text}, {"source_file", type text}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
