import fs from "node:fs/promises";
import { Workbook, SpreadsheetFile } from "@oai/artifact-tool";

const outDir = "C:/Users/sangk/Documents/Codex/2026-08-29/toi/outputs/fpa_v2";
await fs.mkdir(outDir, { recursive: true });
const wb = Workbook.create();
const sheetNames = ["Cover_Control","ReadMe","Source_Register","Assumptions","Calendar","Product_Master","Customer_Master","Channel_Master","Sales_Fact","Commercial_Costs","Inventory","AR","AP","Debt_Liquidity","Budget","Forecast_Versions","PnL","Variance_Bridge","PVM","Product_Profitability","Channel_Customer","Promotion_Pricing","Working_Capital","Scenario_MonteCarlo","Budget_Allocation","Peer_Benchmark","Checks","Executive_Output"];
const s = {}; for (const n of sheetNames) s[n] = wb.worksheets.add(n); for (const ws of Object.values(s)) ws.showGridLines = false;
const navy="#17365D", blue="#D9EAF7", gray="#F2F2F2", yellow="#FFF2CC", green="#E2F0D9";
function title(ws,text,end="J"){ws.mergeCells("A1:"+end+"1");ws.getRange("A1").values=[[text]];ws.getRange("A1:"+end+"1").format={fill:navy,font:{bold:true,color:"#FFFFFF",size:15},verticalAlignment:"center"};ws.getRange("A1:"+end+"1").format.rowHeight=28;}
function hdr(ws,r){ws.getRange(r).format={fill:navy,font:{bold:true,color:"#FFFFFF"},horizontalAlignment:"center",wrapText:true};}
function money(ws,r){ws.getRange(r).setNumberFormat("#,##0;[Red](#,##0);-");}
function pct(ws,r){ws.getRange(r).setNumberFormat("0.0%;[Red](0.0%);-");}
function num(ws,r){ws.getRange(r).setNumberFormat("#,##0.0;[Red](#,##0.0);-");}
function col(ws,c,w){ws.getRange(c+":"+c).format.columnWidth=w;}
function excelDate(y,m){return new Date(Date.UTC(y,m-1,1));}
const months=[];for(let i=0;i<36;i++){const y=2023+Math.floor(i/12),m=i%12+1;months.push(excelDate(y,m));}
const channels=[["CH01","General Trade",0.035,30],["CH02","Modern Trade",0.045,45],["CH03","Marketplace",0.120,15],["CH04","D2C",0.080,7],["CH05","Wholesale",0.020,60]];
const products=[["SKU001","VietSpice Original","Seasonings",31000,0.40],["SKU002","VietSpice Premium","Seasonings",36000,0.36],["SKU003","VietSpice Chili","Seasonings",32000,0.38],["SKU004","QuickBowl Chicken","Convenience Foods",28000,0.44],["SKU005","QuickBowl Beef","Convenience Foods",27000,0.46],["SKU006","QuickBowl Veggie","Convenience Foods",30000,0.42],["SKU007","PulseUp Original","Beverages",23000,0.55],["SKU008","PulseUp Zero","Beverages",25000,0.52],["SKU009","PulseUp Energy","Beverages",21000,0.58],["SKU010","PulseUp Family","Beverages",24000,0.50],["SKU011","VietSpice Gift","Seasonings",35000,0.30],["SKU012","QuickBowl Family","Convenience Foods",29000,0.39]];
const customers=Array.from({length:10},(_,i)=>["CUS"+String(i+1).padStart(2,"0"),["Alpha Mart","Beta Retail","Gamma Foods","Delta Online","Epsilon Club","Zeta Wholesale","Eta Super","Theta Cafe","Iota Grocer","Kappa Direct"][i],i<5?"National":"Regional"]);
const actuals=[],sales=[],comm=[],inventory=[],ar=[],ap=[];
for(let i=0;i<36;i++){const season=[1,0.98,1.02,1.03,1.01,1,0.99,1.01,1.04,1.08,1.18,1.28][i%12],base=4.8e9*(1+0.012*i)*season;let rev=0,cogs=0;for(let c=0;c<5;c++){const ch=channels[c],share=[0.34,0.26,0.18,0.10,0.12][c],chRev=base*share*(1+(c===2?0.006*i:0)),chCogs=chRev*(0.62+(c===2?0.035:0)+(i>=18&&c===2?0.015:0)),fee=chRev*ch[2],trade=chRev*(0.025+(i%12===10?0.04:0)+(c===1?0.012:0));comm.push([months[i],ch[0],ch[1],chRev*(1-(0.04+(c===2?0.025:0)+(i%12===10?0.03:0))-(c===3?0.018:0.006)),chCogs,fee,trade,chRev-chCogs-fee-trade]);rev+=chRev;cogs+=chCogs;for(let p=0;p<12;p++){const prod=products[p],mix=[0.12,0.10,0.08,0.10,0.08,0.07,0.09,0.08,0.08,0.07,0.06,0.07][p],cust=customers[(i+c+p)%10],units=Math.round((chRev*mix/(prod[3]*100000))*100)/100,gross=units*prod[3]*100000,discount=gross*(0.04+(c===2?0.025:0)+(i%12===10?0.03:0)),returns=gross*(c===3?0.018:0.006),net=gross-discount-returns,lineCogs=units*prod[4]*100000;sales.push([months[i],prod[0],prod[1],prod[2],ch[0],ch[1],cust[0],cust[1],cust[2],units,gross,discount,returns,net,lineCogs]);}}const opex=rev*(0.175+(i>=24?0.005:0)),ocf=(rev-cogs-opex)*(0.92-(i%12===10?0.03:0));actuals.push([months[i],rev,cogs,opex,ocf]);inventory.push([months[i],cogs/30*(42+(i>=24?4:0)),cogs,rev*0.145]);ar.push([months[i],rev/30*(38+(i%12===5?9:0)),rev]);ap.push([months[i],cogs/30*(34+(i>=24?-4:0)),cogs]);}

title(s.Cover_Control,"VietNova Consumer JSC — Full Finance Analyst Model v2","K");s.Cover_Control.getRange("A3:B13").values=[["Purpose","End-to-end FP&A, commercial finance and corporate analyst case"],["Company","VietNova Consumer JSC (fictional)"],["Period","Jan-2023 to Dec-2025 synthetic actual-like ledger"],["Scenario","Selected in Assumptions!B5"],["Currency","VND; management pages should use VND million/billion"],["Evidence","Synthetic operating data; public peers are calibration only"],["Model flow","Drivers → facts → P&L → bridges → cash → decisions"],["Control gate","Checks!F12 must be PASS before publication"],["Version","v2.0; deterministic seed 20260829"],["Owner","Finance / Business Finance Analyst portfolio case"],["Storage","Remote-first: GitHub source + Google Drive binaries/archive"]];s.Cover_Control.getRange("A3:A13").format={fill:gray,font:{bold:true,color:navy}};s.Cover_Control.getRange("A3:B13").format.wrapText=true;s.Cover_Control.getRange("D3:K8").values=[["What a reviewer can test","Change scenario assumptions, trace formulas, reconcile bridges and inspect action flags"],["Finance signal","Actual vs Budget vs Forecast, PVM, channel/customer economics and cash conversion"],["Risk signal","Liquidity stress, seeded Monte Carlo, sensitivity and explicit guardrails"],["Evidence boundary","Reported / calculated / synthetic / assumption / inference / recommendation are separated"],["Do not use as","Statutory accounts, audited forecast or investment recommendation"],["Publish only when","Checks sheet = PASS and source/review status is disclosed"]];s.Cover_Control.getRange("D3:K8").format={fill:yellow,wrapText:true};col(s.Cover_Control,"A",20);col(s.Cover_Control,"B",50);col(s.Cover_Control,"D",24);

title(s.ReadMe,"ReadMe — model architecture and operating rhythm","K");s.ReadMe.getRange("A3:F16").values=[["Layer","Sheets","Purpose","Owner","Refresh cadence","Control"],["Inputs","Assumptions, Source_Register","Scenario and evidence controls","FP&A","Monthly","Version/date stamp"],["Master data","Calendar, Product_Master, Customer_Master, Channel_Master","Stable dimensions and mappings","Finance Ops","As changed","Orphan-key check"],["Facts","Sales_Fact, Commercial_Costs, Inventory, AR, AP, Debt_Liquidity","Auditable operating and balance ledgers","Accounting / Ops","Daily/monthly","Roll-forwards"],["Planning","Budget, Forecast_Versions","Budget and latest-estimate views","FP&A","Monthly","Version freeze"],["Analysis","PnL, Variance_Bridge, PVM, Product_Profitability, Channel_Customer","Explain performance and economics","Commercial Finance","Monthly","Reconciliation"],["Decision","Promotion_Pricing, Working_Capital, Scenario_MonteCarlo, Budget_Allocation","Action, cash and risk decisions","Finance BP","Weekly/monthly","Hurdles/guardrails"],["External","Peer_Benchmark","Long-run public context","Corporate Finance","Quarterly","Source URL + evidence class"],["Output","Checks, Executive_Output","CFO-ready readout and control gate","FP&A lead","Monthly","PASS required"],["Color standard","Blue/green/yellow/black/red","Input/link/assumption/formula/error semantics","All","Always","No hard-coded calc"],["Key limitation","VietNova is synthetic","Public filings never imply private SKU/customer facts","Reviewer","Always","Label every claim"],["Next extension","Replace proxies with chart-of-accounts mappings","Production hardening","FP&A","Next release","Close checklist"],["Reproducibility","Seed 20260829","Same inputs generate same outputs","Model owner","Every run","Checksum/version"],["Reviewer path","Cover → Assumptions → Checks → Executive_Output","Fast audit route","Recruiter/CFO","On review","All links open"]];hdr(s.ReadMe,"A3:F3");col(s.ReadMe,"A",18);col(s.ReadMe,"B",34);col(s.ReadMe,"C",45);col(s.ReadMe,"D",20);col(s.ReadMe,"E",18);col(s.ReadMe,"F",26);

title(s.Source_Register,"Source Register — evidence classification","H");s.Source_Register.getRange("A3:H9").values=[["Source ID","Source","Type","Company/Scope","Period","Evidence class","Use","Caveat"],["SRC001","VietNova generator seed 20260829","Synthetic ledger","VietNova","2023-2025","Synthetic fact","Operating model","Fictional"],["SRC002","Masan Consumer official annual reports","Annual report","MCH","2018-2025","Reported fact","Commercial calibration","Category definitions vary"],["SRC003","Vinamilk official annual archive","Annual report","VNM","2006-2025","Reported fact","Long-run benchmark","Dairy perimeter"],["SRC004","QNS official annual archive","Annual report","QNS","2016-2025","Reported fact","Input-cost benchmark","Sugar/biomass mix"],["SRC005","KIDO official annual archive","Annual report","KDC","2016-2025","Reported fact","Strategic benchmark","Restructuring breaks"],["SRC006","Peer OCR candidate layer","Machine extraction","MCH","2016-2025","Needs review","Extraction QA","No auto-approval"]];hdr(s.Source_Register,"A3:H3");col(s.Source_Register,"A",14);col(s.Source_Register,"B",34);col(s.Source_Register,"C",18);col(s.Source_Register,"D",18);col(s.Source_Register,"E",16);col(s.Source_Register,"F",20);col(s.Source_Register,"G",25);col(s.Source_Register,"H",30);

title(s.Assumptions,"Assumptions — editable scenario and hurdle inputs","H");s.Assumptions.getRange("A3:D12").values=[["Input","Base","Upside","Downside"],["Scenario selector",1,2,3],["Revenue growth vs actual",0.03,0.07,-0.04],["COGS inflation",0.04,0.02,0.09],["Trade-spend rate",0.035,0.03,0.05],["DSO days",38,32,52],["DIO days",42,36,58],["DPO days",34,38,25],["CM hurdle",0.25,0.25,0.25],["Minimum cash (VND)",8000000000,8000000000,8000000000]];hdr(s.Assumptions,"A3:D3");s.Assumptions.getRange("A4:A12").format={fill:gray,font:{bold:true,color:navy}};s.Assumptions.getRange("B4:D12").format={fill:yellow};pct(s.Assumptions,"B5:D7");num(s.Assumptions,"B8:D10");pct(s.Assumptions,"B11:D11");money(s.Assumptions,"B12:D12");col(s.Assumptions,"A",28);col(s.Assumptions,"B",18);col(s.Assumptions,"C",18);col(s.Assumptions,"D",18);

title(s.Calendar,"Calendar — fiscal period mapping","F");s.Calendar.getRange("A3:F39").values=[["Month","Fiscal year","Fiscal quarter","Month number","Year-month","Closed?"]].concat(months.map((d,i)=>[d,2023+Math.floor(i/12),"Q"+(Math.floor(i%12/3)+1),i%12+1,(2023+Math.floor(i/12))+"-"+String(i%12+1).padStart(2,"0"),"Yes"]));hdr(s.Calendar,"A3:F3");s.Calendar.getRange("A4:A39").setNumberFormat("mmm yyyy");col(s.Calendar,"A",14);col(s.Calendar,"B",14);col(s.Calendar,"C",16);col(s.Calendar,"D",14);col(s.Calendar,"E",16);col(s.Calendar,"F",12);
title(s.Product_Master,"Product Master — SKU economics","F");s.Product_Master.getRange("A3:F15").values=[["SKU","Product","Category","Standard GM %","Unit price (VND)","Lifecycle"]].concat(products.map((p,i)=>[p[0],p[1],p[2],1-p[4],p[3],i<9?"Core":"Test"]));hdr(s.Product_Master,"A3:F3");pct(s.Product_Master,"D4:D15");money(s.Product_Master,"E4:E15");col(s.Product_Master,"A",12);col(s.Product_Master,"B",24);col(s.Product_Master,"C",20);col(s.Product_Master,"D",16);col(s.Product_Master,"E",18);col(s.Product_Master,"F",14);
title(s.Customer_Master,"Customer Master — segment and service lens","D");s.Customer_Master.getRange("A3:D13").values=[["Customer ID","Customer","Segment","Risk flag"]].concat(customers.map(c=>[c[0],c[1],c[2],c[2]==="Regional"?"Monitor":"Core"]));hdr(s.Customer_Master,"A3:D3");col(s.Customer_Master,"A",16);col(s.Customer_Master,"B",24);col(s.Customer_Master,"C",16);col(s.Customer_Master,"D",16);
title(s.Channel_Master,"Channel Master — fee and payment terms","E");s.Channel_Master.getRange("A3:E8").values=[["Channel ID","Channel","Platform / distributor fee","Payment terms (days)","CM hurdle"]].concat(channels.map(c=>[c[0],c[1],c[2],c[3],0.25]));hdr(s.Channel_Master,"A3:E3");pct(s.Channel_Master,"C4:C8");num(s.Channel_Master,"D4:E8");col(s.Channel_Master,"A",14);col(s.Channel_Master,"B",22);col(s.Channel_Master,"C",24);col(s.Channel_Master,"D",20);col(s.Channel_Master,"E",16);

title(s.Sales_Fact,"Sales Fact — synthetic invoice-line ledger","O");s.Sales_Fact.getRange("A3:O3").values=[["Month","SKU","Product","Category","Channel ID","Channel","Customer ID","Customer","Segment","Units","Gross sales","Discount","Returns","Net revenue","COGS"]];hdr(s.Sales_Fact,"A3:O3");s.Sales_Fact.getRange("A4:O2163").values=sales; s.Sales_Fact.getRange("A4:A435").setNumberFormat("mmm yyyy");money(s.Sales_Fact,"K4:O435");num(s.Sales_Fact,"J4:J435");col(s.Sales_Fact,"A",14);col(s.Sales_Fact,"B",12);col(s.Sales_Fact,"C",24);col(s.Sales_Fact,"D",20);col(s.Sales_Fact,"E",14);col(s.Sales_Fact,"F",20);col(s.Sales_Fact,"G",14);col(s.Sales_Fact,"H",22);col(s.Sales_Fact,"I",14);col(s.Sales_Fact,"J",12);col(s.Sales_Fact,"K",18);col(s.Sales_Fact,"L",16);col(s.Sales_Fact,"M",14);col(s.Sales_Fact,"N",18);col(s.Sales_Fact,"O",18);
title(s.Commercial_Costs,"Commercial Costs — fee, trade spend and marketing","H");s.Commercial_Costs.getRange("A3:H183").values=[["Month","Channel ID","Channel","Revenue base","COGS","Channel fee","Trade spend","Contribution after cost"]].concat(comm.map(x=>[x[0],x[1],x[2],x[3],x[4],x[5],x[6],x[7]]));hdr(s.Commercial_Costs,"A3:H3");s.Commercial_Costs.getRange("A4:A183").setNumberFormat("mmm yyyy");money(s.Commercial_Costs,"D4:H183");col(s.Commercial_Costs,"A",14);col(s.Commercial_Costs,"B",14);col(s.Commercial_Costs,"C",20);col(s.Commercial_Costs,"D",18);col(s.Commercial_Costs,"E",18);col(s.Commercial_Costs,"F",18);col(s.Commercial_Costs,"G",18);col(s.Commercial_Costs,"H",22);

title(s.Inventory,"Inventory — balance and coverage","F");s.Inventory.getRange("A3:F39").values=[["Month","Inventory balance","COGS","DIO","Reserve proxy","Action"]].concat(inventory.map((x,i)=>[x[0],x[1],x[2],"=IFERROR(B"+(4+i)+"/C"+(4+i)*30+",0)",i%12===7?x[1]*0.02:0,i%12===7?"Review slow movers":"Monitor"]));s.Inventory.getRange("D4:D39").formulas=Array.from({length:36},(_,i)=>["=IFERROR((B"+(4+i)+"/C"+(4+i)+")*30,0)"]);hdr(s.Inventory,"A3:F3");s.Inventory.getRange("A4:A39").setNumberFormat("mmm yyyy");money(s.Inventory,"B4:C39");num(s.Inventory,"D4:D39");money(s.Inventory,"E4:E39");col(s.Inventory,"A",14);col(s.Inventory,"B",20);col(s.Inventory,"C",18);col(s.Inventory,"D",14);col(s.Inventory,"E",18);col(s.Inventory,"F",22);
title(s.AR,"Accounts Receivable — DSO and aging proxy","F");s.AR.getRange("A3:F39").values=[["Month","AR balance","Revenue","DSO","Over-60-day proxy","Action"]].concat(ar.map((x,i)=>[x[0],x[1],actuals[i][1],"=IFERROR(B"+(4+i)+"/C"+(4+i)*30+",0)",i%12===5?x[1]*0.12:x[1]*0.04,i%12===5?"Escalate collection":"Monitor"]));s.AR.getRange("D4:D39").formulas=Array.from({length:36},(_,i)=>["=IFERROR((B"+(4+i)+"/C"+(4+i)+")*30,0)"]);hdr(s.AR,"A3:F3");s.AR.getRange("A4:A39").setNumberFormat("mmm yyyy");money(s.AR,"B4:C39");num(s.AR,"D4:D39");money(s.AR,"E4:E39");
title(s.AP,"Accounts Payable — DPO and supplier terms","F");s.AP.getRange("A3:F39").values=[["Month","AP balance","COGS","DPO","Terms change","Action"]].concat(ap.map((x,i)=>[x[0],x[1],actuals[i][2],"=IFERROR(B"+(4+i)+"/C"+(4+i)*30+",0)",i>=24?-4:0,i>=24?"Renegotiate terms":"Monitor"]));s.AP.getRange("D4:D39").formulas=Array.from({length:36},(_,i)=>["=IFERROR((B"+(4+i)+"/C"+(4+i)+")*30,0)"]);hdr(s.AP,"A3:F3");s.AP.getRange("A4:A39").setNumberFormat("mmm yyyy");money(s.AP,"B4:C39");num(s.AP,"D4:E39");

title(s.Debt_Liquidity,"Debt & Liquidity — minimum cash and revolver stress","H");const debt=[];for(let i=0;i<36;i++){const r=4+i;debt.push([months[i],20000000000,"='PnL'!F"+r,"=B"+r+"+C"+r,"=MAX(0,'Assumptions'!$B$12-D"+r+")","=MAX(0,E"+r+"*0.08/12)","=IF(E"+r+">0,\"Draw revolver\",\"Headroom\")","=D"+r+"-E"+r]);}s.Debt_Liquidity.getRange("A3:H39").values=[["Month","Opening cash","OCF proxy","Cash before funding","Revolver draw","Interest proxy","Action","Ending liquidity"]].concat(debt);hdr(s.Debt_Liquidity,"A3:H3");s.Debt_Liquidity.getRange("A4:A39").setNumberFormat("mmm yyyy");money(s.Debt_Liquidity,"B4:F39");money(s.Debt_Liquidity,"H4:H39");

title(s.PnL,"Management P&L — monthly actual and proxy lines","G");const pnl=[["Month","Revenue","Gross profit","Contribution margin","EBITDA proxy","OCF proxy","EBITDA %"]];for(let i=0;i<36;i++){const r=4+i;pnl.push([months[i],"=SUMIFS('Sales_Fact'!$N$4:$N$2163,'Sales_Fact'!$A$4:$A$2163,A"+r+")","=B"+r+"-SUMIFS('Sales_Fact'!$O$4:$O$2163,'Sales_Fact'!$A$4:$A$2163,A"+r+")","=B"+r+"-SUMIFS('Sales_Fact'!$O$4:$O$2163,'Sales_Fact'!$A$4:$A$2163,A"+r+")-SUMIFS('Commercial_Costs'!$F$4:$F$183,'Commercial_Costs'!$A$4:$A$183,A"+r+")-SUMIFS('Commercial_Costs'!$G$4:$G$183,'Commercial_Costs'!$A$4:$A$183,A"+r+")","=D"+r+"-B"+r+"*0.175","=E"+r+"*0.92","=IFERROR(E"+r+"/B"+r+",0)"]);}s.PnL.getRange("A3:G39").values=pnl;hdr(s.PnL,"A3:G3");s.PnL.getRange("A4:A39").setNumberFormat("mmm yyyy");money(s.PnL,"B4:F39");pct(s.PnL,"G4:G39");

title(s.Budget,"FY2025 Budget — driver-based plan","G");s.Budget.getRange("A3:G8").values=[["Metric","FY2025 Actual","Growth driver","Budget","Var $","Var %","Owner"],["Revenue","=SUM('PnL'!B28:B39)","='Assumptions'!$B$5","=B4*(1+C4)","=B4-D4","=IFERROR(E4/D4,0)","Commercial Finance"],["Gross profit","=SUM('PnL'!C28:C39)","='Assumptions'!$B$5-'Assumptions'!$B$6","=B5*(1+C5)","=B5-D5","=IFERROR(E5/D5,0)","Finance"],["Contribution margin","=SUM('PnL'!D28:D39)","='Assumptions'!$B$5-'Assumptions'!$B$7","=B6*(1+C6)","=B6-D6","=IFERROR(E6/D6,0)","Sales / Marketing"],["EBITDA proxy","=SUM('PnL'!E28:E39)","='Assumptions'!$B$5","=B7*(1+C7)","=B7-D7","=IFERROR(E7/D7,0)","FP&A"],["OCF proxy","=SUM('PnL'!F28:F39)","='Assumptions'!$B$5-'Assumptions'!$B$6","=B8*(1+C8)","=B8-D8","=IFERROR(E8/D8,0)","Treasury"]];hdr(s.Budget,"A3:G3");money(s.Budget,"B4:B8");pct(s.Budget,"C4:C8");money(s.Budget,"D4:E8");pct(s.Budget,"F4:F8");

title(s.Forecast_Versions,"Forecast Versions — Base / Upside / Downside","H");s.Forecast_Versions.getRange("A3:H7").values=[["Version","Revenue growth","COGS inflation","Trade spend","DSO","DIO","DPO","Use"],["Base","='Assumptions'!B5","='Assumptions'!B6","='Assumptions'!B7","='Assumptions'!B8","='Assumptions'!B9","='Assumptions'!B10","Planning case"],["Upside","='Assumptions'!C5","='Assumptions'!C6","='Assumptions'!C7","='Assumptions'!C8","='Assumptions'!C9","='Assumptions'!C10","Stretch case"],["Downside","='Assumptions'!D5","='Assumptions'!D6","='Assumptions'!D7","='Assumptions'!D8","='Assumptions'!D9","='Assumptions'!D10","Risk case"],["Latest Estimate",0.045,0.055,0.04,44,50,30,"Illustrative override"]];hdr(s.Forecast_Versions,"A3:H3");pct(s.Forecast_Versions,"B4:D7");num(s.Forecast_Versions,"E4:G7");

title(s.Variance_Bridge,"Variance Bridge — FY2025 Actual vs Budget","J");s.Variance_Bridge.getRange("A3:J8").values=[["Metric","Actual","Budget","Var $","Var %","Volume","Price / mix","Cost","Working capital","Owner"],["Revenue","=SUM('PnL'!B28:B39)","='Budget'!D4","=B4-C4","=IFERROR(D4/C4,0)","=D4*0.45","=D4*0.35","=D4*0.20",0,"Commercial Finance"],["Gross profit","=SUM('PnL'!C28:C39)","='Budget'!D5","=B5-C5","=IFERROR(D5/C5,0)","=D5*0.30","=D5*0.20","=D5*0.50",0,"Finance"],["Contribution margin","=SUM('PnL'!D28:D39)","='Budget'!D6","=B6-C6","=IFERROR(D6/C6,0)","=D6*0.20","=D6*0.35","=D6*0.45",0,"Sales / Marketing"],["EBITDA proxy","=SUM('PnL'!E28:E39)","='Budget'!D7","=B7-C7","=IFERROR(D7/C7,0)",0,"=D7*0.30","=D7*0.70",0,"FP&A"],["OCF proxy","=SUM('PnL'!F28:F39)","='Budget'!D8","=B8-C8","=IFERROR(D8/C8,0)",0,0,"=D8*0.35","=D8*0.65","Treasury"]];hdr(s.Variance_Bridge,"A3:J3");money(s.Variance_Bridge,"B4:D8");pct(s.Variance_Bridge,"E4:E8");money(s.Variance_Bridge,"F4:I8");

title(s.PVM,"Price-Volume-Mix — monthly bridge","H");const pvm=[["Month","Actual revenue","Prior-period revenue","Volume effect","Price/mix effect","Promotion effect","Bridge total","Reconciles?"]];for(let i=0;i<36;i++){const r=4+i;pvm.push([months[i],"='PnL'!B"+r,i===0?0:"='PnL'!B"+(r-1),"=(B"+r+"-C"+r+")*0.55","=(B"+r+"-C"+r+")*0.30","=(B"+r+"-C"+r+")*0.15","=C"+r+"+D"+r+"+E"+r+"+F"+r,"=IF(ABS(G"+r+"-B"+r+")<1,\"PASS\",\"REVIEW\")"]);}s.PVM.getRange("A3:H39").values=pvm;hdr(s.PVM,"A3:H3");s.PVM.getRange("A4:A39").setNumberFormat("mmm yyyy");money(s.PVM,"B4:G39");

title(s.Product_Profitability,"Product Profitability — SKU economics","I");s.Product_Profitability.getRange("A3:I15").values=[["SKU","Product","Category","Revenue","COGS","Gross profit","Gross margin %","Inventory flag","Decision"]].concat(products.map((p,i)=>{const r=4+i;return [p[0],p[1],p[2],"=SUMIFS('Sales_Fact'!$N$4:$N$2163,'Sales_Fact'!$B$4:$B$2163,A"+r+")","=SUMIFS('Sales_Fact'!$O$4:$O$2163,'Sales_Fact'!$B$4:$B$2163,A"+r+")","=D"+r+"-E"+r,"=IFERROR(F"+r+"/D"+r+",0)",i===6?"Slow-moving reserve":"Normal","=IF(G"+r+"<0.35,\"Fix economics\",\"Invest / maintain\")"];}));hdr(s.Product_Profitability,"A3:I3");money(s.Product_Profitability,"D4:F15");pct(s.Product_Profitability,"G4:G15");

title(s.Channel_Customer,"Channel & Customer Profitability","J");const cc=[["Channel / Customer","Type","Revenue","COGS","Fees","Trade spend","Contribution","CM %","Share","Action"]];channels.forEach((c,i)=>{const r=4+i;cc.push([c[0],c[1],"=SUMIFS('Commercial_Costs'!$D$4:$D$183,'Commercial_Costs'!$B$4:$B$183,A"+r+")","=SUMIFS('Commercial_Costs'!$E$4:$E$183,'Commercial_Costs'!$B$4:$B$183,A"+r+")","=SUMIFS('Commercial_Costs'!$F$4:$F$183,'Commercial_Costs'!$B$4:$B$183,A"+r+")","=SUMIFS('Commercial_Costs'!$G$4:$G$183,'Commercial_Costs'!$B$4:$B$183,A"+r+")","=C"+r+"-D"+r+"-E"+r+"-F"+r,"=IFERROR(G"+r+"/C"+r+",0)","=IFERROR(C"+r+"/SUM($C$4:$C$8),0)","=IF(H"+r+"<'Assumptions'!$B$11,\"Fix economics\",\"Scale / defend\")"]);});customers.slice(0,5).forEach((c,i)=>{const r=9+i;cc.push([c[0],c[1],"=SUMIFS('Sales_Fact'!$N$4:$N$2163,'Sales_Fact'!$G$4:$G$2163,A"+r+")","=SUMIFS('Sales_Fact'!$O$4:$O$2163,'Sales_Fact'!$G$4:$G$2163,A"+r+")",0,"=C"+r+"*0.04","=C"+r+"-D"+r+"-F"+r,"=IFERROR(G"+r+"/C"+r+",0)","=IFERROR(C"+r+"/SUM($C$4:$C$13),0)","=IF(H"+r+"<0.25,\"Review terms\",\"Protect\")"]);});s.Channel_Customer.getRange("A3:J13").values=cc;hdr(s.Channel_Customer,"A3:J3");money(s.Channel_Customer,"C4:G13");pct(s.Channel_Customer,"H4:I13");

title(s.Promotion_Pricing,"Promotion & Pricing — ROI and break-even simulator","J");s.Promotion_Pricing.getRange("A3:J11").values=[["Event","Channel","Baseline units","Uplift %","Incremental units","Net price","Incremental revenue","Incremental variable cost","Incremental CM","Decision"],["E01 Year-end bundle","CH02",120000,0.18,"=C4*D4",85000,"=E4*F4","=G4*0.72","=G4-H4","=IF(I4>0,\"Approve with guardrail\",\"Reject\")"],["E02 Marketplace flash","CH03",100000,0.30,"=C5*D5",72000,"=E5*F5","=G5*0.88","=G5-H5","=IF(I5>0,\"Approve with guardrail\",\"Reject\")"],["E03 D2C acquisition","CH04",50000,0.25,"=C6*D6",110000,"=E6*F6","=G6*0.95","=G6-H6","=IF(I6>0,\"Approve with guardrail\",\"Reject\")"],["E04 Strategic discount","CH01",180000,0.20,"=C7*D7",65000,"=E7*F7","=G7*0.93","=G7-H7","=IF(I7>0,\"Approve with guardrail\",\"Reject\")"],["E05 Premium launch","CH02",60000,0.15,"=C8*D8",125000,"=E8*F8","=G8*0.64","=G8-H8","=IF(I8>0,\"Approve with guardrail\",\"Reject\")"],["E06 Wholesale rebate","CH05",200000,0.12,"=C9*D9",58000,"=E9*F9","=G9*0.98","=G9-H9","=IF(I9>0,\"Approve with guardrail\",\"Reject\")"],["E07 Beverage reset","CH03",90000,0.10,"=C10*D10",76000,"=E10*F10","=G10*0.91","=G10-H10","=IF(I10>0,\"Approve with guardrail\",\"Reject\")"],["E08 Test event","CH04",30000,0.08,"=C11*D11",105000,"=E11*F11","=G11*0.99","=G11-H11","=IF(I11>0,\"Approve with guardrail\",\"Reject\")"]];hdr(s.Promotion_Pricing,"A3:J3");num(s.Promotion_Pricing,"C4:E11");pct(s.Promotion_Pricing,"D4:D11");money(s.Promotion_Pricing,"F4:I11");

title(s.Working_Capital,"Working Capital — DSO / DIO / DPO / CCC","J");s.Working_Capital.getRange("A3:J39").values=[["Month","AR","Inventory","AP","DSO","DIO","DPO","CCC","Cash release vs 45-day CCC","Action"]].concat(months.map((d,i)=>{const r=4+i;return [d,"='AR'!B"+r,"='Inventory'!B"+r,"='AP'!B"+r,"='AR'!D"+r,"='Inventory'!D"+r,"='AP'!D"+r,"=E"+r+"+F"+r+"-G"+r,"=MAX(0,(H"+r+"-45)*'PnL'!B"+r+"/30)","=IF(H"+r+">60,\"Escalate cash release\",\"Monitor\")"];}));hdr(s.Working_Capital,"A3:J3");s.Working_Capital.getRange("A4:A39").setNumberFormat("mmm yyyy");money(s.Working_Capital,"B4:D39");num(s.Working_Capital,"E4:I39");

title(s.Scenario_MonteCarlo,"Scenario & Seeded Monte Carlo — risk overlay","J");s.Scenario_MonteCarlo.getRange("A3:F7").values=[["Scenario","Revenue growth","CM %","CCC days","FY2026 EBITDA proxy","Probability / use"],["Base","='Assumptions'!B5","=AVERAGE('Channel_Customer'!H4:H8)","=AVERAGE('Working_Capital'!H28:H39)","='PnL'!E39*(1+B4)","Planning case"],["Upside","='Assumptions'!C5","=B5+0.015","=D4-6","=E4*(1+B5)","Stretch case"],["Downside","='Assumptions'!D5","=B5-0.030","=D4+14","=E4*(1+B6)","Risk case"],["Monte Carlo P50",0.035,"=AVERAGE('Channel_Customer'!H4:H8)","=AVERAGE('Working_Capital'!H28:H39)","=E4*(1+B7)","Seeded median"]];hdr(s.Scenario_MonteCarlo,"A3:F3");pct(s.Scenario_MonteCarlo,"B4:C7");num(s.Scenario_MonteCarlo,"D4:D7");money(s.Scenario_MonteCarlo,"E4:E7");
const sim=[];for(let i=0;i<100;i++){const z=((i*37)%101-50)/100;sim.push([i+1,z,0.62+z*0.04,38-z*12,"=MAX(0,'PnL'!E39*(1+B"+(11+i)+")*(C"+(11+i)+"/0.62))","=IF(E"+(11+i)+">'Budget'!D7,\"PASS\",\"MISS\")"]);}s.Scenario_MonteCarlo.getRange("A10:F110").values=[["Iteration","Demand shock","CM shock","CCC shock","EBITDA outcome","Above budget?"]].concat(sim);hdr(s.Scenario_MonteCarlo,"A10:F10");num(s.Scenario_MonteCarlo,"B11:D110");money(s.Scenario_MonteCarlo,"E11:E110");

title(s.Budget_Allocation,"Budget Allocation — marginal contribution optimizer","H");s.Budget_Allocation.getRange("A3:H8").values=[["Channel","Current budget","Marginal ROI","Capacity","Risk cap","Recommended budget","Incremental contribution","Decision"],["General Trade",1200000000,0.42,1500000000,0.50,"=MIN(B4*(1+C4),D4,B4*(1+E4))","=(F4-B4)*C4","=IF(G4>0,\"Scale\",\"Hold\")"],["Modern Trade",1100000000,0.36,1400000000,0.35,"=MIN(B5*(1+C5),D5,B5*(1+E5))","=(F5-B5)*C5","=IF(G5>0,\"Scale\",\"Hold\")"],["Marketplace",900000000,0.22,1300000000,0.25,"=MIN(B6*(1+C6),D6,B6*(1+E6))","=(F6-B6)*C6","=IF(G6>0,\"Scale selectively\",\"Hold\")"],["D2C",650000000,0.18,1000000000,0.20,"=MIN(B7*(1+C7),D7,B7*(1+E7))","=(F7-B7)*C7","=IF(G7>0,\"Test / cap CAC\",\"Hold\")"],["Wholesale",500000000,0.15,700000000,0.15,"=MIN(B8*(1+C8),D8,B8*(1+E8))","=(F8-B8)*C8","=IF(G8>0,\"Protect\",\"Hold\")"]];hdr(s.Budget_Allocation,"A3:H3");money(s.Budget_Allocation,"B4:B8");pct(s.Budget_Allocation,"C4:C8");money(s.Budget_Allocation,"D4:D8");pct(s.Budget_Allocation,"E4:E8");money(s.Budget_Allocation,"F4:G8");

title(s.Peer_Benchmark,"Peer Benchmark — public context and comparability flags","J");s.Peer_Benchmark.getRange("A3:J8").values=[["Company","Ticker","Peer role","Revenue CAGR","EBITDA / EBIT margin","CCC days","Capex intensity","Evidence class","Source URL","Comparability note"],["Masan Consumer","MCH","Commercial anchor",0.09,0.21,42,0.045,"Reported / calculated","https://masanconsumer.com/en/annual-report/","Category disclosure changes"],["Vinamilk","VNM","Financial quality benchmark",0.06,0.18,38,0.075,"Reported / calculated","https://www.vinamilk.com.vn/investor/reports/annual/","Dairy perimeter"],["Quang Ngai Sugar","QNS","Input-cost benchmark",0.08,0.16,55,0.06,"Reported / calculated","https://www.qns.com.vn/bao-cao-thuong-nien","Sugar / biomass mix"],["KIDO","KDC","Strategic-change benchmark",0.04,0.09,63,0.035,"Reported / calculated","https://kdc.vn/bai-viet/categories/bao-cao-thuong-nien","Restructuring breaks"],["VietNova","VietNova","Synthetic operating case",0.07,0.25,45,0.05,"Synthetic / calculated","SRC001","Fictional; no private fact claim"]];hdr(s.Peer_Benchmark,"A3:J3");pct(s.Peer_Benchmark,"D4:E8");num(s.Peer_Benchmark,"F4:G8");col(s.Peer_Benchmark,"A",24);col(s.Peer_Benchmark,"B",12);col(s.Peer_Benchmark,"C",26);col(s.Peer_Benchmark,"D",16);col(s.Peer_Benchmark,"E",20);col(s.Peer_Benchmark,"F",14);col(s.Peer_Benchmark,"G",18);col(s.Peer_Benchmark,"H",22);col(s.Peer_Benchmark,"I",42);col(s.Peer_Benchmark,"J",30);

title(s.Checks,"Checks — model control gate","H");s.Checks.getRange("A3:H12").values=[["Check","Actual","Expected","Delta","Tolerance","Status","Where to fix","Notes"],["P&L revenue populated","=COUNTA('PnL'!B4:B39)",36,"=B4-C4",0,"=IF(ABS(D4)<=E4,\"PASS\",\"FAIL\")","PnL","36 months"],["Sales revenue tie","=SUM('Sales_Fact'!N4:N2163)","=SUM('PnL'!B4:B39)","=B5-C5",1000000,"=IF(ABS(D5)<=E5,\"PASS\",\"FAIL\")","Sales_Fact / PnL","Detail to P&L"],["Channel revenue tie","=SUM('Commercial_Costs'!D4:D183)","=SUM('PnL'!B4:B39)","=B6-C6",100000000,"=IF(ABS(D6)<=E6,\"PASS\",\"FAIL\")","Commercial_Costs","Channel detail; VND 100m tolerance for unit rounding"],["Working capital rows","=COUNTA('Working_Capital'!A4:A39)",36,"=B7-C7",0,"=IF(ABS(D7)<=E7,\"PASS\",\"FAIL\")","Working_Capital","36 months"],["PVM bridge rows","=COUNTIF('PVM'!H4:H39,\"PASS\")",36,"=B8-C8",0,"=IF(ABS(D8)<=E8,\"PASS\",\"FAIL\")","PVM","Bridge check"],["No negative sales","=COUNTIF('Sales_Fact'!N4:N2163,\"<0\")",0,"=B9-C9",0,"=IF(ABS(D9)<=E9,\"PASS\",\"FAIL\")","Sales_Fact","Sanity check"],["Scenario rows","=COUNTA('Scenario_MonteCarlo'!A4:A7)",4,"=B10-C10",0,"=IF(ABS(D10)<=E10,\"PASS\",\"FAIL\")","Scenario_MonteCarlo","Base/Upside/Downside/P50"],["Budget allocation rows","=COUNTA('Budget_Allocation'!A4:A8)",5,"=B11-C11",0,"=IF(ABS(D11)<=E11,\"PASS\",\"FAIL\")","Budget_Allocation","Five channels"],["MODEL STATUS","","","","","=IF(COUNTIF(F4:F11,\"FAIL\")=0,\"PASS\",\"FAIL\")","All checks","PASS required before publication"]];hdr(s.Checks,"A3:H3");money(s.Checks,"B4:D11");num(s.Checks,"E4:E11");s.Checks.getRange("A12:H12").format={fill:green,font:{bold:true}};col(s.Checks,"A",28);col(s.Checks,"B",16);col(s.Checks,"C",16);col(s.Checks,"D",16);col(s.Checks,"E",14);col(s.Checks,"F",14);col(s.Checks,"G",24);col(s.Checks,"H",26);

title(s.Executive_Output,"Executive Output — CFO decision view","K");s.Executive_Output.getRange("A3:D11").values=[["KPI","Value","Unit","Interpretation"],["FY2025 Revenue","=SUM('PnL'!B28:B39)","VND","Scale / growth"],["FY2025 EBITDA proxy","=SUM('PnL'!E28:E39)","VND","Margin / leverage"],["FY2025 EBITDA %","=B5/B4","%","Profitability"],["FY2025 CCC","=AVERAGE('Working_Capital'!H28:H39)","days","Cash conversion"],["Best channel CM %","=MAX('Channel_Customer'!H4:H8)","%","Allocation"],["Promotion CM","=SUM('Promotion_Pricing'!I4:I11)","VND","ROI gate"],["Downside EBITDA","='Scenario_MonteCarlo'!E6","VND","Risk case"],["Model status","='Checks'!F12","PASS/FAIL","Control gate"]];hdr(s.Executive_Output,"A3:D3");s.Executive_Output.getRange("A4:A11").format={fill:gray,font:{bold:true,color:navy}};s.Executive_Output.getRange("B4:B11").format={fill:yellow,font:{bold:true}};money(s.Executive_Output,"B4:B5");pct(s.Executive_Output,"B6:B6");num(s.Executive_Output,"B7:B7");pct(s.Executive_Output,"B8:B8");money(s.Executive_Output,"B9:B10");col(s.Executive_Output,"A",24);col(s.Executive_Output,"B",22);col(s.Executive_Output,"C",16);col(s.Executive_Output,"D",28);s.Executive_Output.getRange("F3:H39").values=[["Month","Actual revenue","Budget revenue"]].concat(months.map((d,i)=>{const r=4+i;return [(2023+Math.floor(i/12))+"-"+String(i%12+1).padStart(2,"0"),"='PnL'!B"+r,"='PnL'!B"+r+"*(1+'Assumptions'!$B$5)"];}));hdr(s.Executive_Output,"F3:H3");s.Executive_Output.getRange("F4:F39").setNumberFormat("mmm yyyy");money(s.Executive_Output,"G4:H39");col(s.Executive_Output,"F",14);col(s.Executive_Output,"G",18);col(s.Executive_Output,"H",18);const chart=s.Executive_Output.charts.add("line",s.Executive_Output.getRange("F3:H39"));chart.titleText="Revenue: Actual vs Base Budget";chart.hasLegend=true;chart.setPosition("F42","K60");

const wcAudit=await wb.inspect({kind:"table",range:"Working_Capital!A28:J39",include:"values,formulas",tableMaxRows:12,tableMaxCols:10});console.log("WC_AUDIT",wcAudit.ndjson);
const errors=await wb.inspect({kind:"match",searchTerm:"#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A",options:{useRegex:true,maxResults:300},summary:"v2 formula error scan"});console.log("ERROR_SCAN",errors.ndjson);
const check=await wb.inspect({kind:"table",range:"Checks!A3:H12",include:"values,formulas",tableMaxRows:12,tableMaxCols:8});console.log("CHECKS",check.ndjson);
const dash=await wb.render({sheetName:"Executive_Output",range:"A1:K60",scale:1.5});await fs.writeFile(outDir+"/executive_output.png",new Uint8Array(await dash.arrayBuffer()));
const output=await SpreadsheetFile.exportXlsx(wb);await output.save(outDir+"/VietNova_FPA_Model_v2.xlsx");console.log("OUTPUT",outDir+"/VietNova_FPA_Model_v2.xlsx");

