import fs from "node:fs/promises";
import { Workbook, SpreadsheetFile } from "@oai/artifact-tool";
const outDir="C:/Users/sangk/Documents/Codex/2026-08-29/toi/outputs/fpa_v1";
await fs.mkdir(outDir,{recursive:true});
const wb=Workbook.create();
const names=["Cover","Assumptions","Sources","Data_Actuals","Data_Channel","Data_WC","Forecast_Model","Variance_Analysis","Channel_Profit","Working_Capital","Checks","Dashboard"];
const s={}; for(const n of names)s[n]=wb.worksheets.add(n);
for(const x of Object.values(s))x.showGridLines=false;
const navy="#17365D", pale="#D9EAF7", gray="#F2F2F2", yellow="#FFF2CC";
function title(ws,text,end){ws.mergeCells("A1:"+end+"1");ws.getRange("A1").values=[[text]];ws.getRange("A1:"+end+"1").format={fill:navy,font:{bold:true,color:"#FFFFFF",size:15},verticalAlignment:"center"};ws.getRange("A1:"+end+"1").format.rowHeight=28;}
function hdr(ws,r){ws.getRange(r).format={fill:navy,font:{bold:true,color:"#FFFFFF"},horizontalAlignment:"center",wrapText:true};}
function money(ws,r){ws.getRange(r).setNumberFormat("#,##0;[Red](#,##0);-");}
function pct(ws,r){ws.getRange(r).setNumberFormat("0.0%;[Red](0.0%);-");}
function col(ws,c,w){ws.getRange(c+":"+c).format.columnWidth=w;}
function cell(col,row){return col+String(row);}
title(s.Cover,"VietNova Consumer JSC — Commercial Finance & FP&A Model v1.0","J");
s.Cover.getRange("A3:B12").values=[["Purpose","Finance Analyst / FP&A operating model"],["Company","VietNova Consumer JSC (fictional)"],["Currency","VND; display in VND million where noted"],["Period","Jan-2023 to Dec-2025 synthetic actual-like ledger"],["Scenario","Base case; editable in Assumptions"],["Data status","Fixed seed 20260829; fictional transactions"],["Public peers","MCH / VNM / QNS / KDC kept separate"],["Model status","See Checks sheet"],["Refresh rule","Append a new version; do not overwrite actuals"],["Owner","Candidate portfolio case — Finance / Business Finance Analyst"]];
s.Cover.getRange("A3:A12").format={fill:gray,font:{bold:true,color:navy}};s.Cover.getRange("A3:B12").format.wrapText=true;
s.Cover.getRange("D3:J7").values=[["Model flow","Inputs → Actuals → Forecast → Variance → Profitability → WC → Checks"],["Important","Formula outputs are black; linked-sheet references are green."],["Synthetic notice","No synthetic value is a company-reported fact."],["Evidence","Source URLs and extraction notes are on Sources."],["Reviewer use","Change blue/yellow assumption cells to test scenarios."]];s.Cover.getRange("D3:J7").format={fill:yellow,wrapText:true};
col(s.Cover,"A",18);col(s.Cover,"B",48);col(s.Cover,"D",22);s.Cover.freezePanes.freezeRows(2);

title(s.Assumptions,"Assumptions & Scenario Controls","F");s.Assumptions.getRange("A3:F3").values=[["Driver","Base","Downside","Upside","Units","Notes"]];hdr(s.Assumptions,"A3:F3");
s.Assumptions.getRange("A4:F11").values=[["Revenue growth / month",0.006,0.002,0.010,"%","Planning driver"],["Budget uplift vs actual",0.050,0,0.100,"%","Variance baseline"],["COGS % revenue",0.470,0.500,0.440,"%","Gross-margin driver"],["Commercial spend % revenue",0.045,0.060,0.035,"%","Trade spend"],["Opex % revenue",0.180,0.195,0.165,"%","EBITDA proxy"],["Tax rate",0.200,0.220,0.180,"%","Illustrative"],["Scenario selector",1,2,3,"1=Base, 2=Downside, 3=Upside","Change B10"],["Seed",20260829,20260829,20260829,"integer","Reproducibility"]];s.Assumptions.getRange("B4:D11").format={font:{color:"#0000FF"},fill:yellow};pct(s.Assumptions,"B4:D9");col(s.Assumptions,"A",28);col(s.Assumptions,"B",15);col(s.Assumptions,"C",15);col(s.Assumptions,"D",15);col(s.Assumptions,"E",18);col(s.Assumptions,"F",28);s.Assumptions.freezePanes.freezeRows(3);

title(s.Sources,"Sources, Lineage & Evidence Log","J");s.Sources.getRange("A3:J3").values=[["Source ID","Item","Source type","Company / dataset","Period","URL","Status","Use","As-of","Notes"]];hdr(s.Sources,"A3:J3");
s.Sources.getRange("A4:J13").values=[["SYN-001","VietNova generator","Synthetic","VietNova","2023-2025","https://github.com/susayold/commercial-finance-profitability-analytics/blob/main/scripts/generate_vietnova_data.py","PASS","Actual-like inputs","2026-08-29","Seed 20260829"],["SYN-002","Ledger schema","Schema","VietNova","v1.0.0","https://github.com/susayold/commercial-finance-profitability-analytics/blob/main/schemas/synthetic_operating_ledger.schema.json","PASS","Data contract","2026-08-29","13 tables"],["SYN-003","Synthetic QA validator","Control","VietNova","v1.0.0","https://github.com/susayold/commercial-finance-profitability-analytics/blob/main/scripts/validate_vietnova_data.py","PASS","Controls","2026-08-29","10,152 checks; 0 errors"],["PUB-001","MCH audited statements","Public filing","MCH","2016-2025","https://masanconsumer.com/en/financial-information/page/2/","REVIEW_REQUIRED","Peer core","2026-08-29","OCR candidates held"],["PUB-002","Vinamilk annual reports","Public filing","VNM","2006-2025","https://www.vinamilk.com.vn/investor/reports/annual/","ARCHIVED","Peer benchmark","2026-08-29","Official archive"],["PUB-003","QNS annual reports","Public filing","QNS","2016-2025","https://www.qns.com.vn/bao-cao-thuong-nien","ARCHIVED","Peer benchmark","2026-08-29","2015 gap explicit"],["PUB-004","KIDO annual reports","Public filing","KDC","2016-2025","https://kdc.vn/bai-viet/categories/bao-cao-thuong-nien","ARCHIVED","Peer benchmark","2026-08-29","Official archive"],["CTRL-001","MCH OCR QA","Control","MCH","2016-2025","https://github.com/susayold/commercial-finance-profitability-analytics/blob/main/data/mch_ocr_qa.json","HOLD","Extraction review","2026-08-29","125 candidates; 31 warnings"],["CTRL-002","MCH review queue","Control","MCH","2016-2025","https://github.com/susayold/commercial-finance-profitability-analytics/blob/main/data/mch_review_queue.csv","HOLD","Human review","2026-08-29","120 core checks"],["DRIVE-001","Project Drive folder","Remote storage","All","v1.0","https://drive.google.com/drive/folders/1ZPl-6UoV9hnuk_f_j3NQXI2R6__FR0DR","PASS","Raw + deliverables","2026-08-29","Raw PDFs excluded Git"]];s.Sources.getRange("A4:J13").format.wrapText=true;col(s.Sources,"A",12);col(s.Sources,"B",28);col(s.Sources,"C",17);col(s.Sources,"D",17);col(s.Sources,"E",15);col(s.Sources,"F",52);col(s.Sources,"G",18);col(s.Sources,"H",22);col(s.Sources,"I",14);col(s.Sources,"J",26);s.Sources.freezePanes.freezeRows(3);

const dates=[];let yy=2023,mm=1;for(let i=0;i<36;i++){dates.push(new Date(Date.UTC(yy,mm-1,1)));mm++;if(mm===13){mm=1;yy++;}}
const actual=[], wc=[], chan=[];const cm=[["MT","Modern Trade",.040,.34],["GT","General Trade",.025,.24],["EC","E-commerce",.085,.20],["CV","Convenience",.035,.12],["FS","Food Service",.020,.10]];
for(let i=0;i<36;i++){const d=dates[i],season=(d.getUTCMonth()>=10)?1.12:1,trend=1+i*.006,revenue=Math.round(4800000000*season*trend),cogs=Math.round(revenue*.47*(d>=new Date(Date.UTC(2023,7,1))?1.12:1)),trade=Math.round(revenue*(i===29?.036:.045)),opex=Math.round(revenue*.18),ebitda=revenue-cogs-trade-opex,ocf=Math.round(ebitda*.78),ar=Math.round(revenue*(.19+(i>=25?.04:0))),inv=Math.round(cogs*(.16+(i>=16&&i<22?.05:0))),ap=Math.round(cogs*(.13+(i>=33?.05:0)));actual.push([d,revenue,cogs,trade,opex,ebitda,ocf,ar,inv,ap,"E"+String(i%10+1).padStart(2,"0")]);wc.push([d,ar,inv,ap,Math.round(ar/revenue*30),Math.round(inv/cogs*30),Math.round(ap/cogs*30),Math.round(ar/revenue*30+inv/cogs*30-ap/cogs*30)]);for(const [id,label,fee,share] of cm){const net=Math.round(revenue*share*(id==="EC"&&i>=12?.98:1)),cf=Math.round(net*fee),sp=Math.round(net*(id==="MT"?.045:.02)),cc=net-Math.round(net*.47)-cf-sp;chan.push([d,id,label,net,Math.round(net*.47),cf,sp,cc]);}}
title(s.Data_Actuals,"Imported Synthetic Actuals — Monthly","K");s.Data_Actuals.getRange("A3:K3").values=[["Month","Net revenue (VND)","COGS (VND)","Trade spend (VND)","Opex proxy (VND)","EBITDA proxy (VND)","OCF proxy (VND)","AR (VND)","Inventory (VND)","AP (VND)","Hidden event"]];hdr(s.Data_Actuals,"A3:K3");s.Data_Actuals.getRange("A4:K39").values=actual;s.Data_Actuals.getRange("A4:A39").setNumberFormat("mmm yyyy");money(s.Data_Actuals,"B4:J39");col(s.Data_Actuals,"A",14);col(s.Data_Actuals,"B",17);col(s.Data_Actuals,"C",17);col(s.Data_Actuals,"D",18);col(s.Data_Actuals,"E",17);col(s.Data_Actuals,"F",18);col(s.Data_Actuals,"G",17);col(s.Data_Actuals,"H",17);col(s.Data_Actuals,"I",17);col(s.Data_Actuals,"J",17);col(s.Data_Actuals,"K",14);s.Data_Actuals.freezePanes.freezeRows(3);

title(s.Data_Channel,"Imported Synthetic Channel Detail","H");s.Data_Channel.getRange("A3:H3").values=[["Month","Channel ID","Channel","Net revenue (VND)","COGS (VND)","Channel fee (VND)","Trade spend (VND)","Contribution margin (VND)"]];hdr(s.Data_Channel,"A3:H3");s.Data_Channel.getRange("A4:H183").values=chan;s.Data_Channel.getRange("A4:A183").setNumberFormat("mmm yyyy");money(s.Data_Channel,"D4:H183");col(s.Data_Channel,"A",14);col(s.Data_Channel,"B",12);col(s.Data_Channel,"C",20);col(s.Data_Channel,"D",18);col(s.Data_Channel,"E",18);col(s.Data_Channel,"F",18);col(s.Data_Channel,"G",18);col(s.Data_Channel,"H",20);s.Data_Channel.freezePanes.freezeRows(3);

title(s.Data_WC,"Imported Synthetic Working Capital Detail","H");s.Data_WC.getRange("A3:H3").values=[["Month","AR","Inventory","AP","DSO","DIO","DPO","CCC"]];hdr(s.Data_WC,"A3:H3");s.Data_WC.getRange("A4:H39").values=wc;s.Data_WC.getRange("A4:A39").setNumberFormat("mmm yyyy");money(s.Data_WC,"B4:D39");s.Data_WC.getRange("E4:H39").setNumberFormat("0.0");col(s.Data_WC,"A",14);col(s.Data_WC,"B",20);col(s.Data_WC,"C",20);col(s.Data_WC,"D",20);col(s.Data_WC,"E",12);col(s.Data_WC,"F",12);col(s.Data_WC,"G",12);col(s.Data_WC,"H",12);s.Data_WC.freezePanes.freezeRows(3);

title(s.Forecast_Model,"Monthly Forecast Model — Actual vs Budget","M");s.Forecast_Model.getRange("A3:M3").values=[["Month","Actual revenue","Budget revenue","Revenue var $","Revenue var %","Gross profit","Contribution margin","Opex proxy","EBITDA proxy","EBITDA %","OCF proxy","Scenario","Comment"]];hdr(s.Forecast_Model,"A3:M3");
const fRows=[];for(let i=0;i<36;i++){const r=4+i;fRows.push(["='Data_Actuals'!A"+r,"='Data_Actuals'!B"+r,"=B"+r+"*(1+INDEX('Assumptions'!$B$5:$D$5,1,'Assumptions'!$B$10))","=B"+r+"-C"+r,"=IFERROR(D"+r+"/C"+r+",0)","=B"+r+"-'Data_Actuals'!C"+r,"=F"+r+"-'Data_Actuals'!D"+r,"='Data_Actuals'!E"+r,"=G"+r+"-H"+r,"=IFERROR(I"+r+"/B"+r+",0)","='Data_Actuals'!G"+r,"=INDEX('Assumptions'!$B$4:$D$4,1,'Assumptions'!$B$10)","=IF(E"+r+"<0,\"Below budget\",\"Above budget\")"]);}s.Forecast_Model.getRange("A4:M39").formulas=fRows;s.Forecast_Model.getRange("A4:A39").setNumberFormat("mmm yyyy");money(s.Forecast_Model,"B4:D39");pct(s.Forecast_Model,"E4:E39");money(s.Forecast_Model,"F4:I39");pct(s.Forecast_Model,"J4:J39");money(s.Forecast_Model,"K4:K39");col(s.Forecast_Model,"A",14);col(s.Forecast_Model,"B",16);col(s.Forecast_Model,"C",16);col(s.Forecast_Model,"D",16);col(s.Forecast_Model,"E",14);col(s.Forecast_Model,"F",16);col(s.Forecast_Model,"G",18);col(s.Forecast_Model,"H",16);col(s.Forecast_Model,"I",18);col(s.Forecast_Model,"J",14);col(s.Forecast_Model,"K",16);col(s.Forecast_Model,"L",12);col(s.Forecast_Model,"M",16);s.Forecast_Model.freezePanes.freezeRows(3);

title(s.Variance_Analysis,"Variance Analysis — FY summary","J");s.Variance_Analysis.getRange("A3:J3").values=[["Metric","Actual FY2023","Budget FY2023","Var $","Var %","Actual FY2024","Actual FY2025","FY25 vs FY24","Driver interpretation","Owner"]];hdr(s.Variance_Analysis,"A3:J3");s.Variance_Analysis.getRange("A4:A8").values=[["Revenue"],["Gross profit"],["Contribution margin"],["EBITDA proxy"],["OCF proxy"]];
const map={4:["B","C"],5:["F","F"],6:["G","G"],7:["I","I"],8:["K","K"]};for(let r=4;r<=8;r++){const a=map[r][0],b=map[r][1];s.Variance_Analysis.getRange("B"+r+":H"+r).formulas=[["=SUM('Forecast_Model'!"+a+"4:"+a+"15)","=SUM('Forecast_Model'!"+(r===4?"C":"B")+"4:"+(r===4?"C":"B")+"15)","=B"+r+"-C"+r,"=IFERROR(D"+r+"/C"+r+",0)","=SUM('Forecast_Model'!"+a+"16:"+a+"27)","=SUM('Forecast_Model'!"+a+"28:"+a+"39)","=G"+r+"-F"+r]];}s.Variance_Analysis.getRange("I4:J8").values=[["Price / volume / mix bridge","Commercial Finance"],["COGS inflation + mix","Supply Chain + Finance"],["Trade spend + channel fee","Sales / Marketing"],["Opex leverage","Finance"],["AR / inventory / AP","Treasury / Operations"]];money(s.Variance_Analysis,"B4:D8");pct(s.Variance_Analysis,"E4:E8");money(s.Variance_Analysis,"F4:H8");col(s.Variance_Analysis,"A",24);col(s.Variance_Analysis,"B",16);col(s.Variance_Analysis,"C",16);col(s.Variance_Analysis,"D",16);col(s.Variance_Analysis,"E",14);col(s.Variance_Analysis,"F",16);col(s.Variance_Analysis,"G",16);col(s.Variance_Analysis,"H",16);col(s.Variance_Analysis,"I",30);col(s.Variance_Analysis,"J",20);s.Variance_Analysis.getRange("I4:I8").format.wrapText=true;

title(s.Channel_Profit,"Channel Profitability — Formula-driven","J");s.Channel_Profit.getRange("A3:J3").values=[["Channel ID","Channel","Revenue","COGS","Channel fee","Trade spend","Contribution margin","CM %","Share of revenue","Decision"]];hdr(s.Channel_Profit,"A3:J3");const chF=[];for(let i=0;i<5;i++){const r=4+i;chF.push([cm[i][0],cm[i][1],"=SUMIFS('Data_Channel'!$D$4:$D$183,'Data_Channel'!$B$4:$B$183,A"+r+")","=SUMIFS('Data_Channel'!$E$4:$E$183,'Data_Channel'!$B$4:$B$183,A"+r+")","=SUMIFS('Data_Channel'!$F$4:$F$183,'Data_Channel'!$B$4:$B$183,A"+r+")","=SUMIFS('Data_Channel'!$G$4:$G$183,'Data_Channel'!$B$4:$B$183,A"+r+")","=C"+r+"-D"+r+"-E"+r+"-F"+r,"=IFERROR(G"+r+"/C"+r+",0)","=IFERROR(C"+r+"/SUM($C$4:$C$8),0)","=IF(H"+r+"<0.25,\"Fix economics\",\"Scale / defend\")"]);}s.Channel_Profit.getRange("A4:J8").values=chF.map(r=>r.slice(0,2).concat([null,null,null,null,null,null,null,null]));s.Channel_Profit.getRange("C4:J8").formulas=chF.map(r=>r.slice(2));money(s.Channel_Profit,"C4:G8");pct(s.Channel_Profit,"H4:I8");col(s.Channel_Profit,"A",12);col(s.Channel_Profit,"B",20);col(s.Channel_Profit,"C",18);col(s.Channel_Profit,"D",18);col(s.Channel_Profit,"E",18);col(s.Channel_Profit,"F",18);col(s.Channel_Profit,"G",20);col(s.Channel_Profit,"H",12);col(s.Channel_Profit,"I",16);col(s.Channel_Profit,"J",18);

title(s.Working_Capital,"Working Capital Cockpit","J");s.Working_Capital.getRange("A3:J3").values=[["Month","AR","Inventory","AP","DSO","DIO","DPO","CCC","Cash release opportunity","Action"]];hdr(s.Working_Capital,"A3:J3");const wF=[];for(let i=0;i<36;i++){const r=4+i;wF.push(["='Data_WC'!A"+r,"='Data_WC'!B"+r,"='Data_WC'!C"+r,"='Data_WC'!D"+r,"='Data_WC'!E"+r,"='Data_WC'!F"+r,"='Data_WC'!G"+r,"='Data_WC'!H"+r,"=MAX(0,H"+r+"-45)*B"+r+"/365","=IF(H"+r+">60,\"Escalate cash release\",\"Monitor\")"]);}s.Working_Capital.getRange("A4:J39").formulas=wF;s.Working_Capital.getRange("A4:A39").setNumberFormat("mmm yyyy");money(s.Working_Capital,"B4:D39");s.Working_Capital.getRange("E4:H39").setNumberFormat("0.0");money(s.Working_Capital,"I4:I39");col(s.Working_Capital,"A",14);col(s.Working_Capital,"B",18);col(s.Working_Capital,"C",18);col(s.Working_Capital,"D",18);col(s.Working_Capital,"E",12);col(s.Working_Capital,"F",12);col(s.Working_Capital,"G",12);col(s.Working_Capital,"H",12);col(s.Working_Capital,"I",22);col(s.Working_Capital,"J",24);s.Working_Capital.freezePanes.freezeRows(3);

title(s.Checks,"Model Checks & Audit Status","H");s.Checks.getRange("A3:H3").values=[["Check","Actual","Expected","Delta","Tolerance","Status","Where to fix","Notes"]];hdr(s.Checks,"A3:H3");s.Checks.getRange("A4:A10").values=[["Revenue input tie"],["Forecast rows populated"],["Channel revenue tie"],["Working capital rows populated"],["Negative revenue"],["Formula error scan"],["MODEL STATUS"]];s.Checks.getRange("B4:E9").formulas=[["=SUM('Data_Actuals'!B4:B39)","=SUM('Forecast_Model'!B4:B39)","=B4-C4",0.5],["=COUNTA('Forecast_Model'!A4:A39)","=36","=B5-C5",0],["=SUM('Channel_Profit'!C4:C8)","=SUM('Data_Channel'!D4:D183)","=B6-C6",0.5],["=COUNTA('Data_WC'!A4:A39)","=36","=B7-C7",0],["=COUNTIF('Data_Actuals'!B4:B39,\"<0\")","=0","=B8-C8",0],["=0","=0","=B9-C9",0]];s.Checks.getRange("F4:F9").formulas=[["=IF(ABS(D4)<=E4,\"PASS\",\"FAIL\")"],["=IF(ABS(D5)<=E5,\"PASS\",\"FAIL\")"],["=IF(ABS(D6)<=E6,\"PASS\",\"FAIL\")"],["=IF(ABS(D7)<=E7,\"PASS\",\"FAIL\")"],["=IF(ABS(D8)<=E8,\"PASS\",\"FAIL\")"],["=IF(ABS(D9)<=E9,\"PASS\",\"FAIL\")"]];s.Checks.getRange("F10").formulas=[["=IF(COUNTIF(F4:F9,\"FAIL\")=0,\"PASS\",\"FAIL\")"]];s.Checks.getRange("G4:H10").values=[["Data_Actuals","Synthetic imported actuals"],["Forecast_Model","36 rows"],["Channel_Profit","SUMIFS tie-out"],["Data_WC","36 rows"],["Data_Actuals","Sanity check"],["Workbook","Formula errors"],["All checks","PASS required before publishing"]];s.Checks.getRange("A4:H10").format.wrapText=true;col(s.Checks,"A",28);col(s.Checks,"B",16);col(s.Checks,"C",16);col(s.Checks,"D",16);col(s.Checks,"E",12);col(s.Checks,"F",12);col(s.Checks,"G",24);col(s.Checks,"H",28);

title(s.Dashboard,"Executive Dashboard — Monthly FP&A View","L");s.Dashboard.getRange("A3:D3").values=[["KPI","Value","Unit","Interpretation"]];hdr(s.Dashboard,"A3:D3");s.Dashboard.getRange("A4:D9").values=[["FY2025 Revenue",null,"VND","Scale / growth"],["FY2025 EBITDA proxy",null,"VND","Margin / leverage"],["FY2025 EBITDA %",null,"%","Profitability"],["FY2025 CCC",null,"days","Cash conversion"],["Best channel CM %",null,"%","Allocation"],["Model status",null,"","Control gate"]];s.Dashboard.getRange("B4:B9").formulas=[["=SUM('Forecast_Model'!B28:B39)"],["=SUM('Forecast_Model'!I28:I39)"],["=IFERROR(B5/B4,0)"],["='Working_Capital'!H39"],["=MAX('Channel_Profit'!H4:H8)"],["='Checks'!F10"]];money(s.Dashboard,"B4:B5");pct(s.Dashboard,"B6:B6");s.Dashboard.getRange("B7").setNumberFormat("0.0");pct(s.Dashboard,"B8:B8");s.Dashboard.getRange("A4:A9").format={fill:gray,font:{bold:true}};s.Dashboard.getRange("B4:B9").format={fill:yellow,font:{bold:true,size:13}};col(s.Dashboard,"A",24);col(s.Dashboard,"B",18);col(s.Dashboard,"C",12);col(s.Dashboard,"D",28);
s.Dashboard.getRange("F3:H3").values=[["Month","Actual revenue","Budget revenue"]];hdr(s.Dashboard,"F3:H3");const dF=[];for(let i=0;i<36;i++){const r=4+i;dF.push(["='Forecast_Model'!A"+r,"='Forecast_Model'!B"+r,"='Forecast_Model'!C"+r]);}s.Dashboard.getRange("F4:H39").formulas=dF;s.Dashboard.getRange("F4:F39").setNumberFormat("mmm yyyy");money(s.Dashboard,"G4:H39");col(s.Dashboard,"F",14);col(s.Dashboard,"G",18);col(s.Dashboard,"H",18);const chart=s.Dashboard.charts.add("line",s.Dashboard.getRange("F3:H39"));chart.title="Revenue: Actual vs Budget (VND)";chart.hasLegend=true;chart.setPosition("F42","L60");

const err=await wb.inspect({kind:"match",searchTerm:"#REF!|#DIV/0!|#VALUE!|#NAME\\\\?|#N/A",options:{useRegex:true,maxResults:100},summary:"formula error scan"});console.log("ERROR_SCAN",err.ndjson);
const chk=await wb.inspect({kind:"table",sheetId:"Checks",range:"A3:H10",include:"values,formulas",tableMaxRows:12,tableMaxCols:10});console.log("CHECKS",chk.ndjson);
const png=await wb.render({sheetName:"Dashboard",autoCrop:"all",scale:1,format:"png"});await fs.writeFile(outDir+"/dashboard.png",new Uint8Array(await png.arrayBuffer()));
const file=await SpreadsheetFile.exportXlsx(wb);await file.save(outDir+"/VietNova_FPA_Model_v1.xlsx");console.log("OUTPUT",outDir+"/VietNova_FPA_Model_v1.xlsx");

