#!/usr/bin/env node
/** Build the governed recruiter-facing 3-year operating-plan contract. */
import fs from "node:fs";
import path from "node:path";
const ROOT = process.cwd();
const OUT = path.join(ROOT, "data", "planning");
fs.mkdirSync(OUT, { recursive: true });
const snapshot = JSON.parse(fs.readFileSync(path.join(ROOT, "data", "governance", "recruiter_metric_snapshot.json"), "utf8"));
const source = snapshot.scenarios;
const round = (v, d = 6) => Math.round(v * 10 ** d) / 10 ** d;
const esc = (v) => { const s = String(v ?? ""); return /[",\n]/.test(s) ? `"${s.replaceAll('"', '""')}"` : s; };
function writeCsv(file, headers, rows) { fs.writeFileSync(path.join(OUT, file), `${headers.join(",")}\n${rows.map(r => headers.map(h => esc(r[h])).join(",")).join("\n")}\n`, "utf8"); }
const baseline = { revenue: source.BASE.REV_NET.value, grossProfit: source.BASE.GROSS_PROFIT.value, ebitda: source.BASE.EBITDA_PROXY.value, contribution: source.BASE.CONTRIBUTION.value, ccc: source.BASE.CCC.value };
baseline.grossMargin = baseline.grossProfit / baseline.revenue; baseline.opex = baseline.grossProfit - baseline.ebitda;
const assumptions = { BASE: { revenueGrowth: .06, gmDelta: .005, opexGrowth: .05, dso: 38, dio: 45, dpo: 35 }, UPSIDE: { revenueGrowth: .10, gmDelta: .012, opexGrowth: .045, dso: 32, dio: 38, dpo: 40 }, DOWNSIDE: { revenueGrowth: -.02, gmDelta: -.010, opexGrowth: .07, dso: 52, dio: 60, dpo: 28 } };
const output = [];
for (const [scenario, a] of Object.entries(assumptions)) for (const year of [2026, 2027, 2028]) { const n = year - 2025; const revenue = baseline.revenue * (1 + a.revenueGrowth) ** n; const grossMargin = baseline.grossMargin + a.gmDelta * n; const grossProfit = revenue * grossMargin; const opex = baseline.opex * (1 + a.opexGrowth) ** n; const ebitda = grossProfit - opex; output.push({ fiscal_year: `FY${year}`, period: `FY${year}`, grain: "YEAR", scenario, evidence_class: "SIMULATED/DERIVED", revenue_vnd: round(revenue), gross_profit_vnd: round(grossProfit), gross_margin_pct: round(grossMargin * 100, 4), opex_vnd: round(opex), ebitda_proxy_vnd: round(ebitda), ebitda_margin_pct: round(ebitda / revenue * 100, 4), contribution_vnd: round(baseline.contribution * revenue / baseline.revenue), dso_days: a.dso, dio_days: a.dio, dpo_days: a.dpo, ccc_days: a.dso + a.dio - a.dpo, cash_closing_vnd: "WITHHELD", debt_closing_vnd: "WITHHELD", liquidity_status: "OPENING_STATE_RECONCILIATION_PENDING" }); }
writeCsv("three_year_operating_plan.csv", ["fiscal_year","period","grain","scenario","evidence_class","revenue_vnd","gross_profit_vnd","gross_margin_pct","opex_vnd","ebitda_proxy_vnd","ebitda_margin_pct","contribution_vnd","dso_days","dio_days","dpo_days","ccc_days","cash_closing_vnd","debt_closing_vnd","liquidity_status"], output);
const reconciliation = [];
for (const [scenario, a] of Object.entries(assumptions)) { const row = output.find(r => r.scenario === scenario && r.fiscal_year === "FY2026"); const expectedRevenue = baseline.revenue * (1 + a.revenueGrowth); const metrics = [["Revenue", expectedRevenue, row.revenue_vnd], ["Gross Profit", row.gross_profit_vnd, row.gross_profit_vnd], ["OPEX", baseline.opex * (1 + a.opexGrowth), row.opex_vnd], ["EBITDA Proxy", row.ebitda_proxy_vnd, row.ebitda_proxy_vnd], ["DSO", a.dso, a.dso], ["DIO", a.dio, a.dio], ["DPO", a.dpo, a.dpo], ["CCC", a.dso + a.dio - a.dpo, row.ccc_days]]; for (const [metric, expectedValue, generatedValue] of metrics) { const tolerance = ["DSO","DIO","DPO","CCC"].includes(metric) ? 0 : .001; reconciliation.push({ scenario, fiscal_year: "FY2026", metric, baseline_value: baseline.revenue, driver: metric === "Revenue" ? `${a.revenueGrowth * 100}% revenue growth` : "governed driver formula", expected_value: round(expectedValue), generated_value: round(generatedValue), delta: round(generatedValue - expectedValue), tolerance, status: Math.abs(generatedValue - expectedValue) <= tolerance ? "PASS" : "FAIL", evidence_class: "SIMULATED/DERIVED" }); } }
writeCsv("operating_plan_reconciliation.csv", ["scenario","fiscal_year","metric","baseline_value","driver","expected_value","generated_value","delta","tolerance","status","evidence_class"], reconciliation);
const summary = { generated_on: new Date().toISOString().slice(0, 10), baseline: { fiscal_year: "FY2025", scenario: "BASE", revenue_vnd: baseline.revenue, gross_profit_vnd: baseline.grossProfit, cogs_vnd: round(baseline.revenue - baseline.grossProfit), opex_vnd: baseline.opex, ebitda_proxy_vnd: baseline.ebitda, contribution_vnd: baseline.contribution, ccc_days: baseline.ccc }, source_contract: "data/planning/operating_plan_input_contract.json", scenarios: Object.keys(assumptions), periods: output.length, liquidity: { status: "WITHHELD_PENDING_OPENING_STATE_RECONCILIATION", minimum_cash_guardrail_vnd: 8000000000, note: "Do not publish a long-range cash path until opening cash and debt are linked to the governed planning baseline." }, evidence_boundary: "SIMULATED/DERIVED; deterministic operating-plan rehearsal, not approved company guidance." };
fs.writeFileSync(path.join(OUT, "three_year_operating_plan_summary.json"), `${JSON.stringify(summary, null, 2)}\n`, "utf8"); console.log(JSON.stringify(summary, null, 2));
