import fs from "node:fs";
const report=fs.readFileSync(process.argv[2]||"reports/MONTE_CARLO_RISK_OVERLAY_2026-08-30.md","utf8");
const csv=fs.readFileSync(process.argv[3]||"data/monte_carlo_risk_overlay_2026-08-30.csv","utf8").trim().split(/\r?\n/);
const checks=[]; const must=(n,o)=>checks.push({n,ok:Boolean(o)});
must("report_nontrivial",report.length>3500);
for(const p of ["## Model assumptions","## Percentile output","## Finance interpretation","## Decision rules","## Limitations and handoff"])must(p,report.includes(p));
must("simulation_count",report.includes("5,000")&&report.includes("20260830"));
must("thresholds",["76.9","53.1","68.8","25%"].every(v=>report.includes(v)));
must("header",csv[0]==="metric,statistic,value,unit,threshold,threshold_direction,simulation_count,seed,evidence_class");
const rows=csv.slice(1).map(x=>x.split(","));
must("row_count",rows.length===25);
must("metrics",["revenue","ebitda_proxy","ebitda_margin","ccc","joint_downside"].every(m=>rows.some(r=>r[0]===m)));
must("five_percentiles_each",["revenue","ebitda_proxy","ebitda_margin","ccc"].every(m=>rows.filter(r=>r[0]===m&&r[1].startsWith("p")).length===5));
must("evidence_class",rows.every(r=>r.length===9&&r[8]==="SIMULATED_DERIVED"));
must("seed_and_n",rows.every(r=>r[6]==="5000"&&r[7]==="20260830"));
must("boundary",report.includes("not a live probabilistic forecast")&&report.includes("Gate A remains open"));
const failed=checks.filter(c=>!c.ok); for(const c of checks) console.log((c.ok?"PASS ":"FAIL ")+c.n);
console.log("Overall status: "+(failed.length?"FAIL":"PASS")+" ("+(checks.length-failed.length)+"/"+checks.length+" checks passed)");
if(failed.length)process.exit(1);
