import fs from "node:fs";
const report=fs.readFileSync(process.argv[2]||"docs/MONTHLY_CLOSE_FORECAST_BUSINESS_PARTNERING_CALENDAR.md","utf8");
const csv=fs.readFileSync(process.argv[3]||"data/monthly_close_forecast_business_partnering_calendar.csv","utf8").trim().split(/\r?\n/);
const checks=[]; const must=(n,o)=>checks.push({n,ok:Boolean(o)});
must("report_nontrivial",report.length>7000);
for(const p of ["## Ten-day cadence","## RACI","## Required pack contents","## Close-quality scorecard","## Handoff rules","## Interview conversion"])must(p,report.includes(p));
must("wd5_wdplus5",["WD-5","WD0","WD+5"].every(v=>report.includes(v)));
must("freeze_control",report.includes("before actual availability")&&report.includes("FROZEN"));
must("header",csv[0]==="timing,activity,primary_owner,input,output,control_sla,escalation");
const rows=csv.slice(1).map(x=>x.split(","));
must("row_count",rows.length===11);
must("required_fields",rows.every(r=>r.length===7&&r.every(Boolean)));
must("timings",["WD-5","WD-4","WD-3","WD-2","WD-1","WD0","WD+1","WD+2","WD+3","WD+4","WD+5"].every(t=>rows.some(r=>r[0]===t)));
must("boundary",report.includes("synthetic")&&report.includes("not a claim"));
const failed=checks.filter(c=>!c.ok); for(const c of checks) console.log((c.ok?"PASS ":"FAIL ")+c.n);
console.log("Overall status: "+(failed.length?"FAIL":"PASS")+" ("+(checks.length-failed.length)+"/"+checks.length+" checks passed)");
if(failed.length)process.exit(1);
