table Fact_Public_Cashflow
	lineageTag: b481482f-5508-49d2-a35e-4cf745158c24

	column CompanyKey
		dataType: string
		isKey
		summarizeBy: none
		sourceColumn: CompanyKey
		lineageTag: 93b28546-6cd0-4981-a4f3-6d8d77e58981
		annotation SummarizationSetBy = User

	column Ticker
		dataType: string
		summarizeBy: none
		sourceColumn: Ticker
		lineageTag: 93b3542e-3342-46e3-bbfa-61e33292d1b0
		annotation SummarizationSetBy = User

	column FiscalYear
		dataType: int64
		formatString: #,0
		summarizeBy: sum
		sourceColumn: FiscalYear
		lineageTag: 7b0e07d7-21c6-41e3-a127-ea327f5388b9
		annotation SummarizationSetBy = User

	column OperatingCashFlowVNDBn
		dataType: double
		formatString: #,0
		summarizeBy: sum
		sourceColumn: OperatingCashFlowVNDBn
		lineageTag: 3744efa6-82bf-4f17-bb64-7918f9b2654b
		annotation SummarizationSetBy = User

	column PATVNDBn
		dataType: double
		formatString: #,0
		summarizeBy: sum
		sourceColumn: PATVNDBn
		lineageTag: 63dabec0-66c0-4f72-9077-f0a8dab81ab3
		annotation SummarizationSetBy = User

	column EvidenceClass
		dataType: string
		isKey
		summarizeBy: none
		sourceColumn: EvidenceClass
		lineageTag: 51a1353c-7c39-4e6e-b8a1-ccc1a4f4ea25
		annotation SummarizationSetBy = User

	column SourceDocument
		dataType: string
		summarizeBy: none
		sourceColumn: SourceDocument
		lineageTag: 9e52386f-8a17-432d-a519-b00aeb2c1c77
		annotation SummarizationSetBy = User

	partition Fact_Public_Cashflow = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataRoot & "\\fact_public_cashflow.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"CompanyKey", type text}, {"Ticker", type text}, {"FiscalYear", Int64.Type}, {"OperatingCashFlowVNDBn", type number}, {"PATVNDBn", type number}, {"EvidenceClass", type text}, {"SourceDocument", type text}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
