'use client';
import { useMemo, useState } from 'react';
import { BarChart3, CheckCircle2, CircleDollarSign, Clock3, ExternalLink, Gauge, Landmark, ShieldAlert, TrendingUp } from 'lucide-react';
import data from '../data/generated/page10-dashboard.json';
import page2 from '../data/generated/page2-performance.json';
type Scenario = typeof data.scenarios[number];
const nav = (hash: string) => `../${hash}`;
const fmt = (n: number, d = 1) => n.toLocaleString('en-US', { minimumFractionDigits: d, maximumFractionDigits: d });
function SectionTitle({ n, title, sub }: { n: number; title: string; sub?: string }) { return <div className="p10-section-title"><span>{n}</span><div><h2>{title}</h2>{sub && <small>{sub}</small>}</div></div>; }
function Badge({ children, tone = 'green' }: { children: React.ReactNode; tone?: string }) { return <span className={`p10-badge ${tone}`}>{children}</span>; }
function Kpi({ label, value, note, href, icon: Icon }: { label: string; value: string; note: string; href: string; icon: typeof BarChart3 }) { return <a className="p10-kpi" href={href}><Icon size={22} /><div><small>{label}</small><strong>{value}</strong><em>{note}</em></div></a>; }
function ScenarioCard({ item, active, onClick }: { item: Scenario; active: boolean; onClick: () => void }) { return <button className={`p10-scenario ${item.name.toLowerCase()} ${active ? 'active' : ''}`} onClick={onClick}><div><b>{item.name.toUpperCase()}</b><Badge tone={item.name === 'Base' ? 'green' : item.name === 'Upside' ? 'teal' : 'amber'}>{item.tag}</Badge></div><strong>{fmt(item.revenue)}<small>bn Revenue</small></strong><strong>{fmt(item.ebitda)}<small>bn EBITDA Proxy</small></strong><strong>{item.ccc}<small>days CCC</small></strong></button>; }
export default function DashboardPage10() {
  const [selected, setSelected] = useState('Base');
  const scenario = useMemo(() => data.scenarios.find((s) => s.name === selected) ?? data.scenarios[1], [selected]);
  const trend = page2.monthly.map((m) => ({ label: m.label, revenue: m.forecast.revenue, margin: m.actual.ebitdaProxy / m.actual.revenue * 100 }));
  const maxRev = Math.max(...trend.map((m) => m.revenue));
  return <main className="p10-shell" id="dashboard">
    <nav className="p10-nav"><a className="p10-brand" href="../"><span>▥</span><b>VietNova Finance<small>FP&amp;A · Financial Performance &amp; Analytics</small></b></a><div className="p10-navlinks">{[['Executive','#executive'],['Performance','#performance'],['Commercial','#commercial'],['Profitability','#profitability'],['Costing','#costing'],['Resources','#resources'],['Cash & WC','#cash'],['Forecast','#forecast'],['Evidence','#evidence']].map(([label, hash]) => <a key={label} href={nav(hash)}>{label}</a>)}<a className="active" href="#dashboard">Dashboard</a></div><a className="p10-model" href="https://github.com/susayold/commercial-finance-profitability-analytics" target="_blank" rel="noreferrer">Open model <ExternalLink size={13} /></a></nav>
    <header className="p10-position page-width"><div><div className="p10-eyebrow">FP&amp;A EXECUTIVE DASHBOARD</div><h1>From Insight to Action.<br /><em>A Stronger VietNova Tomorrow.</em></h1><p>Base performance is profitable, but margin conversion, working capital and downside liquidity require active management.</p></div><div className="p10-position-card"><small>MANAGEMENT POSITION</small><strong>Base Case <i>ACTIVE ANCHOR</i></strong><strong>Upside <i className="teal">GATED</i></strong><strong>Downside <i className="amber">CONTINGENCY</i></strong><strong>Gate A <i className="red">OPEN</i></strong></div></header>
    <section className="p10-kpis page-width" aria-label="FY2025 base KPI snapshot"><Kpi icon={BarChart3} label="FY2025 Revenue" value="82.5bn" note="Base" href={nav('#performance')} /><Kpi icon={TrendingUp} label="Gross Margin" value="32.6%" note="Proxy-derived" href={nav('#performance')} /><Kpi icon={Gauge} label="EBITDA Proxy" value="12.9bn" note="15.6% margin" href={nav('#performance')} /><Kpi icon={Gauge} label="EBITDA Proxy Margin" value="15.6%" note="FY2025 Base" href={nav('#performance')} /><Kpi icon={CircleDollarSign} label="Contribution" value="24.2bn" note="Proxy-derived" href={nav('#commercial')} /><Kpi icon={Clock3} label="CCC" value="54d" note="Proxy-derived" href={nav('#cash-working-capital')} /></section>
    <section className="p10-grid p10-row-one page-width"><article className="p10-card p10-performance"><SectionTitle n={1} title="Performance & Landing Range" sub="Revenue bars · EBITDA Proxy Margin line · Page 2 current contract" /><div className="p10-performance-body"><div className="p10-chart" role="img" aria-label="Monthly forecast revenue bars with EBITDA proxy margin line">{trend.map((m) => <div className="p10-bar-wrap" key={m.label}><div className="p10-bar" style={{ height: `${m.revenue / maxRev * 125}px` }}><b>{m.revenue.toFixed(1)}</b></div><small>{m.label}</small></div>)}</div><div className="p10-trend-note"><span><i className="dot emerald" /> Revenue · FY2025 forecast reconciles to 82.5138bn</span><span><i className="dot gold" /> EBITDA Proxy Margin · monthly actual proxy trend</span><h3>Revenue range is contained;<br /><em>EBITDA risk is not.</em></h3></div></div><div className="p10-scenarios">{data.scenarios.map((item) => <ScenarioCard item={item} active={item.name === selected} onClick={() => setSelected(item.name)} key={item.name} />)}</div><a className="p10-drill" href={nav('#forecast')}>View Forecast &amp; Scenario →</a></article><article className="p10-card p10-commercial"><SectionTitle n={2} title="Commercial & Margin Signals" sub="Decision quality, not revenue alone" /><Badge tone="gold">PROMOTION DISCIPLINE</Badge><div className="p10-bigstat"><strong>8</strong><span>cases evaluated</span></div><div className="p10-segment"><i style={{ width: '37.5%' }} /> <i className="reject" style={{ width: '62.5%' }} /></div><div className="p10-split"><b><span>3</span> approve</b><b><span className="redtext">5</span> reject</b></div><div className="p10-mini-grid"><div><small>Portfolio ROI</small><strong>30.1%</strong></div><div><small>ROI Hurdle</small><strong>25%</strong></div><div><small>Budget</small><strong>4.35bn</strong></div><div><small>Modeled contribution</small><strong className="greentext">+55m</strong></div></div><p className="p10-callout">Average ROI clears hurdle, yet 5 of 8 cases should still be rejected.</p><a className="p10-drill" href={nav('#commercial')}>View Commercial Performance →</a></article></section>
    <section className="p10-grid p10-row-two page-width"><article className="p10-card"><SectionTitle n={3} title="Cash & Working Capital" sub="Core operating view · FY2025 Base" /><div className="p10-metrics"><div><small>Operating WC</small><strong>13.337bn</strong></div><div><small>AR 61+</small><strong>2.158bn</strong></div><div><small>Slow-moving inventory</small><strong>1.773bn</strong></div><div><small>Base CCC</small><strong>54d</strong></div></div><div className="p10-waterfall">{data.cash.waterfall.map((x) => <div key={x.label} className={x.value < 0 ? 'negative' : ''}><span>{x.label}</span><b>{x.value > 0 ? '+' : ''}{x.value.toFixed(3)}</b></div>)}<div className="total"><span>Operating WC</span><b>13.337</b></div></div><div className="p10-stress"><ShieldAlert size={18} /><div><Badge tone="amber">FY2026 STRESS REHEARSAL</Badge><p>First negative headroom <b>Oct-2026</b> · Dec headroom <b className="redtext">−0.740bn</b> · Revolver <b>2.500bn</b></p></div></div><a className="p10-drill" href={nav('#cash')}>View Cash &amp; WC →</a></article><article className="p10-card"><SectionTitle n={4} title="Cost & Resources" sub="Cross-page signals with scope preserved" /><Badge tone="gold">DETAILED COSTING REHEARSAL</Badge><div className="p10-signal"><b>+249.4m</b><span>FY2025 unfavorable cost variance</span><em>Material-price share <strong>82.0%</strong></em></div><Badge tone="teal">RESOURCE PLANNING LAYER</Badge><div className="p10-mini-grid"><div><small>Q4 vs Q1 OPEX</small><strong>+26.3%</strong></div><div><small>Non-payroll share</small><strong>75.6%</strong></div><div><small>OPEX bridge</small><strong className="redtext">+496.1m</strong><em>OPEN</em></div></div><div className="p10-capex"><Landmark size={18} /><span><b>{data.costResource.capexProject}</b><small>{data.costResource.capexStatus} · 1.300bn envelope · 22m payback</small></span></div><a className="p10-drill" href={nav('#costing')}>View Costing</a><a className="p10-drill secondary" href={nav('#resources')}>View Resources →</a></article><article className="p10-card p10-actions"><SectionTitle n={5} title="Management Actions" sub="Top five operating priorities" />{[['Prioritize aged receivables','AR Lead','DSO ≤43d'],['Reduce slow-SKU inventory','Supply-Chain Finance','Service level ≥95%'],['Reallocate promotion budget','Commercial Finance','ROI / CM ≥25%'],['Keep Upside gated','FP&A Lead','Two closes above hurdle'],['Capture frozen forecast snapshot','FP&A Lead','Gate A OPEN']].map((a, i) => <div className="p10-action" key={a[0]}><span>{String(i + 1).padStart(2, '0')}</span><div><b>{a[0]}</b><small>Owner: {a[1]} · {a[2]}</small></div></div>)}</article></section>
    <section className="p10-card p10-plan page-width"><SectionTitle n={6} title="FY2026–FY2028 Plan Snapshot" sub="Base case · simulated / derived planning layer" /><div className="p10-plan-chart">{data.plan.map((x) => <div className="p10-year" key={x.year}><div className="p10-plan-bars"><i style={{ height: `${x.revenue * 1.05}px` }}><b>{x.revenue}</b></i><i className="goldbar" style={{ height: `${x.ebitda * 4}px` }}><b>{x.ebitda}</b></i><i className="bluebar" style={{ height: `${x.cash * 4}px` }}><b>{x.cash}</b></i></div><strong>{x.year}</strong><small>Revenue · EBITDA Proxy · Cash</small></div>)}</div><div className="p10-plan-note"><TrendingUp size={18} /> Base case maintains cash above 8.0bn by 2026 and improves thereafter.</div></section>
    <section className="p10-card p10-controls page-width"><SectionTitle n={7} title="Project Controls & Release Status" sub="Inherited governance status · Gate A remains visible" /><div className="p10-control-grid">{data.controls.map((x) => <div key={x.label}><small>{x.label}</small><strong>{x.value}</strong><Badge tone={x.status === 'PASS' ? 'green' : x.status === 'OPEN' ? 'amber' : x.status === 'OUT' ? 'slate' : 'blue'}>{x.status}</Badge></div>)}</div><a className="p10-drill" href={nav('#evidence')}>View Controls &amp; Evidence →</a></section>
    <footer className="p10-footer"><span>VietNova Finance · PORTFOLIO CASE · SIMULATED / DERIVED DATA</span><span>Open evidence gates remain visible.</span><a href="https://github.com/susayold/commercial-finance-profitability-analytics" target="_blank" rel="noreferrer">GitHub <ExternalLink size={13} /></a></footer>
  </main>;
}
