'use client';

import { useMemo, useState } from 'react';
import { AlertTriangle, ArrowDownRight, ArrowUpRight, BarChart3, CheckCircle2, CircleDollarSign, Clock3, Database, FileText, Scale, ShieldCheck, Store, Target, TrendingUp, Users, WalletCards } from 'lucide-react';

type Customer = { id:string; name:string; channel:string; gross:number; net:number; contribution:number; margin:number; dso:number; wc:number; after:number; strategic:boolean };
const customers: Customer[] = [
  ['C01','Customer 01','General Trade',6450,5921,2426,40.97,45,73,2353,false],['C02','Customer 02','Modern Trade',6900,5782,2172,37.56,74.99,119,2053,false],['C03','Customer 03','Marketplace',7350,6577,2615,39.76,30.02,54,2561,false],['C04','Customer 04','D2C',7800,7238,3514,48.55,7.01,14,3500,true],['C05','Customer 05','Wholesale',8250,7408,3029,40.89,60.01,122,2907,false],['C06','MT National Account','Modern Trade',18000,14400,2100,14.58,88.72,350,1750,true],['C07','Customer 07','Modern Trade',9150,7667,2881,37.58,74.98,158,2723,false],['C08','Customer 08','Marketplace',9600,8592,3415,39.75,29.99,71,3344,true],['C09','Customer 09','D2C',10050,9325,4527,48.55,7.01,18,4509,false],['C10','Customer 10','Wholesale',10500,9429,3854,40.87,60,155,3699,false],['C11','Customer 11','General Trade',10950,10052,4118,40.97,44.99,124,3994,false],['C12','Customer 12','Modern Trade',11400,9553,3590,37.58,75,196,3394,true],['C13','Customer 13','Marketplace',11850,10605,4215,39.75,30.01,87,4128,false],['C14','Customer 14','D2C',12300,11414,5541,48.55,7,22,5519,false],['C15','Customer 15','Wholesale',12750,11449,4680,40.88,60,188,4492,false],['C16','Customer 16','General Trade',13200,12118,4965,40.97,45,149,4816,true],['C17','Customer 17','Modern Trade',13650,11438,4299,37.59,74.99,235,4064,false],['C18','Customer 18','Marketplace',14100,12619,5016,39.75,29.99,104,4912,false],['C19','Customer 19','D2C',14550,13501,6555,48.55,7,26,6529,false],['C20','Customer 20','Wholesale',15000,13470,5506,40.88,59.99,221,5285,true],['C21','Customer 21','General Trade',15450,14183,5811,40.97,45.01,175,5636,false],['C22','Customer 22','Modern Trade',15900,13324,5007,37.58,75.01,274,4733,false],['C23','Customer 23','Marketplace',16350,14632,5816,39.75,30.01,120,5696,false],['C24','Customer 24','D2C',16800,15590,7569,48.55,7,30,7539,true]
].map((r) => ({id:r[0] as string,name:r[1] as string,channel:r[2] as string,gross:r[3] as number,net:r[4] as number,contribution:r[5] as number,margin:r[6] as number,dso:r[7] as number,wc:r[8] as number,after:r[9] as number,strategic:r[10] as boolean}));
const bn = (v:number) => (v/1000).toFixed(1);
const channels = ['General Trade','Modern Trade','Marketplace','D2C','Wholesale'];
const channelColors:Record<string,string> = {'General Trade':'#0a6351','Modern Trade':'#3b82b6','Marketplace':'#d88b19','D2C':'#8b5cf6','Wholesale':'#9aa3a6'};
const channelSummary = channels.map((channel) => { const rows=customers.filter(c=>c.channel===channel); const sum=(key:keyof Customer)=>rows.reduce((a,c)=>a+Number(c[key]),0); const net=sum('net'), after=sum('after'), contribution=sum('contribution'); return {channel,count:rows.length,net,contribution,after,margin:after/net*100,dso:sum('dso')/rows.length}; });

function Section({n,title,aside,children}:{n:number;title:string;aside?:React.ReactNode;children:React.ReactNode}) { return <section className="cust4-section"><div className="cust4-section-title"><h2><span>{n}</span>{title}</h2>{aside}</div>{children}</section>; }
function Metric({label,value,detail,icon:Icon}:{label:string;value:string;detail:string;icon:typeof BarChart3}) { return <div className="cust4-metric"><Icon size={20}/><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>; }
function MiniBars({items,color='#0a6351'}:{items:{label:string;value:number}[];color?:string}) { const max=Math.max(...items.map(i=>i.value)); return <div className="cust4-bars">{items.map(i=><div className="cust4-bar-row" key={i.label}><span>{i.label}</span><div><i style={{width:`${Math.max(8,i.value/max*100)}%`,background:color}}/></div><b>{i.value.toFixed(1)}</b></div>)}</div>; }

export default function ProfitabilityPageFour() {
  const [selectedId,setSelectedId]=useState('C06');
  const selected=customers.find(c=>c.id===selectedId) ?? customers[5];
  const topGross=[...customers].sort((a,b)=>b.gross-a.gross).slice(0,5);
  const topAfter=[...customers].sort((a,b)=>b.after-a.after).slice(0,5);
  const strategic=customers.filter(c=>c.strategic);
  const total={gross:288300,net:256287,contribution:103221,wc:3085,after:100136,ar:30844};
  const margin=total.after/total.net*100;
  return <div className="cust4-page">
    <div className="cust4-hero"><div className="cust4-hero-copy"><div className="cust4-kicker">CUSTOMER &amp; CHANNEL PROFITABILITY</div><h1>Revenue quality changes when customer economics are viewed after working-capital cost.</h1><p>FY2025 customer-profitability rehearsal — connecting gross-to-net, service cost, contribution, accounts receivable and working-capital cost to reveal which accounts and channels truly create economic value.</p><div className="cust4-actions"><a href="#commercial">← Back to Commercial</a><a href="#costing">View Cost &amp; Inventory →</a></div></div><div className="cust4-hero-panel"><b><ShieldCheck size={18}/> ACCOUNT ECONOMICS</b><h3>Protect profitable growth,<br/>not revenue at any cost.</h3><div><span>Customers <strong>24</strong></span><span>After-WC Margin <strong>39.1%</strong></span><span>Portfolio DSO <strong>43.9d</strong></span><span>Top-5 After-WC Value Share <strong>30.9%</strong></span></div><em>SYNTHETIC REHEARSAL</em></div></div>
    <div className="cust4-context"><span><CalendarIcon/> <b>Period</b>FY2025</span><span><Store size={21}/> <b>View</b>Customer Profitability</span><span><Users size={21}/> <b>Customers</b>24</span><span><Database size={21}/> <b>Evidence</b>Synthetic Rehearsal</span><span><TrendingUp size={21}/> <b>Value Lens</b>After-WC Contribution</span><span><ShieldCheck size={21}/> <b>Scope</b>Standalone Economics Layer</span></div>
    <main className="cust4-main">
      <Section n={1} title="Profitability Scorecard"><div className="cust4-score-grid"><Metric icon={Users} label="Customers" value="24" detail="Synthetic rehearsal"/><Metric icon={CircleDollarSign} label="Net Sales" value="256.3bn" detail="VND bn"/><Metric icon={Target} label="Contribution" value="103.2bn" detail="Pre-WC"/><Metric icon={WalletCards} label="After-WC Contribution" value="100.1bn" detail="Cash-adjusted"/><Metric icon={TrendingUp} label="Contribution Margin" value="40.3%" detail="Pre-WC"/><Metric icon={Clock3} label="Portfolio DSO" value="43.9d" detail="AR-weighted"/></div><div className="cust4-secondary"><span>🧾 WC Cost <b>3.1bn</b></span><span>▣ AR Balance <b>30.8bn</b></span><span>◔ Top-5 Sales Share <b>28.6%</b></span><span>◷ Top-5 Value Share <b>30.9%</b></span><span>♜ Strategic Accounts <b>7</b></span></div></Section>
      <Section n={2} title="From Gross Sales to After-WC Contribution" aside="(VND bn)"><div className="cust4-bridge"><div className="cust4-waterfall">{[['Gross Sales',288.3,'start'],['Discounts',-14.3,'down'],['Rebates',-13.5,'down'],['Returns',-4.2,'down'],['Net Sales',256.3,'start'],['COGS',-141.4,'down'],['Delivery',-8.1,'down'],['Customer Support',-3.5,'down'],['Contribution',103.2,'start'],['Working-Capital Cost',-3.1,'down'],['After-WC',100.1,'start']].map(([label,value,tone],i)=><div key={String(label)} className={`wf-col ${tone}`}><div className="wf-bar" style={{height:`${Math.max(18,Math.abs(Number(value))/288.3*125)}px`}}><b>{Number(value)<0?'(':''}{Math.abs(Number(value)).toFixed(1)}{Number(value)<0?')':''}</b></div><span>{label}</span></div>)}</div><p className="cust4-footnote">◆ Working-capital cost reduces portfolio contribution margin by ~1.2pp.</p></div></Section>
      <Section n={3} title="Customer Profitability Map"><div className="cust4-two-col"><div className="cust4-card"><div className="cust4-scatter"><span className="scatter-y">After-WC Margin (%)</span><span className="scatter-x">Net Sales (VND bn)</span><div className="scatter-mid"/><div className="scatter-vline"/>{customers.map(c=><button key={c.id} title={`${c.id} · ${bn(c.net)}bn · ${c.margin.toFixed(1)}%`} aria-label={`Select ${c.id}`} onClick={()=>setSelectedId(c.id)} className={selectedId===c.id?'selected':''} style={{left:`${5+(c.net/16000)*86}%`,bottom:`${8+(c.margin/55)*82}%`,width:`${12+Math.min(c.after/7600,1)*12}px`,height:`${12+Math.min(c.after/7600,1)*12}px`,background:channelColors[c.channel]}}>{c.id==='C06'?'C06':''}</button>)}</div></div><div className="cust4-card cust4-insight"><h3>Customer Profitability Map</h3><p>Bubble size = After-WC Contribution</p><div className="cust4-legend">{channels.map(ch=><span key={ch}><i style={{background:channelColors[ch]}}/>{ch}</span>)}</div><div className="cust4-callout"><AlertTriangle size={16}/> C06 combines scale with weak after-WC economics; review terms before protecting incremental volume.</div></div></div></Section>
      <Section n={4} title="Channel Profitability After Working Capital"><div className="cust4-two-col"><div className="cust4-card"><table className="cust4-table"><thead><tr><th>Channel</th><th>Customers</th><th>Net Sales</th><th>Contribution</th><th>After-WC</th><th>Margin</th><th>DSO</th></tr></thead><tbody>{channelSummary.map(r=><tr key={r.channel}><td><i className="channel-dot" style={{background:channelColors[r.channel]}}/>{r.channel}</td><td>{r.count}</td><td>{bn(r.net)}</td><td>{bn(r.contribution)}</td><td><b>{bn(r.after)}</b></td><td>{r.margin.toFixed(2)}%</td><td>{r.dso.toFixed(1)}d</td></tr>)}<tr className="total"><td>Total</td><td>24</td><td>256.287</td><td>103.221</td><td>100.136</td><td>39.07%</td><td>43.92d</td></tr></tbody></table></div><div className="cust4-card cust4-side-note"><Scale size={28}/><h3>Account economics lens</h3><p>D2C combines the highest after-WC margin with the shortest DSO, while Modern Trade carries the largest working-capital burden.</p><strong>Protect cash-adjusted contribution, not volume alone.</strong></div></div></Section>
      <Section n={5} title="Customer Concentration"><div className="cust4-two-col"><div className="cust4-card"><h3>Top 5 by Gross Sales <small>(VND bn)</small></h3><MiniBars items={topGross.map(c=>({label:`${c.id}  ${c.name}`,value:c.gross/1000}))}/><div className="cust4-share">Top-5 Gross Sales Share <b>28.62%</b></div></div><div className="cust4-card"><h3>Top 5 by After-WC Contribution <small>(VND bn)</small></h3><MiniBars color="#138b68" items={topAfter.map(c=>({label:`${c.id}  ${c.name}`,value:c.after/1000}))}/><div className="cust4-share">Top-5 After-WC Value Share <b>30.88%</b></div></div></div></Section>
      <Section n={6} title="Strategic Account Economics"><div className="cust4-card"><div className="cust4-strategic-kpis"><span>Strategic Customers <b>7</b></span><span>Gross Sales <b>91.8bn</b></span><span>Net Sales <b>81.0bn</b></span><span>After-WC Contribution <b>29.6bn</b></span><span>After-WC Value Share <b>29.6%</b></span></div><p className="cust4-strategic-list">Strategic customers: <b>C04, C06, C08, C12, C16, C20, C24</b></p><div className="cust4-card-note"><ShieldCheck size={16}/> Strategic importance should not exempt account economics from review.</div></div></Section>
      <Section n={7} title="Account Review Case — C06" aside="(VND bn)"><div className="cust4-two-col"><div className="cust4-card"><div className="cust4-waterfall compact">{[['Gross Sales',18,'start'],['Discounts',-1.8,'down'],['Rebates',-1.6,'down'],['Returns',-.2,'down'],['Net Sales',14.4,'start'],['COGS',-10.9,'down'],['Delivery',-1.1,'down'],['Support',-.3,'down'],['Contribution',2.1,'start']].map(([label,value,tone])=><div key={String(label)} className={`wf-col ${tone}`}><div className="wf-bar" style={{height:`${Math.max(12,Math.abs(Number(value))/18*100)}px`}}><b>{Number(value)<0?'(':''}{Math.abs(Number(value)).toFixed(1)}{Number(value)<0?')':''}</b></div><span>{label}</span></div>)}</div><div className="cust4-c06-metrics"><span>AR Balance <b>3.5bn</b></span><span>DSO <b>88.72d</b></span><span>WC Cost <b>0.35bn</b></span><span>After-WC Contribution <b>1.75bn</b></span><span>After-WC Margin <b>12.15%</b></span><span>Payment Terms <b>90d</b></span></div></div><div className="cust4-card cust4-review"><div className="cust4-review-badge"><AlertTriangle/> REVIEW TERMS</div><h3>C06 is large in revenue but weak in after-WC value.</h3><p>Review trade terms, service cost and payment terms before protecting incremental volume.</p><div className="cust4-compare"><span>Gross sales share <b>6.2%</b></span><span>After-WC value share <b>1.7%</b></span></div></div></div></Section>
      <Section n={8} title="Customer Priority Table"><div className="cust4-card"><table className="cust4-table priority"><thead><tr><th>Customer</th><th>Channel</th><th>Strategic</th><th>Net Sales</th><th>CM</th><th>DSO</th><th>After-WC Margin</th><th>After-WC Contribution</th><th>Review Status</th></tr></thead><tbody>{[...customers].sort((a,b)=>b.after-a.after).slice(0,8).map(c=><tr key={c.id} className={c.id==='C06'?'risk-row':''}><td><b>{c.id}</b> {c.name}</td><td>{c.channel}</td><td>{c.strategic?'✓':'—'}</td><td>{bn(c.net)}</td><td>{c.margin.toFixed(2)}%</td><td>{c.dso.toFixed(1)}d</td><td>{(c.margin-c.wc/c.net*100).toFixed(2)}%</td><td><b>{bn(c.after)}</b></td><td><span className={`status ${c.id==='C06'?'review':c.after>5000?'protect':'monitor'}`}>{c.id==='C06'?'REVIEW TERMS':c.after>5000?'PROTECT':'MONITOR'}</span></td></tr>)}</tbody></table></div></Section>
      <Section n={9} title="Management Actions"><div className="cust4-actions-grid">{[['1','Review C06 trade terms','before protecting incremental volume.',Scale],['2','Prioritize Modern Trade','term and service-cost review.',FileText],['3','Protect high-after-WC-value D2C','accounts with strong cash economics.',ShieldCheck],['4','Track concentration separately','for top-sales and top-value cohorts.',BarChart3]].map(([n,t,d,Icon])=><div key={String(n)}><b>{n}</b><Icon size={27}/><strong>{t}</strong><p>{d}</p></div>)}</div></Section>
      <Section n={10} title="Management Takeaway"><div className="cust4-takeaway"><p><Users/>The 24-customer rehearsal generates <b>103.2bn</b> contribution and <b>100.1bn</b> after-WC contribution.</p><p><ArrowDownRight/>Working-capital cost reduces contribution margin by about <b>1.2pp</b>.</p><p><ShieldCheck/>Channel economics differ materially: D2C is strongest after-WC while Modern Trade is most working-capital intensive.</p><p><AlertTriangle/>C06 is large in revenue but weak in after-WC value.</p><p><Target/>Revenue ranking and economic-value ranking are not the same.</p></div></Section>
      <Section n={11} title="Evidence & Scope Boundary"><div className="cust4-evidence"><div className="cust4-badges"><b>SYNTHETIC-REHEARSAL</b><b>24 CUSTOMERS</b><b>AFTER-WC ECONOMICS</b><b>STANDALONE SCOPE</b></div><p>This page is a standalone synthetic customer-economics rehearsal for analysis and decision-support. The results are included in the GitHub/Drive deliverable, but they are a separate analytical layer and must not be added to or reconciled with the core FY2025 management P&amp;L universe used on Pages 1–3.</p><span><ShieldCheck size={18}/> SEPARATE FROM CORE P&amp;L · PAGES 1–3</span></div></Section>
    </main>
  </div>;
}
function CalendarIcon(){ return <span className="calendar-icon">▣</span>; }
